### ISSUE TITLE
Sidebar Open Close Button should always stay on top

### ISSUE THREAD

**Issue by antrikshpatel** [creativetimofficial/material-dashboard-pro-angular#10]
Does it have the option whereby the sidebar open/close button stays on top when viewed on the phone?

**Comment by alexandru-paduraru** [comment]
@antrikshpatel thank you for the suggestion. You can simply achieve that by adding the class `.fixed-top` to the `div.navbar` and the move the whole `<navbar-cmp>` outside of the `div.main-panel` like in this example:

<img width="1019" alt="screen shot 2017-05-16 at 23 52 15" src="https://cloud.githubusercontent.com/assets/2517758/26127740/e019a578-3a92-11e7-84f0-0e3a41232cb0.png">

Then the navbar will be on top visible always.

Please let us know if that was working for you.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Navbar fixed top was added in the documentation for v1.2.0 CLI version.
