### ISSUE TITLE
Navbar and Bootstrap Issues with routed parameters

### ISSUE THREAD

**Issue by WaleedZ90** [creativetimofficial/material-dashboard-pro-angular#101]
This issue is composed of two points:
- Navbar
- bootstrap.min.css and all the css files imported in the index.html

Scenario"

- Create a page example PersonList and create another page PersonDetails

- Make a router for these two components

First router to be accessed by this path "/persons"
Second router to be accessed by this path "/persons/:id"

- In PersonList page make a link that redirects to PersonDetails page.

- After clicking the link **and then Refreshing.**

Output is:
bootstrap.min.css, material-dashboard.css, demo.css are no longer imported so the layout becomes messed up.

the navbar changes its title to "Dashboard".

I've tried to import these css files in the angular-cli.json but it generates so many errors i don't understand why but i do believe the issue is with how these files are imported.

**Comment by chelaruc** [comment]
Hi @WaleedZ90! Thank you for using our product! Can you tell me what version of browser and project do you have?

Best,
Ciprian!

**Comment by WaleedZ90** [comment]
Browser : Google Chrome latest version Version 61.0.3163.100 (Official Build) (64-bit)
Project : v1.4.1

**Comment by chelaruc** [comment]
@WaleedZ90 Can you add these lines in `angular-cli.json`:
```
 "styles": [
          "../node_modules/bootstrap/dist/css/bootstrap.css",
          "./assets/sass/material-dashboard.scss",
          "./assets/css/demo.css"
      ],
```
and delete this ones from `index.html`:
<img width="829" alt="screen shot 2017-10-12 at 11 23 04" src="https://user-images.githubusercontent.com/22840626/31486311-bd9c74c2-af3f-11e7-808c-5a6ec94c14d4.png">
Tell me if it worked!

Best,
Ciprian

**Comment by WaleedZ90** [comment]
Thank you very much it worked!
