### ISSUE TITLE
Scrolling beyond content

### ISSUE THREAD

**Issue by leeniu** [creativetimofficial/material-dashboard-pro-angular#102]
Hey guys, another scrollling-related thing:

You can scroll beyond the height of your content and I believe that shouldn't be the case. Here is a screenshot from your very own demo at http://md-pro-angular.creative-tim.com/dashboard

![scrollbeyondcontent](https://user-images.githubusercontent.com/15927396/31315675-5518d0c8-ac1d-11e7-957b-9816ce93eda7.PNG)

I have that exact same issue in my app and would love to have it resolved :).

Cheers

Malik

**Comment by chelaruc** [comment]
@leeniu We made an update today and that was fixed. Can you test it?

Best,
Ciprian

**Comment by leeniu** [comment]
Hope this is not a dumb question but is there a convenient way to update? I guess npm update won't do the trick, right? I am a developer customer

**Comment by chelaruc** [comment]
You need to download again the archive or we can give you access to the repository and you can see the updates.
Best, 
Ciprian

**Comment by leeniu** [comment]
Yeah, I'd love to have access to the repo. Right now I am integrating the current project status into the update. I'll let you know how this works out but it looks good at first glance!

Thanks for taking the time.

**Comment by chelaruc** [comment]
@leeniu Can you give me your email address to send you the files with the changes?

**Comment by leeniu** [comment]
I've checked it. This issue is resolved as far as I am concerned
