### ISSUE TITLE
Scrollable divs are not scrolling (perfect-scrollbar issue)

### ISSUE THREAD

**Issue by leeniu** [creativetimofficial/material-dashboard-pro-angular#103]
Sry, me again.

I have a scrollable div in one of my components (see screenshot). When my mouse is within that div and I try to scroll, nothing happens. 

![scrollabledivsnotscrolling](https://user-images.githubusercontent.com/15927396/31315866-6e0a3a28-ac21-11e7-996e-5c4e7dc048c7.PNG)

I am certain that this has to do with the perfect scrollbar plugin. Some weeks earlier I tried to remove that plugin. It broke some other things but the scrollable divs were working again as expected.

Cheers

**Comment by chelaruc** [comment]
@leeniu fixed in #102
