### ISSUE TITLE
Datepicker model value do not set in dynamic assignment

### ISSUE THREAD

**Issue by jariwbh** [creativetimofficial/material-dashboard-pro-angular#104]
Hi,

We have used dynamic fields in our forms. some of the fields are datetime and we load Datepicker dynamically runtime. In this case, model value does not display on the datepicker component. 

Value in static datepicker is working fine.

![image](https://user-images.githubusercontent.com/1841956/31385317-79e2f194-ade0-11e7-96aa-34834b0c60d0.png)

**Comment by chelaruc** [comment]
@jariwbh see this plunker and tell me if it helped you: https://plnkr.co/edit/ucGODHnqlaRi7IgoJNmt?p=preview

Best,
Ciprian

**Comment by jariwbh** [comment]
We are populating form control at run time. and assigning values like below attachment

![datepicker](https://user-images.githubusercontent.com/1841956/31444162-0525b5b0-aeb9-11e7-9c26-1c5a5289f0ea.png)

**Comment by jariwbh** [comment]
element.value = this._bindIdData['property'][key];  

this binding data from db that's not working

**Comment by chelaruc** [comment]
@jariwbh Have you found a solution for this? I would put it in our documentation.
