### ISSUE TITLE
Login page render wrong mobile

### ISSUE THREAD

**Issue by eliesermorais** [creativetimofficial/material-dashboard-pro-angular#106]
The login page os rendering wrong, there is a saúde blank LINE on right, and the box is practicaly full screen. See It on gol.decisao.net on a mobile Chrome, for example.

**Comment by chelaruc** [comment]
@eliesermorais thank you for using our product! To fix that, you need to go in `src/assets/sass/material-dashboard/_responsive.scss` file, on line 307 and delete these lines: 
<img width="563" alt="screen shot 2017-10-11 at 12 10 52" src="https://user-images.githubusercontent.com/22840626/31431761-491ad0a2-ae7d-11e7-9609-a355fc703450.png">

Best,
Ciprian
