### ISSUE TITLE
Datepicker not shown in small viewports 

### ISSUE THREAD

**Issue by fbecaria** [creativetimofficial/material-dashboard-pro-angular#110]
Hi,

I have an issue when trying to select a date with the Datepicker in small viewports. If the datepicker has no space, is not shown (see screenshot attached).

I'm using md-pro-angular version 1.2.1.

Thanks,
![datepicker_issue](https://user-images.githubusercontent.com/7152832/31562576-64cbf716-b032-11e7-90cd-217dd0f335cf.png)

**Comment by chelaruc** [comment]
Hi @fbecaria! Thank you for using our product. We are using material datepicker now because that one is with jQuery. You can update to latest version of the product. 

Best,
Ciprian

**Comment by fbecaria** [comment]
Hi! How do I do that? The current version was purchased by a business
partner and he didn't receive any notification about an upgrade.

Thanks,
Federico

**Comment by alexandru-paduraru** [comment]
@fbecaria I've just sent you an invitation to our private repo for customers. Please check the branch 1.4.4 and you will see exactly what changes we did to the files. Hope this helps.

Best,
Alex
