### ISSUE TITLE
Wizard on Mobile Not Displaying Tabs Correctly

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-dashboard-pro-angular#111]
When using the twitter bootstrap wizard, the tabs aren't resizing correctly on mobile.

[visual example](https://imgur.com/a/v3aOj)

**Comment by alexandru-paduraru** [comment]
@elvnthaus thank you for the information. We will have a look and come back with a solution. 

Best,
Alex

**Comment by chelaruc** [comment]
Hi, @elvnthaus! For fixing the issue, we will attach `wizard.component.ts` file and what you have to do is to replace in the `src/app/forms/wizard/wizard.component.ts` file with the attached one.
[wizard.component.ts.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1391324/wizard.component.ts.zip)

All the best,
Ciprian

**Comment by elvnthaus** [comment]
Thanks!
