### ISSUE TITLE
time picker

### ISSUE THREAD

**Issue by elvisgn** [creativetimofficial/material-dashboard-pro-angular#113]
Understand that angular material does not have a timepicker, but there are a few github projects that do identical in design.

I tried using them but the alignment and UX feel is not similar to the datepicker.

Would appreciate if the team could add support for this.

**Comment by chelaruc** [comment]
Hi @elvisgn! Thank you for using our product! Can you give us more details and maybe an archive with your project?

Best,
Ciprian

**Comment by elvisgn** [comment]
Hi Ciprian,
Thanks for your response.

Following is the code I'm using for time input...notice the alignment with the datepicker. Also, which attributes are necessary ?
```
<div class="row">
	<div class="col-md-6">
		<md-datepicker-toggle mdSuffix [for]="startDatePicker"></md-datepicker-toggle>
		<md-input-container>
			<input mdInput [mdDatepicker]="startDatePicker" name="startDatePicker" [(ngModel)]="conference.startDate" placeholder="Start Date">
		</md-input-container>
		<md-datepicker #startDatePicker [touchUi]="touch" [startView]="'month'"></md-datepicker>
	</div>
	<div class="col-md-6">
		<input mdInput type="time" class="form-control" id="startTimePicker" name="startTimePicker" ng-model="conference.timeStart">
	</div>
</div>
```
The UI is based on the validation and extended forms snippets.
![screen shot](https://user-images.githubusercontent.com/8165850/31768626-37a9fcc0-b4e1-11e7-919b-4f5f48cbdabf.png)

**Comment by chelaruc** [comment]
Hi, @elvisgn! Sorry for the late response! We changed validation forms in v1.4.5 because it had some errors. Please check the new one and tell me if the error persisting.

All the best,
Ciprian

**Comment by drenda** [comment]
A time picker component would be very useful in the theme.
