### ISSUE TITLE
Uploading File: Error with Preview

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-dashboard-pro-angular#114]
When uploading a file using the wizard, there should be a preview of the file after selection but the jquery isn't working properly.

I thought it might just be my project code but the same error is happening on the theme preview

[ERROR: this.readURL is not a function at HTMLInputElement](https://imgur.com/a/CDR4y)

Problem code:
````
readURL(input: any) {
    if (input.files && input.files[0]) {
      const reader = new FileReader();
      reader.onload = function (e: FileReaderEvent) {
        $('#wizardPicturePreview').attr('src', e.target.result).fadeIn('slow');
      };
      reader.readAsDataURL(input.files[0]);
    }
  }

ngOnInit() {
    // Prepare the preview for profile picture
    $('#wizard-picture').change(function() {
      this.readURL(this); <<<<<<<<<
    });
}
````

**Comment by chelaruc** [comment]
Hi @elvnthaus! I fixed the error and I have attached the file you need to replace.
[wizard.component.ts.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1393808/wizard.component.ts.zip)

Best,
Ciprian

**Comment by elvnthaus** [comment]
Thanks
