### ISSUE TITLE
Problems with navbar

### ISSUE THREAD

**Issue by enovaski** [creativetimofficial/material-dashboard-pro-angular#117]
When I resize my browser to a smaller screen, I click to open the sidebar and maximize (full screen), the items that are in the navbar within the `<div class="collapse navbar-collapse">` do not reappear on the screen, they return only when I step or mouse or click on the screen.
![error screen](https://user-images.githubusercontent.com/9543316/31832043-42056f24-b5a4-11e7-901c-055764880818.PNG)
![error-free screen](https://user-images.githubusercontent.com/9543316/31832044-422f2c1a-b5a4-11e7-815f-232310974795.PNG)

**Comment by chelaruc** [comment]
Hi, @enovaski! Thank you for using our product! Can you give me more details and an archive for testing?

Best,
Ciprian

**Comment by enovaski** [comment]
[cemiterio.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1434885/cemiterio.zip)
Hello,

the error occurs when in the following situation:
I minimize the page, click on the button to open the menu and maximize the page again, after that the content only appears when clicking or hovering the page. follows test design.

**Comment by chelaruc** [comment]
Hi, @enovaski! I've made some test and fixed that. I've deleted `isMobileMenu()` function and added `onResize(event)` function and you need to change `*ngIf` from .html with `(window:resize)="onResize($event)"`. I'll attach the files you need to replace and you will see the changes. Although, you need to do the same changes in sidebar component. 
[Archive.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1438163/Archive.zip)

Best,
Ciprian

**Comment by enovaski** [comment]
Now it worked perfectly, thank you very much for the help.
