### ISSUE TITLE
Style problem upgrading material

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#119]
I have recently upgrade material to 2.0.0.beta12, and I see some style problems in mat-select
![cattura](https://user-images.githubusercontent.com/27501745/31852638-59812634-b67b-11e7-911f-5accacafffd7.PNG)
Now mat-select lives inside mat-form-field.
Do you have a plan to solve this?

**Comment by chelaruc** [comment]
Hi, @lippomano! We're working on it and will do an update this week with the fix!

Best, 
Ciprian

**Comment by chelaruc** [comment]
Fixed in v1.4.5
