### ISSUE TITLE
Problems in lbd folder

### ISSUE THREAD

**Issue by hguaymas** [creativetimofficial/material-dashboard-pro-angular#12]
Hi, I'm trying to run the application with npm start or ng serve, but I have errors when compile:

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (66,9): Identifier 'Chartist' must be imported from a module

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (66,9): Value of type 'IChartistPieChart' is not callable. Did you mean to include 'new'?

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (69,9): Identifier 'Chartist' must be imported from a module

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (69,9): Value of type 'IChartistLineChart' is not callable. Did you mean to include 'new'?

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (72,9): Identifier 'Chartist' must be imported from a module

ERROR in E:/web_projects/anunciate_front/src/app/lbd/lbd-chart/lbd-chart.component.ts (72,9): Value of type 'IChartistBarChart' is not callable. Did you mean to include 'new'?

ERROR in E:/web_projects/anunciate_front/src/app/lbd/services/notification.service.ts (59,5): Cannot find name '$'.

I don't know how to fix these errors. Can you help me please? Thanks and sorry for my english

**Comment by alexandru-paduraru** [comment]
@hguaymas are you using Light Bootstrap Dashboard or Material Dashboard PRO? This is the repo for Material Dashboard PRO.

Best,
Alex

**Comment by alexandru-paduraru** [comment]
Fixed in v1.2.0 CLI Version. Please check it and let us know if everything is fine.

Best,
Alex
