### ISSUE TITLE
Koala can't compile the material-dashboard.scss

### ISSUE THREAD

**Issue by dwaxgio** [creativetimofficial/material-dashboard-pro-angular#120]
You can change the default colors via variables from SASS:

You can find the colors in assets/sass/material-dashboard/_variables.scss starting with line 28 where is the primary color set: $brand-primary: $purple !default;. All the possible colors are in assets/sass/material-dashboard/_colors.scss
Add the SASS folder from assets/sass/ to a new project inside Koala Compiler and find the file material-dashboard.scss, it will be the one in Green.
Right click on that file and set the output path, it must be in assets/css/ so anything that you compile will overwrite the original material-dashboard.css
Press on compile and everything will be done automatically.

When I press compile, koala throws this error:

![problem_koala](https://user-images.githubusercontent.com/31946346/31857359-45949e40-b6a2-11e7-8f04-be5ed42c76c7.PNG)

Any idea about how to resolve this, thanks

**Comment by chelaruc** [comment]
Hi, @dwaxgio! Thank you for using our product! We don't use Koala anymore in our latest version 1.4.4. Can you make an update to it?

Best,
Ciprian
