### ISSUE TITLE
Multilevel menu in sidebar

### ISSUE THREAD

**Issue by emVdovin** [creativetimofficial/material-dashboard-pro-angular#121]
Hi 

Do you have an example how to create a multilevel sidebar menu?

Regards

**Comment by chelaruc** [comment]
Hi, @emVdovin! Thank you for using our product and we are sorry for the late response! I'll attach an archive with sidebar.component.ts and sidebar.component.html. All you need to do is to replace them with your files. You can see an example with a multilevel sidebar in components -> buttons.
[Archive.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1437787/Archive.zip)

All the best,
Ciprian

**Comment by chelaruc** [comment]
This is the archive with the modifications for latest versions:
[multilevel-sidebar.zip](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/files/2071187/multilevel-sidebar.zip)

**Comment by Leonardo-demeloweb** [comment]
@chelaruc  Hello how the thing is going? I just tried to use the last solution provided for multilevel menu in sidebar (in the v.7.0.2) and unfortunately does not work. 

Do you think to be possible to implement a 'n' number of childrens inside submenus dynamically? E.g. I am receiving an Array of Objects childrens inside of childrens 'n' times. In typescript logic is OK to us. How do you suggest to implement it binding on html template?

**Comment by chelaruc** [comment]
In our case, for every child, you need to modify the array of routes and add a parameter for it. I don't know how to implement an 'n' number of children.

**Comment by elvisgn** [comment]
I had the similar challenge in issue [#210](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/210).

The solution is to use named router-outlets' whenever you need to add/remove a sidemenu (you'll also need to use router-outlets for the page views, else the paths won't match). By adding/removing the sidemenu at runtime, you will be able to change the titles etc dynamically.
