### ISSUE TITLE
Problem with forms with new validation

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#123]
vimeo.com/240352189

As you can see in the video something probably try to apply and remove the `has error` class to the field, maybe your new validation forms?

In the fields when I see the error messages probably the fields have to be red, now some field became red only if something is typed:
![correct](https://user-images.githubusercontent.com/27501745/32143162-befa7ecc-bca5-11e7-8afe-8bd05d03afdb.PNG)

And I don't know if is a best practice to use the `input type="number"` because for example in firefox I can write letters into the field:
![numb valid](https://user-images.githubusercontent.com/27501745/32143099-d88e196c-bca4-11e7-8e5d-ca706f8f717e.PNG)

tested in your live preview

**Comment by chelaruc** [comment]
Hi, @lippomano! To fix that, you need to go in `src/app/app.component.ts` file and delete line 19: `$.material.options.autofill = true;`
Tell me if this worked for you!

Best,
Ciprian

**Comment by lippomano** [comment]
yes probably problem solved, I'll do other tests
