### ISSUE TITLE
Navigation. sidebar

### ISSUE THREAD

**Issue by BobaFett58** [creativetimofficial/material-dashboard-pro-angular#124]
Hey, creative-tim!
I have some problem with this template in browser Edge. Navigation doesn't work. (In live preview it's doesn't work too)
Best regards, Denis.

Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Comment by chelaruc** [comment]
Hi, @BobaFett58! Thank you for using our product! I made some changes for fixing that. All you need to do is to replace these two files in your project: `src/app/app.component.ts` and `src/app/layouts/admin/admin.component.ts`
[changes.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1434756/changes.zip)

All the best,
Ciprian

**Comment by BobaFett58** [comment]
Hi, @chelaruc! Thanks for your quick support, if u will push this changes to master, don't forget to delete this strangers 'todo' or i don't know what is it, but it can brake some code :)
![hz](https://user-images.githubusercontent.com/16953976/32375058-8eac14a2-c0a0-11e7-86d7-b6a5caebff02.png)

line 38 and 42.

Best regards, Denis.

**Comment by chelaruc** [comment]
@BobaFett58 thank you for pointing this! You can delete them, it's just random words for tests.
 
Best,
Ciprian
