### ISSUE TITLE
Does this theme support rtl ?

### ISSUE THREAD

**Issue by uchar** [creativetimofficial/material-dashboard-pro-angular#125]
Is RTL supported for this theme ? 
If not is there any plan to support it in the feature ?

**Comment by chelaruc** [comment]
Hi, @uchar! Thank you for your interest in our product! Unfortunately, it does not support RTL :(

**Comment by rakesh410** [comment]
Hi Any timeline for this, we purchased this theme before confirming about RTL and now stuck here.

**Comment by alexandru-paduraru** [comment]
@rakesh410 we will have the RTL version as soon as we release the BS4 version. In the meantime, please check this Bootstrap RTL library: https://github.com/morteza/bootstrap-rtl and let us know how it works.

Best,
Alex
