### ISSUE TITLE
No File Input

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-dashboard-pro-angular#127]
Can we get a file input added to the template? There select inputs, dropdown inputs, etc but no file input for uploading documents like png, jpg, etc.

**Comment by chelaruc** [comment]
Hi, @elvnthaus! Thank you for using our product! Here is an example of file input: [http://www.jasny.net/bootstrap/javascript/#fileinput-examples](http://www.jasny.net/bootstrap/javascript/#fileinput-examples).

All the best,
Ciprian
