### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by ehdwns980416** [creativetimofficial/material-dashboard-pro-angular#128]
There is a scroll on my page, such as dashboard example.
![image](https://user-images.githubusercontent.com/26425092/32305974-f2785166-bfbb-11e7-9abd-7424c519ac43.png)
But when i want to print with `Ctrl+P` it just print one page.
![image](https://user-images.githubusercontent.com/26425092/32306010-42a2b1f4-bfbc-11e7-9337-cf0aaef59866.png)
How can I print the whole thing?

**Comment by chelaruc** [comment]
Hi, @ehdwns980416! Thank you for using our product! Add this lines of code in `src/assets/sass/material-dashboard/_responsive.scss`:
```
@media print{

    .sidebar{
        display: none !important;
    }

    .main-panel * {
        display: block !important;
        width: 100% !important;
        min-width: 100% !important;
        max-width: none !important;
        max-height: none !important;
        .navbar{
            display: none!important;
        }
    }
    .wrapper{
        height: auto !important;
    }
}
```
We've been able to make some changes to make it print all over the page, but if you find something better than this, please tell us.

All the best,
Ciprian

**Comment by ehdwns980416** [comment]
@chelaruc Thank you for your quick reply. 👍
The problem with which the whole page was not printed was resolved.
But, there is a problem that something is not going to print..
I will use `@media print` to solve the problem.
It has been a great help. Thank you. 😄
