### ISSUE TITLE
scrollbar issue

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#129]
Upgrading from 1.4.3 to 1.4.5 I have some problem with scrollbar, as you can see in the image my page scroll also if there isn't any content to scroll.
![cattura](https://user-images.githubusercontent.com/27501745/32335682-b4a17e44-bfed-11e7-8ca1-695696ccf4e8.PNG)

Same problem in the sidebar and I don't have any errors.

In the app.component 

 ```
 if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {
            let ps = new PerfectScrollbar(elemMainPanel, { wheelSpeed: 2, suppressScrollX: true });
            ps = new PerfectScrollbar(elemSidebar, { wheelSpeed: 2, suppressScrollX: true });
        }
```

and 

```
if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()) {
        const elemMainPanel = <HTMLElement>document.querySelector('.main-panel');
        const ps = new PerfectScrollbar(elemMainPanel);
        ps.update();
      }
```

**Comment by chelaruc** [comment]
Hi, @lippomano! Can you give me your archive on email? email address: ciprian@creative-tim.com

**Comment by drenda** [comment]
Hi, is there some fix about this problem? Thanks

**Comment by lippomano** [comment]
Hi @chelaruc archive for testing sended

**Comment by chelaruc** [comment]
@lippomano I did a few tests and I saw that you deleted the css for the perfect scrollbar library from `angular-cli.json` file. Can you add it again and try again? 
Here is an image with styles from angular-cli.json file:
<img width="749" alt="screen shot 2017-11-10 at 12 09 32" src="https://user-images.githubusercontent.com/22840626/32653311-23a5cc64-c610-11e7-9b97-b384fd1585ee.png">

Best,
Ciprian

**Comment by lippomano** [comment]
Sorry it was my fault.
Thank you very much.
