### ISSUE TITLE
Can't fill datatable.net with ngFor

### ISSUE THREAD

**Issue by serweck** [creativetimofficial/material-dashboard-pro-angular#13]
i'm trying to use a ngFor to fill a datatable. I can show data but the filters, orders, etc... doesn't work.

```
 <tr *ngFor="let factura of listadoFactura">
                    <td>{{factura.NumeroFacture}}</td>
                    <td>{{factura.Type}}</td>
                    <td>{{factura.Emetteur}}</td>
                    <td>{{factura.Client}}</td>
                    <td>{{factura.DateFacture}}</td>
                    <td>{{factura.DateEcheanceReglement}}</td>
                    <td>{{factura.MontantHT}}</td>
                    <td>{{factura.MontantTTC}}</td>
                    <td>{{factura.Statut}}</td>
                    <td>{{factura.MoyenPaiemet}}</td>
                    <td class="text-right">
                      <a href="/home/listado-factura" class="btn btn-simple btn-info btn-icon like"><i class="material-icons">favorite</i></a>
                      <a href="/home/listado-factura" class="btn btn-simple btn-warning btn-icon edit"><i class="material-icons">dvr</i></a>
                      <a href="/home/listado-factura" class="btn btn-simple btn-danger btn-icon remove"><i class="material-icons">close</i></a>
                    </td>
</tr>
```
how can i do it?

**Comment by alexandru-paduraru** [comment]
@serweck thank you for using our product. Please try to initialise the table using data from typescript like this: https://github.com/creativetimofficial/light-bootstrap-dashboard-pro-angular/issues/3

Please let us know if that helped you.

Best,
Alex

**Comment by serweck** [comment]
i'm using v1.1.1

This is the code:
`import { Component, OnInit } from '@angular/core';
import { Facture } from '../../model/listado-factura';
import * as Collections from 'typescript-collections';

declare var $: any;

@Component({
  selector: 'app-listado-factura',
  templateUrl: './listado-factura.component.html',
  styleUrls: ['./listado-factura.component.css']
})
export class ListadoFacturaComponent implements OnInit {

  public listadoFactura: Facture[];

  constructor() { }

  ngOnInit() {
    this.initDataTable();

    this.serviceCall();
  }


  initDataTable() {

    $('#datatables').DataTable({
      'pagingType': 'full_numbers',
      'lengthMenu': [[10, 25, 50, -1], [10, 25, 50, 'All']],
      responsive: true,
      language: {
        search: '_INPUT_',
        searchPlaceholder: 'Search records',
      }

    });


    const table = $('#datatables').DataTable();

    // Edit record
    table.on('click', '.edit', function () {
      const $tr = $(this).closest('tr');

      const data = table.row($tr).data();
      alert('You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.');
    });

    // Delete a record
    table.on('click', '.remove', function (e) {
      const $tr = $(this).closest('tr');
      table.row($tr).remove().draw();
      e.preventDefault();
    });

    // Like record
    table.on('click', '.like', function () {
      alert('You clicked on Like button');
    });

    //  Activate the tooltips
    $('[rel="tooltip"]').tooltip();

  }

  serviceCall() {
    this.listadoFactura = this.MOCK();
  }

  MOCK() {
    return [
      new Facture('AA20170217-0003', 'Majoration', 'Portnet SA', 'MAERSK MAROC', '15/04/2017 00:00', '15/06/2017 00:00', '1200.0 MAD', '1020.0 MAD', 'Facture Payé. attemte confirmation Partenaire', 'Virement Amanpay'),
      new Facture('AA20170217-0002', 'Majoration', 'Portnet SA', 'MAERSK MAROC', '15/04/2017 00:00', '15/06/2017 00:00', '500.0 MAD', '820.0 MAD', 'Non Réglée', 'Amanpay Chèque Virement'),
      new Facture('PPCC20170214-0017', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '567.0 MAD', '500.0 MAD', 'Non Réglée', 'Amanpay'),
      new Facture('PPCC20170214-0010', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '500.0 MAD', '400.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0011', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '600.0 MAD', '570.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0012', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '560.0 MAD', '500.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0013', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '77.0 MAD', '66.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0014', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '99.0 MAD', '88.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0015', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '800.0 MAD', '790.0 MAD', 'Facture Payé. attemte confirmation Partenaire', 'Amanpay'),
      new Facture('PPCC20170214-0016', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '580.0 MAD', '569.0 MAD', 'Non Réglée', 'Amanpay'),
      new Facture('AA20170217-0001', 'Majoration', 'Portnet SA', 'MAERSK MAROC', '15/04/2017 00:00', '15/06/2017 00:00', '1200.0 MAD', '1020.0 MAD', 'Facture Payé. attemte confirmation Partenaire', 'Virement Amanpay'),
      new Facture('AA20170217-0004', 'Majoration', 'Portnet SA', 'MAERSK MAROC', '15/04/2017 00:00', '15/06/2017 00:00', '500.0 MAD', '820.0 MAD', 'Non Réglée', 'Amanpay Chèque Virement'),
      new Facture('PPCC20170214-0018', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '567.0 MAD', '500.0 MAD', 'Non Réglée', 'Amanpay'),
      new Facture('PPCC20170214-0019', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '500.0 MAD', '400.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0020', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '600.0 MAD', '570.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0021', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '560.0 MAD', '500.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0022', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '77.0 MAD', '66.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0023', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '99.0 MAD', '88.0 MAD', 'Non Réglée', 'Virement'),
      new Facture('PPCC20170214-0024', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '800.0 MAD', '790.0 MAD', 'Facture Payé. attemte confirmation Partenaire', 'Amanpay'),
      new Facture('PPCC20170214-0025', 'Principale', 'Portnet SA', 'MAERSK MAROC', '14/04/2017 00:00', '14/06/2017 00:00', '580.0 MAD', '569.0 MAD', 'Non Réglée', 'Amanpay')
    ]
  }
}
`
`          <div class="card-content">
            <h4 class="card-title">Consulter des factures</h4>
            <div class="toolbar">
              
            </div>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th>NumeroFacture</th>
                    <th>Type</th>
                    <th>Emetteur</th>
                    <th>Client</th>
                    <th>DateFacture</th>
                    <th>DateEcheanceReglement</th>
                    <th>MontantHT</th>
                    <th>MontantTTC</th>
                    <th>Statut</th>
                    <th>MoyenPaiement</th>
                    <th class="text-right">Operations</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let factura of listadoFactura">
                    <td>{{factura.NumeroFacture}}</td>
                    <td>{{factura.Type}}</td>
                    <td>{{factura.Emetteur}}</td>
                    <td>{{factura.Client}}</td>
                    <td>{{factura.DateFacture}}</td>
                    <td>{{factura.DateEcheanceReglement}}</td>
                    <td>{{factura.MontantHT}}</td>
                    <td>{{factura.MontantTTC}}</td>
                    <td>{{factura.Statut}}</td>
                    <td>{{factura.MoyenPaiemet}}</td>
                    <td class="td-actions text-right">
                                              <button type="button" rel="tooltip" class="btn btn-info">
                                                  <i class="material-icons">person</i>
                                              </button>
                                              <button type="button" rel="tooltip" class="btn btn-success">
                                                  <i class="material-icons">edit</i>
                                              </button>
                                              <button type="button" rel="tooltip" class="btn btn-danger">
                                                  <i class="material-icons">close</i>
                                              </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>`

The data is showing but appear a line with: No data available in table

And when i click to order by column or change show X rows, the data disappear.

**Comment by pmargom** [comment]
Hi @serweck:

I noticed you have this en the html: **`<table class="table">`**
and in the .ts file you have: **$('#datatables').DataTable()**
Maybe you need to update html code to use the right selector: **`<table id="datatable">`**.

Hope it helps.

On the other hand @alexandru-paduraru you mentioned to use *creativetimofficial/light-bootstrap-dashboard-pro-angular#3* and I'm afraid this issue is regarding **material dasboard**. So please, provide a fix to use datatables.net plugin with **material dashboard**.

Thanks in advance.

**Comment by alexandru-paduraru** [comment]
@serweck we just added in v1.2.0 a working example for the ngFor inside datatables. Please check it and let us know if everything is fine.

Best,
Alex

**Comment by serweck** [comment]
it's work wrong again:
![image](https://user-images.githubusercontent.com/9169130/28059391-6a720d48-6624-11e7-9750-623dd5c0aaf0.png)
![image](https://user-images.githubusercontent.com/9169130/28059424-8d266c3a-6624-11e7-9f9e-39ba3213fdc0.png)

**Comment by tracksimple** [comment]
is there any update on this, how can refresh can be implemented using this as it behave same as above.
Any working example ?

**Comment by serweck** [comment]
Use other suits components, it was with jquery and not npm packages components.

Use MaterialDesing, primeNg ...

**Comment by serweck** [comment]
For me was imposible becouse you need modify the component datatable.net.

I choosen change suits components. with other i have virtual scroll that i think is better than pagination.

**Comment by tracksimple** [comment]
thanks serweck, can you suggest primeNg full fledged example, if it is possible. . virtual scroll seems to be viable solution.

**Comment by serweck** [comment]
no sry, i'm using primeNg in a private solution, but if i need to decide a suit now, i think that i use material desing with Angular 7:
https://material.angular.io/components/table/overview
and
https://material.angular.io/cdk/scrolling/overview

**Comment by stayingcool** [comment]
> it's work wrong again:
> ![image](https://user-images.githubusercontent.com/9169130/28059391-6a720d48-6624-11e7-9750-623dd5c0aaf0.png)
I have the same issue. The table gets loaded with data and shows _`"No data available in table"`_ Is there a solution for this?

**Comment by pmargomclear** [comment]
Hi @serweck , you can do it in this way (sorry for the spanish):

In **html** file, you only need to uses this:

![image](https://user-images.githubusercontent.com/39117018/53692606-ecd9f900-3d8a-11e9-8f32-9af28c21b470.png)

And in **typescript**: 

![image](https://user-images.githubusercontent.com/39117018/53692662-dda77b00-3d8b-11e9-9c7e-8b55c498e67e.png)

If your data comes from an api...

![image](https://user-images.githubusercontent.com/39117018/53692677-06c80b80-3d8c-11e9-8883-8b35ea9c2fc2.png)

And the **setDataTable** function is:

![image](https://user-images.githubusercontent.com/39117018/53692718-9f5e8b80-3d8c-11e9-8c38-1620cd87d2d0.png)

In particular, notice this line:

**$('#data-table-documentos').DataTable(dtOptions);**

as you can see this is the id in html element. So in order the plugin works as you expect, you need to do everything in a **dtOptions** config.

Some sections are collapsed in order to copy and past for you but if you need more explanation, let me know.

Hope this helps.
