### ISSUE TITLE
label color

### ISSUE THREAD

**Issue by BobaFett58** [creativetimofficial/material-dashboard-pro-angular#133]
Hey, Creative-Tim!
When i choose a black theme and a side bar is minimize, label color don't changing to white.

![image](https://user-images.githubusercontent.com/16953976/32439418-eea3e7fe-c2ee-11e7-9497-637743a41415.png)

Best regards, Denis!

**Comment by chelaruc** [comment]
Hi, @BobaFett58! 

Thank you for using our product and for pointing this to us! To fix that, you need to go in `src/assets/sass/material-dashboard/_sidebar-and-main-panel.scss` file and delete the 475-486 lines.

Best,
Ciprian

**Comment by BobaFett58** [comment]
Thanks !

**Comment by chelaruc** [comment]
fixed in v1.4.6
