### ISSUE TITLE
Password match does not works on the Material Dashboard PRO Angular 

### ISSUE THREAD

**Issue by Leonardo-demeloweb** [creativetimofficial/material-dashboard-pro-angular#135]
Material Dashboard PRO Angular forms/validationforms password match does not works, the validation is broken. If some one want to help, lets try on together verify the error.

**Comment by chelaruc** [comment]
Hi @Leonardo-demeloweb! Can you give us more details?

**Comment by Leonardo-demeloweb** [comment]
![image](https://user-images.githubusercontent.com/14796489/32610812-ff067536-c54a-11e7-986d-7ed25733a6e4.png)

**Comment by Leonardo-demeloweb** [comment]
I am exactly with the licensed version for developers of the Material Dashboard PRO Angular.

**Comment by Leonardo-demeloweb** [comment]
@chelaruc Seems that you fixed it at the live preview of this template, perhaps yous guys upgrade to 1.4.5 version. The agency that I am working actually bought the developer license, if you might help us would be great. What should be the best way to get this fixed? Our template is "version": "1.4.1".

**Comment by chelaruc** [comment]
@Leonardo-demeloweb Here is an image with the function for Register Form:
<img width="433" alt="screen shot 2017-11-09 at 16 55 14" src="https://user-images.githubusercontent.com/22840626/32611650-e2ea5a10-c56e-11e7-97b6-d097082d3ad9.png">
How you can see, if the form is valid you will get a message in console with the text 'form submitted', else will be call a function named 'validateAllFormFields':
<img width="447" alt="screen shot 2017-11-09 at 16 58 40" src="https://user-images.githubusercontent.com/22840626/32611835-5786fc3e-c56f-11e7-9b5e-beb1d8dddc10.png">
So, the form is valid when you get in consoel the message 'form submitted'.

Hope this helps you,
Ciprian

**Comment by chelaruc** [comment]
@Leonardo-demeloweb I saw your message and I'm thinking you should download the archive again and see the current validation forms. We've made pretty big changes and all the structure was changed. If you need help with integration, you can send me an email with details at ciprian@creative-tim.com.

Best,
Ciprian

**Comment by Leonardo-demeloweb** [comment]
@chelaruc  as I could check seems a bug at the 1.4.1 version of the Material Dashboard PRO Angular. I mentioned above that we are full licensed to use this template as developers. Where is it placed? I am talking about the password match at the forms/validationforms. I will post the print of the validationforms.component.ts:
![image](https://user-images.githubusercontent.com/14796489/32612307-149491fe-c54f-11e7-8cd9-78ea76f0409b.png)

and here the password validation
![image](https://user-images.githubusercontent.com/14796489/32612356-34bcc32a-c54f-11e7-8f5b-2a4161ec799a.png)

**Comment by chelaruc** [comment]
@Leonardo-demeloweb  You need to go to [https://www.creative-tim.com](https://www.creative-tim.com) and log in. After that, you need to access your profile from navbar and go to My Purchases. I'll attach an image with the navbar:
![screen shot 2017-11-09 at 17 12 43](https://user-images.githubusercontent.com/22840626/32612567-438b995e-c571-11e7-800d-52b50fa837e9.png)
Then you will see what products you bought and download the latest version.

Best,
Ciprian

**Comment by Leonardo-demeloweb** [comment]
@chelaruc OK We shall do this. Our manager must be on charge of. I particularly have been reading the documentation of the 1.4.5 material angular pro dashboard. Do you are proposing a form validation using jquery.validation as new component? What is about typescript and node dependecies?

**Comment by chelaruc** [comment]
@Leonardo-demeloweb the current forms validations are without jquery.validation.
