### ISSUE TITLE
Password match does not works on the Material Dashboard PRO Angular with typescript.

### ISSUE THREAD

**Issue by Leonardo-demeloweb** [creativetimofficial/material-dashboard-pro-angular#136]
@chelaruc Hello how the thing is going with you?

I do not think the issue is closed as you purposed. The form validation delivered to us like full licensed for development is not working properly at this point with typescript. The 1.4.1 version was written on typescript and seems the 1.4.5 version the form.validation is written on jquery. We need the typescript version to be agile with the process. All forms inputs of the project on development actually is implemented. We can not just blow away hours of implementation and development because this punctual bug. The form promised to work at the version 1.4.1 need to be fixed as bug.

**Comment by Leonardo-demeloweb** [comment]
@chelaruc How the thing is going with you? I did not analise the 1.4.5 version of the material ANGULAR pro yet. But I was reading the promises of new components, between then jaquery.validator. Have you solved the issue with passoword match with jquery? The version that I was using it was with Typescript, just the password match does not work properly in there. Here is the link of one of our projects on production (we are a softwares house and the thing must goes as fast as possible).  Check this:

http://nagro.surge.sh

I want to say might be not the best choice to re-work all of this. I just need the password match developed on typescript, as promised. If I need to re-implement all of this a lose time working on other important things, and the project goes on delay.

**Comment by Leonardo-demeloweb** [comment]
@jac0117 can you have a look please?

**Comment by chelaruc** [comment]
@Leonardo-demeloweb The current version(v1.4.5) is without jquery.validation.
