### ISSUE TITLE
bootstrap v4?

### ISSUE THREAD

**Issue by elvnthaus** [creativetimofficial/material-dashboard-pro-angular#137]
Will there be an update for the latest bootstrap update?

**Comment by chelaruc** [comment]
Hi @elvnthaus! Thank you for your interest in our product! Yes, it will be an update in the middle of December! 

Best,
Ciprian

**Comment by eleventhaus** [comment]
Any updates on this?

**Comment by chelaruc** [comment]
Hi, @elvnthaus! We didn't finish Material Dashboard PRO HTML with Bootstrap 4, when this will be finished, the Angular one will be easy to update.

**Comment by eleventhaus** [comment]
Ok thanks for the update! Keep up the great work.

**Comment by FabioMorcillo** [comment]
Hi @chelaruc ,

You have any news to finish this upgrade to Bootstrap 4 and Angular 5 ?

**Comment by eleventhaus** [comment]
Any updates?

**Comment by chelaruc** [comment]
Hi, @eleventhaus  @FabioMorcillo! We've finished the development for Material Kit Pro Bootstrap 4(HTML) and we will start to develop the Material Dashboard Pro Bootstrap 4(HTML), after that we will update the Angular product. I think it will be finished in first week of February. I'm working for the Angular 5 right now and will be updated in v1.5.0. 

All the best,
Ciprian

**Comment by chelaruc** [comment]
@eleventhaus we are trying to work with [@angular/material ](https://github.com/angular/material2).

**Comment by eleventhaus** [comment]
Does @angular/material2 use bootstrap 4? I don't see it on their package.json or in the docs.

**Comment by chelaruc** [comment]
I'm thinking they are using their own CSS, without bootstrap, but I'm not sure.

**Comment by eleventhaus** [comment]
Yes I believe [they conflict](https://www.google.com/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/questions/45497542/can-bootstrap-4-be-integrated-along-with-angular-material-2&ved=2ahUKEwit9c-t5eHYAhVN-GMKHa-XAZ8QjjgwAnoECBMQAQ&usg=AOvVaw30RWzUG75PBacZYaHz_2Q9)

**Comment by bommen** [comment]
With this information, would you consider going all the way with Material
Angular and removing Bootstrap as a dependency of the project? I could
imagine this would require some css to be moved from the bootstrap css to
individual components (like the sidebar and navbar) but in the end the
project would be much cleaner/leaner with just one UI framework as a
dependency.

What are your thoughts on this @chelaruc?

**Comment by darlanads** [comment]
@chelaruc When I bought this dasbhoard, I expected it to be already bootstrap4. I bought with the user euzeli.santos@gmail.com I will be waiting for the update. Still with forecast for the first week of February?

**Comment by alexandru-paduraru** [comment]
@bommen @darlanads we are working for Bootstrap 4 release for the HTML version, the one without Angular. As soon as we finish that, probably in a couple of days, we will decide which is the best option for further development of the Angular. With or without Bootstrap? What's your opinion about that @darlanads? As I know the opinion of @bommen 

Best,
Alex

**Comment by eleventhaus** [comment]
This template should stick with Bootstrap 4 as that was what was advertised at the time of purchase.

Perhaps create another template with Angular Material CDK for those who would like to use it?

**Comment by Kalki5** [comment]
@chelaruc @alexandru-paduraru I would prefer to go with Bootstrap 4 since it would help a lot in consumer's perspective.

**Comment by Kalki5** [comment]
Any updates on this?

**Comment by chelaruc** [comment]
@Kalki5 we will launch the HTML version next week, then we will launch the Angular version. Sorry for this but things were more complicated than we expected with the BS3 to BS4 conversion.

All the best,
Ciprian

**Comment by Kalki5** [comment]
@chelaruc Thanks. Eagerly waiting for BS4 release of MD-pro-angular.

**Comment by chelaruc** [comment]
Fixed in v2.0.0

**Comment by Kalki5** [comment]
Thank You @chelaruc .
The documentation isn't updated yet.

**Comment by chelaruc** [comment]
@Kalki5 thx for point this to me. I'll update the documentation today
