### ISSUE TITLE
[Bug] Datepicker not work inside a modal

### ISSUE THREAD

**Issue by gogo217** [creativetimofficial/material-dashboard-pro-angular#138]
> [Angular Material Datepicker](https://material.angular.io/components/datepicker/overview) doesn't work in side a bootstrap modal , and I can see the same issue with [Bootstrap Datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker).  Updating `z-index` is not helpful. 

_I am on the v1.4.5 now._

![image](https://user-images.githubusercontent.com/20570634/32823063-7c22034e-ca16-11e7-8525-58f04ae99b05.png)

**Comment by chelaruc** [comment]
Hi, @gogo217! Thank you for using our product! To fix this you need to go in `src/assets/sass/material-dashboard/_dialogs.scss` file and add these lines of code at the end of the file:
```
.modal-backdrop{
    z-index: 1030;
}
.modal{
    z-index: 1031;
}
```
Tell me if it worked for you!

All the best,
Ciprian

**Comment by gogo217** [comment]
Seems to work now. Thanks
