### ISSUE TITLE
Style ProfilePics into table rows

### ISSUE THREAD

**Issue by elvisgn** [creativetimofficial/material-dashboard-pro-angular#139]
Hi,
How can we accurately position a profile image into the table row (as in attached image) ? The existing class of 'photo' does not work. Tried writing custom classes, but getting the shown output.
<img width="909" alt="profilepic" src="https://user-images.githubusercontent.com/8165850/32978263-e4a0b77e-cc57-11e7-8ba6-b07657762d05.png">
`.userThumbnail {
    width: 36px;
    height: 36px;
    overflow: hidden;
    border-radius: 50%;
    // z-index: 5;
    box-shadow: 0 10px 30px -12px rgba(0, 0, 0, 0.42), 0 4px 25px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
}`

**Comment by chelaruc** [comment]
Hi, @elvisgn! I'll attach some images with our tests:
<img width="623" alt="screen shot 2017-11-22 at 15 17 34" src="https://user-images.githubusercontent.com/22840626/33129430-7e66669a-cf98-11e7-8296-c3dd5fefe4f6.png">
<img width="884" alt="screen shot 2017-11-22 at 15 16 56" src="https://user-images.githubusercontent.com/22840626/33129431-7e810d9c-cf98-11e7-88dd-22edcaa7396d.png">
<img width="739" alt="screen shot 2017-11-22 at 15 16 46" src="https://user-images.githubusercontent.com/22840626/33129432-7e9c8d60-cf98-11e7-8154-ca75f8e1a3b9.png">


All the best,
Ciprian
