### ISSUE TITLE
form-control has no underline 

### ISSUE THREAD

**Issue by GHakopian** [creativetimofficial/material-dashboard-pro-angular#140]
![untitled](https://user-images.githubusercontent.com/15728609/33130890-17f4686a-cf95-11e7-8ec7-71bb2a5865ec.png)

its strange but the underline on the search control wont show unless its active, this works in the live demo thought.

**Comment by chelaruc** [comment]
Hi, @GHakopian! Thank you for using our product! What version do you have? The latest one is 1.4.5.

Best,
Ciprian

**Comment by GHakopian** [comment]
this is the latest version  (1.4.5)

**Comment by chelaruc** [comment]
What browser and what version of it do you use?

**Comment by GHakopian** [comment]
in the screenshot its chrome Version 62.0.3202.94 (Official Build) (64-bit)
the bottom border is working in the newest version of firefox but when i click to type the carrot is lover than the hint text that sais search.

works perfectly in edge

**Comment by GHakopian** [comment]
I solved this by doing the following, it is not the perfect solution but its better than nothing.

in assets > sass > inputs.scss > line 143 
background-size: 0 2px, 100% 1px; changed to   background-size: 0 2px, 100% 2px;

it appears that the background is 1 pixel too far to be visible in chrome.
