### ISSUE TITLE
card-avatar as card title

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#142]
Is there a way to use a card avatar as card header. I would like to put a rounded image as floating header (similar to card-header-icon, but with a rounded image (left aligned))

**Comment by niesteszeck** [comment]
Hi @dragosct10, thanks, that exactly what I wanted to do, now my profile page looks great. This changes will be included in new updates or I'll have to patch by myself?

** One correction to your instructions, the location of the _cards.scss is `src/assets/sass/material-dashboard/_cards.scss` (v1.4.5)

Best regards

**Comment by dragosct10** [comment]
Hi, @niesteszeck! Yes, we will put these changes also in the next update because it's a smart idea, but I think the next update will be in a few weeks so until then you can use the solution that I gave it to you. Thank you! 

Regards,
Dragos

**Comment by niesteszeck** [comment]
Of course, already using it.

I will close this issue as resolved,
have a great day.

**Comment by niesteszeck** [comment]
@dragosct10 @chelaruc 
Hi, how do I use this on 2.0.x?

**Comment by chelaruc** [comment]
@niesteszeck you can change the `i` tag from card-icon with `img` and add this scss code: 
```
.card-header-icon .card-icon img{
  width: 80px;
  height: 80px;
  border-radius: 50%;
}
```

**Comment by chelaruc** [comment]
@niesteszeck why don't you take the second card and change the image?

**Comment by niesteszeck** [comment]
Because I want to be left aligned. 

Using 
```
<div class="card card-profile">
            <!--<div class="card-header card-header-icon">-->
              <div class="card-avatar">
                <img  [src]="profile.imageUrl"/>
              </div>
            <!--</div>-->
```
I got:
![image](https://user-images.githubusercontent.com/3708962/40001522-5bd8718a-575c-11e8-8492-a9a0ef002f94.png)

How can I put it left aligned to the card?

**Comment by niesteszeck** [comment]
Finally i did this.


Add a ne scss file _card-profile-form.scss, import it on _cards.scss and add this src to it:
.card-profile-form {
  @extend %common-card-testimonial;
}

```
.card-profile-form {
  .card-header:not([class*="card-header-"]) {
    background: transparent;
    box-shadow: none;
  }
  .card-avatar {
    max-width: 130px;
    max-height: 130px;
    float: left;
  }
  text-align: left;
}
  text-align: left;
}

```

I got this:
![image](https://user-images.githubusercontent.com/3708962/40002623-447163be-575f-11e8-9433-9cb7f3b80aef.png)


Use it:
```
<div class="col-md-5 ml-auto mr-auto">
          <div class="card card-profile-form">
            <div class="card-header">
              <div class="card-avatar">
                <img [src]="profile.imageUrl"/>
              </div>
            </div>
            <div class="card-body"
                 [formGroup]="mainForm">
```
