### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by BobaFett58** [creativetimofficial/material-dashboard-pro-angular#143]
Hello, when I use datepicker in modal window and trying to pick the date, his open the window under the modal.

![image](https://user-images.githubusercontent.com/16953976/33320190-bfc01840-d441-11e7-8f41-0f3964a2b4bc.png)

**Comment by BobaFett58** [comment]
Oh, sorry I found it on closed issues here (https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/138)

Best regards, Denis.

**Comment by BobaFett58** [comment]
And it doesn't help me, now, after I added this lines of code 
`.modal-backdrop{
    z-index: 1030;
}
.modal{
    z-index: 1031;
}`

I can't do anything on the page. 

![image](https://user-images.githubusercontent.com/16953976/33320718-6adc23ee-d443-11e7-93d5-f9a52f461421.png)

**Comment by chelaruc** [comment]
Hi @BobaFett58,
Thank you for using our product! Can you give me your project for testing?

All the best,
Ciprian

**Comment by BobaFett58** [comment]
[Client.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1514149/Client.zip)

Please :)

**Comment by chelaruc** [comment]
@BobaFett58 go in `src/assets/sass/material-dashboard/plugins/_plugin-datetime-picker.scss` and replace the line 31 with `z-index: 1051 !important;`
Tell me if it worked!

Best,
Ciprian

**Comment by cholivar** [comment]
Hi! how can i set the datepicker to spanish?? 

Please. 
Christian Olivares R.

**Comment by chelaruc** [comment]
@cholivar 
You can see an example here: [https://material.angular.io/components/datepicker/examples](https://material.angular.io/components/datepicker/examples) but is set to French. All you need to do is to set it to Spanish.

Best, 
Ciprian
