### ISSUE TITLE
After click button, shadows maintains visible (as pressed)

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#144]
If I click a button it draws a shadow to make the efect of pressing it, but if I release the button, the shadow maintains till I click other part of the page. This is happening in the demo also

**Comment by chelaruc** [comment]
Hi @niesteszeck!
Thank you for using our product! Can you give me an image example?

Keep in touch, 
Ciprian

**Comment by niesteszeck** [comment]
![normal state not clicked](https://user-images.githubusercontent.com/3708962/33344173-c5c833b0-d466-11e7-8e7c-29309562a5fc.png)


![over state before click it](https://user-images.githubusercontent.com/3708962/33344124-8ecbf018-d466-11e7-8c1d-efce105e691a.png)


![after clicked](https://user-images.githubusercontent.com/3708962/33344125-91284294-d466-11e7-8e48-9ee8b35cd8b6.png)


you can see on picture 2 and 3 a shadow on button LARGE. I espected just to see it on picture 2, not on 3 (after i clicked the

**Comment by chelaruc** [comment]
Hi @niesteszeck! Sorry for the late response! have you found a solution for that? If not, all you have to do is to go in `/src/assets/sass/material-dashboard/_mixins.scss` on line 382 and delete:
````
    &:focus,
    &:active,
````
Tell me if it worked.

All the best, 
Ciprian

**Comment by niesteszeck** [comment]
@chelaruc this works, it will be included in next release?

**Comment by chelaruc** [comment]
@niesteszeck, These lines, but only focus and active:
<img width="672" alt="screen shot 2017-12-20 at 15 46 59" src="https://user-images.githubusercontent.com/22840626/34210015-0a5950a8-e59d-11e7-9f23-d8c0b08da560.png">

**Comment by niesteszeck** [comment]
@chelaruc  it wass on other line number, now it works!

![screenshot_20171220_105230](https://user-images.githubusercontent.com/3708962/34210209-d151068a-e573-11e7-819e-67de51619f6a.png)


this will be included in next release?

**Comment by chelaruc** [comment]
@niesteszeck, For now, this will not be in the next update. Usually, we are doing changes when the minimum number of clients who ask for it is more than 5.

All the best,
Ciprian

**Comment by niesteszeck** [comment]
@chelaruc thanks, so I'll put it on my git as a commit.

Have a great day
