### ISSUE TITLE
Sidebar appear/disappear on swipe (mobile devices) - feature request

### ISSUE THREAD

**Issue by MSkraburski** [creativetimofficial/material-dashboard-pro-angular#145]
I would like to ask for a feature. It would be nice to have a built-in function that shows/hides sidebar on swipe on smartphones & tablets. Or maybe it already exists but I forgot to turn it on. Any ideas?

Regards,
Mikołaj

**Comment by chelaruc** [comment]
Hi, @MSkraburski ! Sorry for the late response! I'll speak with my team and we will see if this feature will be in the next update.

Best,
Ciprian

**Comment by jac0117** [comment]
Was this implemented? @chelaruc

**Comment by chelaruc** [comment]
@jac0117 this wasn't implemented yet :(
