### ISSUE TITLE
Putting a material icon between text expands the height of a text line/row

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#146]
Hello.
I'm wondering how to size the material icons so they don't make the line height bigger where they are put as text, or between it. I tried  using the small class, but then the icon get to small.

Normal size on a
![screenshot_20171205_100635](https://user-images.githubusercontent.com/3708962/33608734-38190056-d9a4-11e7-8e10-9b1d8442ad27.png)
```
<div class="row">
    <label class="col-md-3">Type:</label>
    <div class="col-md-9">
        <i class="text-info material-icons">{{client?.type | lowercase}}</i>
    </div>
</div>
<div class="row">
    <label class="col-md-3">Rut</label>
    <div class="col-md-9">{{client?.rut | rut}}</div>
</div>
<div class="row">
    <label class="col-md-3">Name</label>
    <div class="col-md-9">
        {{client?.name}}
        <span *ngIf="client && client.type==='Person'">{{client.secondName}}</span>
        {{client?.lastName}}
        <span *ngIf="client && client.type==='Person'">{{client.secondLastName}}</span>
    </div>
</div>
```

with small class on the `<i>` tag
![screenshot_20171205_100755](https://user-images.githubusercontent.com/3708962/33608744-461898ba-d9a4-11e7-92d2-2c6ec3b7944e.png)
```
<div class="row">
    <label class="col-md-3">Type:</label>
    <div class="col-md-9">
        <i class="small text-info material-icons">{{client?.type | lowercase}}</i>
    </div>
</div>
<div class="row">
    <label class="col-md-3">Rut</label>
    <div class="col-md-9">{{client?.rut | rut}}</div>
</div>
<div class="row">
    <label class="col-md-3">Name</label>
    <div class="col-md-9">
        {{client?.name}}
        <span *ngIf="client && client.type==='Person'">{{client.secondName}}</span>
        {{client?.lastName}}
        <span *ngIf="client && client.type==='Person'">{{client.secondLastName}}</span>
    </div>
</div>
```

In the first screenshot you can see a different in the space between Type and Rut compared to Rut and Name. On the second one the space is the same, but the icon  is really small, to small.

If I put `style="font-size:19px;"` to the icon, i get the same 25 tall for the row.
![screenshot_20171205_102519](https://user-images.githubusercontent.com/3708962/33609384-a3b8757e-d9a6-11e7-9f26-be01d640118f.png)

```
<div class="row">
    <label class="col-md-3">Type:</label>
    <div class="col-md-9">
        <i class="text-info material-icons" style="font-size:19px">{{client?.type | lowercase}}</i>
    </div>
</div>
<div class="row">
    <label class="col-md-3">Rut</label>
    <div class="col-md-9">{{client?.rut | rut}}</div>
</div>
<div class="row">
    <label class="col-md-3">Name</label>
    <div class="col-md-9">
        {{client?.name}}
        <span *ngIf="client && client.type==='Person'">{{client.secondName}}</span>
        {{client?.lastName}}
        <span *ngIf="client && client.type==='Person'">{{client.secondLastName}}</span>
    </div>
</div>
```

Is there a style already for this? or just put 19px style?

**Comment by niesteszeck** [comment]
Hi @chelaruc any update on this?

**Comment by chelaruc** [comment]
@niesteszeck Sorry for the late response. We don't have any class that could make the icon bigger or smaller and you have to style the icon by yourself and your example with font-size is a good choice.

Best,
Ciprian

**Comment by niesteszeck** [comment]
thx
