### ISSUE TITLE
Missing js files in assets > js > core

### ISSUE THREAD

**Issue by rashinp** [creativetimofficial/material-dashboard-pro-angular#148]
Purchased on 5th Dec, downloaded the archive couldn't find any files in assets > js > core

**Comment by chelaruc** [comment]
Hi, @rashinp! Thank you for using our product! Can you tell me what problem you encounter? In the latest versions, we've installed all plugins in node_modules and forgot to update the documentation.

Best, Ciprian

**Comment by rashinp** [comment]
Oh ok, I was comparing the files with the documentation. Actually I am using the templates for building a Meteor.js app, so I am taking only the required components from the downloaded files, and found some issues, but after I copied the material.min.js and jquery.3.2.1 min that you have on your web version demo it seems to be working. Thank you for your quick response
