### ISSUE TITLE
ESC close modal behaviour 

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#149]
Hi.

How to activate ESC close modal behaviour .

Thanks

**Comment by chelaruc** [comment]
Hi, @niesteszeck! 
Thank you for using our product! In our project, we can close the modal using ESC button. Are you sure it is not working?

All the best,
Ciprian

**Comment by niesteszeck** [comment]
yes, sure.

tested on firefox and chromium

my modal:
### .html
```
<div #clientModal class="modal fade" role="dialog"
     *ngIf="clientService.clientObservable | async as Client;">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" (click)="openFull()"><i class="material-icons">launch</i></button>
                <h4 class="modal-title"><strong>
                    {{title}}
                </strong></h4>
            </div>
            <div class="modal-body">
                <app-clients-details-cmp></app-clients-details-cmp>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
```
### .ts
```
@Component({
    selector: 'app-clients-modal-cmp',
    templateUrl: './client-details-modal.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ClientModalComponent implements OnInit, OnDestroy {
    @ViewChild('clientModal') modal: ElementRef;
    private subscription: Subscription;
    private title: string = '';
    private client: Client;

    constructor(private router: Router,
                private clientService: ClientService) {
    }

    ngOnInit(): void {
        this.subscription = this.clientService.clientObservable.subscribe(
            client => {
                this.client = client;
                this.title = (client.name ? client.name + ' ' : '')
                    + (client.secondName ? client.secondName + ' ' : '')
                    + (client.lastName ? client.lastName : '')
                    + (client.secondLastName ? ' ' + client.secondLastName : '');
            });
    }

    ngOnDestroy(): void {
        this.subscription.unsubscribe();
    }

    public show() {
        $(this.modal.nativeElement).modal('show');
    }

    public hide() {
        $(this.modal.nativeElement).modal('hide');
    }

    private openFull() {
        this.router.navigate(['./client/rut', this.client.rut]);
    }
}
```


I include it on other component html:   `<app-clients-modal-cmp></app-clients-modal-cmp>`
and show it with a function on ts: 
```
showDetails(client: Client) {
        this.clientService.setClient(client);
        this.detailsModal.show();
    }
```

**Comment by chelaruc** [comment]
@niesteszeck Can you give me an archive for testing?

**Comment by niesteszeck** [comment]
@chelaruc  I shared it over drive

**Comment by niesteszeck** [comment]
@chelaruc I found the error. I missed the `tabindex="-1"` attribute for the main modal div 
<div #clientModal class="modal fade" tabindex="-1 role="dialog"
     *ngIf="clientService.clientObservable | async as Client;">
    <div class="modal-dialog">
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" (click)="openFull()"><i class="material-icons">launch</i></button>
                <h4 class="modal-title"><strong>
                    {{title}}
                </strong></h4>
            </div>
            <div class="modal-body">
                <app-clients-details-cmp></app-clients-details-cmp>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>
