### ISSUE TITLE
Is-empty is not working correctly with [(ngModel)]

### ISSUE THREAD

**Issue by BoyeMagnus** [creativetimofficial/material-dashboard-pro-angular#15]
![image](https://cloud.githubusercontent.com/assets/24491343/26283332/c05ad472-3e26-11e7-88ae-12e9bd820a4c.png)
The error is occurring when I am using [(ngModel)] and router redirecting to the component. The error doesn't occur if I reload the page instead of router redirecting.

**Comment by alexandru-paduraru** [comment]
@BoyeMagnus thank you for pointing out. Can you please make sure you are not including the `.is-empty` class when you are sending something in the value of the input? If the class `.is-empty` is added the input will think that there is nothing there and it will move the floating label over the text.

Do you have an example with the code from the ngModel and the html?

Best,
Alex

**Comment by gassuncaocosta** [comment]
Hi. I'm having the same issue when data is loaded dynamically.

Checking chrome inspector, I can see that div class "form-group" have this "is-empty" class, when data is filled with [ngModel]:

HTML:
`<div class="form-group label-floating">
<label class="control-label" for="name">Nome:
                                    <span class="star">*</span>
                                </label>
                                <input id="name" type="text" class="form-control" name="name" [ngModel]="database.name" required #name="ngModel">
                            </div>`

![dberror](https://user-images.githubusercontent.com/24612762/30030773-3466b2aa-9165-11e7-93ae-c902a105a196.png)

Any suggestion?

**Comment by alexandru-paduraru** [comment]
@gassuncaocosta can you please add this code on ngAfterViewInit:
```
$.material.options.autofill = true;
$.material.init();
```
And let us know your status?

Best,
Alex

**Comment by gassuncaocosta** [comment]
It works like a charm! Thank you, @alexandru-paduraru !

**Comment by jac0117** [comment]
Thanks... this works great.
