### ISSUE TITLE
Wizard form color inconsistence

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#151]
Hi,

I'm not sure if this is a desire behaviour, but at least for me looks strange.

When changing the color of the wizard there are mixed colors for imputs with errors. If focused get red, if not de configured wizard-card data-color
![screenshot_20171207_170117](https://user-images.githubusercontent.com/3708962/33736111-31e7a53e-db70-11e7-9e86-d51bdda22dc7.png)

**Comment by niesteszeck** [comment]
The red color isn't bad if whe have focus on the input, but the red label when not focused, in combination with the data-color underline (purple in this case)  looks wear
![screenshot_20171214_124525](https://user-images.githubusercontent.com/3708962/34000705-ce9f4196-e0cc-11e7-8323-4e2c460f3053.png)

**Comment by niesteszeck** [comment]
if you change (inside `_mixins.scss`:`@mixin set-wizard-color($color) {`)
```
  .form-group {
    .form-control {
      background-image: linear-gradient($color, $color), linear-gradient($mdb-input-underline-color, $mdb-input-underline-color);
    }
  }
```
by this
```
  .form-group {
    .form-control {
      background-image: linear-gradient($color, $color), linear-gradient($mdb-input-underline-color, $mdb-input-underline-color);
    }
    &.has-error {
      &:not(.is-focused) {
        .control-label {
          color: $color;
        }
      }
    }
  }
```

you get 
![screenshot_20171214_130144](https://user-images.githubusercontent.com/3708962/34001481-e12bcd8c-e0ce-11e7-85da-8a8e4ff9b481.png)

That, at least for me looks more consistent

**Comment by niesteszeck** [comment]
Other option is to add this rule to `_wizard-card.scss`. This time looks even more consistence
```
  .form-group {
    &.has-error {
      &:not(.is-focused) {
        .control-label {
          @extend label.control-label;
        }
      }
    }
  }
```

![screenshot_20171214_130859](https://user-images.githubusercontent.com/3708962/34001909-06176790-e0d0-11e7-8fc1-f356f361acf0.png)

**Comment by chelaruc** [comment]
@niesteszeck Thank you for these fixes! We will do these modifications in the next update. 

Best, Ciprian.

**Comment by niesteszeck** [comment]
@chelaruc If I can vote, i like the second one (no purple on unfocused labels), I'm using it.

**Comment by chelaruc** [comment]
Hi, @niesteszeck! I've made some changes to your code. Try this:
```
.form-group {
        &.has-error {
            &:not(.is-focused) {
                .form-control {
                    background-image: linear-gradient($label-danger-bg, $label-danger-bg), linear-gradient($mdb-input-underline-color, $mdb-input-underline-color);
                }
            }
        }
        .form-control {
            background-image: linear-gradient($color, $color), linear-gradient($mdb-input-underline-color, $mdb-input-underline-color);
        }
    }
```
Tell me if is better!

Best,
Ciprian

**Comment by niesteszeck** [comment]
Hi, @chelaruc. In wich file I have to put this, `_mixins.scss` or `_wizard-card.scss`

**Comment by chelaruc** [comment]
@niesteszeck I forgot to say the file :)), in `_mixins.scss`

**Comment by niesteszeck** [comment]
@chelaruc looks great, errors all always erros

**Comment by niesteszeck** [comment]
@chelaruc Looks great. This way errors all always errors.
![screenshot_20171221_094728](https://user-images.githubusercontent.com/3708962/34256401-e549aeec-e633-11e7-9d2f-df00701c8e4d.png)

**Comment by niesteszeck** [comment]
@chelaruc your code will be included?

**Comment by chelaruc** [comment]
yes, it will be in v1.5.0

**Comment by niesteszeck** [comment]
thks, have a great day!
