### ISSUE TITLE
Angular Universal compatibilty

### ISSUE THREAD

**Issue by sherry9872** [creativetimofficial/material-dashboard-pro-angular#152]
Is the material-dashboard-pro-angular compatible with angular universal for server side rendering

**Comment by chelaruc** [comment]
Hi @sherry9872,

We didn't try angular universal yet, but if you can give me a tutorial, I'll try to integrate it for you.

Best,
Ciprian

**Comment by taketomatsunaga** [comment]
Hi,

Hi is there any way to use nguniversal at this moment?
I need to optimize my app for SEO.

Sincerely,

**Comment by chelaruc** [comment]
Hi, @taketomatsunaga. Unfortunately, we haven't used Angular Universal yet.

**Comment by taketomatsunaga** [comment]
@chelaruc Are you planning to update for universal or not? if yes, please tell me your timeline

**Comment by chelaruc** [comment]
Currently, we are working on other projects and we don't have an ETA for this feature.

**Comment by khwerhahn** [comment]
The template is unusable with Angular Universal due to window, document & navigator not being available server side. https://github.com/angular/universal/blob/master/docs/gotchas.md
