### ISSUE TITLE
Cannot run unit test

### ISSUE THREAD

**Issue by johnhigginsavila** [creativetimofficial/material-dashboard-pro-angular#153]
How can I run unit test? 
I got this error:

ERROR in /home/ubuntu/Documents/StartupFolder/OBQA/DEV/development/task1/web-ui/node_modules/@angular/core/src/testability/testability.d.ts (41,33): Cannot find name 'Node'.

**Comment by chelaruc** [comment]
Hi, @johnhigginsavila! Thank you for using our product! Can you give me more information about unit testing? It will help me to test in our project.

All the best,
Ciprian

**Comment by johnhigginsavila** [comment]
Hi Chelaru,

I just run ng test and its not working. I also what to run the test using
phantom js but still doesnt work.
I did no add anything before running the test. What configurations should I
do for unit testing?

Sincerely,
John

**Comment by chelaruc** [comment]
@johnhigginsavila
I made some tests and you need to follow this tutorial: [https://github.com/angular/angular-cli/wiki/stories-1.0-update#one-tsconfig-per-app](https://github.com/angular/angular-cli/wiki/stories-1.0-update#one-tsconfig-per-app)
Then go in `src/typings.d.ts` and replace the current code with: `declare var module: NodeModule;
`
Tell me if it worked.

**Comment by johnhigginsavila** [comment]
Thank you. I'll update you after I test it. thanks.

**Comment by johnhigginsavila** [comment]
Hi Chelaru,

I followed your instructions and still had errors. I can't even run ng
build --prod.
Do you have updates for this one? thanks

**Comment by johnhigginsavila** [comment]
attached is the error message I receieved after running ng build --prod

Thanks.

**Comment by chelaruc** [comment]
Hi @johnhigginsavila,

I didn't receive the attached error message. Can you send it again?

Best,
Ciprian

**Comment by johnhigginsavila** [comment]
Hi Chelaru,

I would like to ask, how can I extend my license for the product I bought
to you? because I will be using the product for multiple clients.
thank you.

Sincerely,
John

**Comment by chelaruc** [comment]
Hi @johnhigginsavila! Can you send me an email to ciprian@creative-tim.com with the order details?

All the best,
Ciprian

**Comment by johnhigginsavila** [comment]
Hi Chelaru,

I already sent a mail.

Regards,
John
