### ISSUE TITLE
Direct links work locally but not on CDN

### ISSUE THREAD

**Issue by rohit-gandhe** [creativetimofficial/material-dashboard-pro-angular#155]
This works and correctly lands me on the buttons page with sidebar and everything.
http://localhost:4200/components/buttons 

But when I deploy the same code ( dist dir that `ng build --prod` produced), I get a 404
http://test.hermes.ohme.li.s3-website-us-west-1.amazonaws.com/components/buttons

![image](https://user-images.githubusercontent.com/8609882/33854055-2685747a-de75-11e7-9c90-b58cdfda65a6.png)

I am sure I am missing something very basic but don't know what.

**Comment by chelaruc** [comment]
Hi, @rohit-gandhe! Thank you for using our product.  Can you go to `src/app/app.module` and replace:
```
        RouterModule.forRoot(AppRoutes),
``` 
with
````
        RouterModule.forRoot(AppRoutes, {useHash: true}),
````
Tell me if it worked.

Keep in touch,
Ciprian

**Comment by rohit-gandhe** [comment]
Thanks, @chelaruc! That works
