### ISSUE TITLE
mat-select with search filter

### ISSUE THREAD

**Issue by jariwbh** [creativetimofficial/material-dashboard-pro-angular#157]
Hi,

We are using mat-select in our applications, it sometimes has more than 50 items and we need search textbox to filter data. How do we do this with current component ? Please share code.

//Bharat

**Comment by chelaruc** [comment]
Hi @jariwbh,

See this issues opened on material/angular2 repository: [https://github.com/angular/material2/issues/2812](https://github.com/angular/material2/issues/2812) and [https://github.com/angular/material2/pull/7835](https://github.com/angular/material2/pull/7835)
We are waiting for this feature.

Best,
Ciprian

**Comment by jrood** [comment]
@jariwbh @chelaruc, I feel like I've spoken too much on the thread at https://github.com/angular/material2/pull/7835, but if you guys have particular use cases, feel free to share them there. It might help demonstrate why the item should be prioritized.

**Comment by niesteszeck** [comment]
@jariwbh I use mat autocomplete to achieve a searchable select, not the same (missing down arrow) but hopefully it'll fill your needs. On #170 there is a reference to an example.

**Comment by davewolfusa** [comment]
I'm attempting to create a number of selects that have all of the countries in the world. Most of the selects have multiple selections. It would be really nice to have categories (groupings by geographic area, EU Membership), filtering, and the ability to select all or all of a group.

Any suggestions?

**Comment by macjohnny** [comment]
FYI there exists a temporary implementation using `MatSelect`
See https://github.com/angular/material2/issues/5697#issuecomment-369358522
