### ISSUE TITLE
mat-autocomplete css overriding problem

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#159]
In my project I use some [mat-autocomplete](https://material.angular.io/components/autocomplete/overview) and If you try (also with basic example) to use it inside your theme you can't see the active option when you navigate with arrow up/down, maybe your css is not specific because you use this code: 
`.mat-option.mat-active {
    background: transparent !important;
}`

`<form>
	<mat-form-field class="example-full-width">
	<input type="text" placeholder="Pick one" aria-label="Number" matInput [matAutocomplete]="auto">
	<mat-autocomplete #auto="matAutocomplete">
	<mat-option *ngFor="let option of options" [value]="option">
				  {{ option }}
				</mat-option>
			  </mat-autocomplete>
			</mat-form-field>
		  </form>`

![cattura](https://user-images.githubusercontent.com/27501745/34100477-d10a5e0c-e3e2-11e7-9b9d-239a24b4d72c.PNG)

**Comment by chelaruc** [comment]
@lippomano Can you tell me the browser and the version so I can do some tests?

Best,
Ciprian

**Comment by lippomano** [comment]
Chrome latest
and your theme version 1.4.5

**Comment by chelaruc** [comment]
@lippomano All you have to do is to go in `src/assets/sass/material-dashboard/plugins/_select-bootstrap.scss` and delete these lines:
<img width="445" alt="screen shot 2017-12-19 at 15 44 31" src="https://user-images.githubusercontent.com/22840626/34159887-889a02d4-e4d3-11e7-994c-01890f867ff9.png">

Best,
Ciprian

**Comment by lippomano** [comment]
Good it works, Do you plan to fix it?

**Comment by chelaruc** [comment]
@lippomano it is fixed in v1.4.7.
