### ISSUE TITLE
Can't use Chartist.js Plugins

### ISSUE THREAD

**Issue by Sedor** [creativetimofficial/material-dashboard-pro-angular#16]
I'm trying to get the Zoom Plugin running but Chartist.plugin is undefined for me.

Any suggestions how to hack that or will there be a fix ?

**Comment by alexandru-paduraru** [comment]
@Sedor thank you for using our product. We updated the CLI version to 1.2.0 and we included the zoom plugin there. Please download it again and let us know if everything is fine.

Best,
Alex
