### ISSUE TITLE
ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by rohit-gandhe** [creativetimofficial/material-dashboard-pro-angular#160]
Sorry for an open ended question but I am seeing this very annoying error in the console after a change I made and I do not know what change created this issue. I have made a lot of changes and can't undo all of them. What is the best way to troubleshoot this issue?

**Comment by rohit-gandhe** [comment]
![image](https://user-images.githubusercontent.com/8609882/34361300-a9595f52-ea1d-11e7-9f4e-c45bf08270a0.png)

**Comment by niesteszeck** [comment]
is declared?

![screenshot_20171226_153417](https://user-images.githubusercontent.com/3708962/34362427-34eccfac-ea52-11e7-9e7a-66bbfe87a212.png)

**Comment by rohit-gandhe** [comment]
Yes, $ is declared.

**Comment by bommen** [comment]
What version of Bootstrap Material Design are you using? I got this error
when I upgraded to the latest version.

**Comment by rohit-gandhe** [comment]
I did not upgrade Bootstrap, but I did upgrade a bunch of Angular libs to 5.0 to comply with AngularFire and CloudFirestore.

**Comment by bommen** [comment]
Not bootstrap itself, just the material design library for bootstrap. In
newer versions (4+) the calls to initialize the framework have been
changed. I haven't figured out what the new call should be.

**Comment by rohit-gandhe** [comment]
I think I screwed up when I commented the html in dashboard html but didn't comment the ts in dashboard component. When I comment the init and afterViewInit methods in component, the error is gone. Thanks for checking guys, I am going to close this issue.

**Comment by rohit-gandhe** [comment]
Just for posterity in case, somebody is looking for this error. It happens whenever the compilation fails. I had a variable name wrong (schedules vs schedule$) and I got the dreaded $ is not defined. It  is a symptom of the compiled files (bundle.js) not loading properly.
