### ISSUE TITLE
mat-select css override problem

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#161]
I have a problem similar to [issue 159](https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/159) with mat-select.
The css for the active option is `.mat-option.mat-selected:not(.mat-option-multiple) {
    background-color: #9c27b0 !important;
    color: #FFFFFF !important;` 
And I can't override it.

Version 1.4.7 of material-dashboard-pro-angular

**Comment by drenda** [comment]
I've the same problem. Some news? Thanks

**Comment by chelaruc** [comment]
Hi, @lippomano @drenda! Can you describe me what you want to do? I don't understand it very good.

Best,
Ciprian

**Comment by lippomano** [comment]
@chelaruc  I need to change the color of the mat-select active option, but in your template 1.4.7 there is this code:
`.mat-option.mat-selected:not(.mat-option-multiple) { background-color: #9c27b0 !important; color: #FFFFFF !important;` so I can't override this css

**Comment by lippomano** [comment]
probably in `_select-bootstrap.scss` I need to remove this line:

`.mat-option.mat-selected:not(.mat-option-multiple){
    background-color: #9c27b0 !important;
    color: $white-color !important;
}`
But I'll wait your feedback @chelaruc

**Comment by chelaruc** [comment]
@lippomano have you fixed that?

**Comment by lippomano** [comment]
Yes, but like I said the only way is to remove this line from your CSS

**Comment by drenda** [comment]
@chelaruc Are you able to solve it please? Thanks

**Comment by chelaruc** [comment]
Fixed in v2.0.0
