### ISSUE TITLE
 Starting a new project

### ISSUE THREAD

**Issue by jeasomoza** [creativetimofficial/material-dashboard-pro-angular#162]
Good afternoon, I am new at angular and I want to implement a new project, I would like to know what are the most necessary files to start, that is, in the html format there is a folder called examples -> a file called dashboard.html in angular which modules are the necessary?

**Comment by chelaruc** [comment]
Hi, @jeasomoza! Thank you for your interest in our product! You can download the free version of [Material Dashboard Angular](https://www.creative-tim.com/product/material-dashboard-angular2) and take a look how to implement your application. All the best, Ciprian
