### ISSUE TITLE
Integrate to existing angular 2 project

### ISSUE THREAD

**Issue by jvvosantos** [creativetimofficial/material-dashboard-pro-angular#163]
I bought the PRO dashboard angular theme just earlier today and I'm having too much trouble integrating to my already existing angular2 project, how can I do it?

I can run the sample project just fine, but I want to apply the theme to my existing project

**Comment by elvisgn** [comment]
I think we all have gone through the same. My way was to accept the sample project, and include my components into it, and remove what I didn't need.

**Comment by chelaruc** [comment]
Hi, @jvvosantos! 

Sorry for the late response. I think @elvisgn is right. You can import our scss files in your project, but I don't know if it is the best solution because you don't have our classes. 

All the best,
Ciprian
