### ISSUE TITLE
change sidebar background color

### ISSUE THREAD

**Issue by douglas168** [creativetimofficial/material-dashboard-pro-angular#167]
Hi,

In the Material Dashboard Pro Angular, there is a setting on the right to change the sidebar background color and background imsage, how do I configure the downloaded package to have this feature?

Thanks!

**Comment by chelaruc** [comment]
Hi, @douglas168!

Can you give me your email address to send you the files with fixed plugin?

All the best,
Ciprian

**Comment by douglas168** [comment]
HI Chelaru,
Yes, my email address is douglas168@yahoo.com Thank you!
Sincerely,Douglas Kuo
Email : douglas168@yahoo.com

**Comment by douglas168** [comment]
Hi Ciprian,
Two other questions about Material dashboard Pro Angular:
1- Say I need to set the sidebar background,  how do I do it?2- Once I have the plugin, how to do configure the given colors to be more inline with brand color and customer desired background images on the sidebar? Appreciate your help!
Sincerely,Douglas Kuo
Email : douglas168@yahoo.com

**Comment by douglas168** [comment]
Hi Ciprian,
Because of customer request, I moved the Navbar's "search form"  to inside of main content (see picture below).
In the main content, this "search form" is noticeably lower than other components on the left.   How do get the "search form" line up with other components?


 Appreciate the help!
Sincerely,Douglas Kuo
Email : douglas168@yahoo.com

**Comment by chelaruc** [comment]
Hi @douglas168!

In `src/app/layouts/admin/admin-layout.component.html` you will see: 
<img width="906" alt="screen shot 2018-01-08 at 11 30 32" src="https://user-images.githubusercontent.com/22840626/34665011-63f7f0fa-f467-11e7-92cb-51b2512e73aa.png">
All you have to do is to change the colors from `data-active-color` and `data-background-color`. For image you need to change the path from `style="background-image:url(PATH_TO_IMAGE)"`

Best,
Ciprian

**Comment by nitekon1** [comment]
@chelaruc 

I would also like to get the right sidebar settings plugin and instructions to integrate it into my project.  Also went ahead and sent you my email address.

FYI I think this would be a great article to add to the Material Dashboard Pro help documentation.

Thanks!

**Comment by douglas168** [comment]
Hi Chelaru,
I changed the data-background-color to 'purple' but the sidebar background becomes white.  What did I do wrong?



 Sincerely,Douglas Kuo
Email : douglas168@yahoo.com

**Comment by chelaruc** [comment]
@douglas168 we have built only 3 colors for sidebar background(white, red and black).

**Comment by douglas168** [comment]
Hi Chelaru,
Is there anyway to change sidebar background color to other than those 3 colors? Sincerely,Douglas Kuo
Email : douglas168@yahoo.com

**Comment by chelaruc** [comment]
@douglas168 Here you have a tutorial for that: [https://github.com/creativetimofficial/material-dashboard-pro/issues/72](https://github.com/creativetimofficial/material-dashboard-pro/issues/72)
