### ISSUE TITLE
CLI version bugs

### ISSUE THREAD

**Issue by LexBel-co** [creativetimofficial/material-dashboard-pro-angular#17]
The CLI version of 'Material Dashboard Pro Angular 2' was released with Angular CLI 1.0.0-rc.0 and if we try tu update that version to the latest stable or even 1.0.0, when we run the ng serve command, we get several errors, related with 'ldb' folder:

`ERROR in /Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (66,9): Iden
tifier 'Chartist' must be imported from a module
/Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (66,9): Value of type
 'IChartistPieChart' is not callable. Did you mean to include 'new'?
/Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (69,9): Identifier 'C
hartist' must be imported from a module
/Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (69,9): Value of type
 'IChartistLineChart' is not callable. Did you mean to include 'new'?
/Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (72,9): Identifier 'C
hartist' must be imported from a module
/Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/lbd-chart/lbd-chart.component.ts (72,9): Value of type
 'IChartistBarChart' is not callable. Did you mean to include 'new'?

ERROR in /Users/LexBel/Documents/Desarrollo/Proyectos/opentecnologia.frontend/src/app/lbd/services/notification.service.ts (59,5): Cann
ot find name '$'.`

Do you plan to update the CLI version to the latest?, this is because we need to include other dependencies that at this moment doesn't work with CLI 1.0.0-rc.0

**Comment by alexandru-paduraru** [comment]
@LexBel-co thank you for pointing out and sorry for the late response. We fixed this and added CLI 1.0.0 in the V1.2.0. Please check it and let us know if everything is fine.

Best,
Alex
