### ISSUE TITLE
Missing Autocomplete example

### ISSUE THREAD

**Issue by AndreasHohnholt** [creativetimofficial/material-dashboard-pro-angular#170]
Hi,

is there an example? If not is there any plan to add an example?

I tried it for myself, based on this angular material example 
https://stackblitz.com/angular/gopkmmxqxek?file=app%2Fautocomplete-simple-example.html

but the result was not very beautiful

**Comment by chelaruc** [comment]
Hi @AndreasHohnholt! Thank you for using our product! Try this component from material: [https://material.angular.io/components/autocomplete/overview](https://material.angular.io/components/autocomplete/overview).

Best,
Ciprian
