### ISSUE TITLE
Datatables Editor theming

### ISSUE THREAD

**Issue by decisao** [creativetimofficial/material-dashboard-pro-angular#172]
Hi,

I see you use datatables.net tables on this template. They have a editor plugin sold separated. If I add this plugin, It Will theme like the table?

Elieser

**Comment by alexandru-paduraru** [comment]
@decisao thank you for using our product. Sincerely, we don't know how is the code of the editor, but if it is following the same classes as the datatables.net that means they will look the same. Please use it and let us know your feedback.

Best,
Alex
