### ISSUE TITLE
outdated html download version

### ISSUE THREAD

**Issue by israelias94** [creativetimofficial/material-dashboard-pro-angular#173]
I don't need an angular project. I only need the html template. but the html version to download is outdated. 
Currently this template is on 1.4.7 version. but html template is on 1.2.1 version. I need the full version in HTML format to download.

![image](https://user-images.githubusercontent.com/16140960/34694617-1a940408-f49e-11e7-879c-394f39ad0a7b.png)

**Comment by chelaruc** [comment]
Hey @israelias94! 

Thank you for using our product! Material Dashboard Pro HTML and Material Dashboard Pro Angular are two different products. That's why are different versions. 

All the best,
Ciprian
