### ISSUE TITLE
Adding a BreadCrumb

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#177]
Hi,
I am currently using material-dashboard-pro.

One thing that I have missed was a breadcrumb.
Implemented one from some code which works nicely for what I want if it wasn't for a minor issue:

when media query is between 992 and 1440 and sidebar exapnded container has size as if sidebar collapsed.
Could you tell me how can i FIx this behaviour?

codes
[breadcrumb_container.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1629602/breadcrumb_container.zip)

if you like it:

`
.breadcrumbs {
    font-size: 12px;
    margin: 0;
    padding: 0;
    border: 1px solid #c2c2c2;
    border-radius: 4px;
    background-color: #d5d5d5;
    box-shadow: 0 0 10px #bbb inset;

}

.breadcrumbs li {
    display: inline-block;
    background-image: linear-gradient(#08d, #06c);
    line-height: 30px;
    color: #fff;
    padding: 0 30px 0 20px;
    position: relative;
}

.breadcrumbs li:before {
    content: "";
    position: absolute;
    top: 5px;
    left: -11px;
    display: block;
    height: 21px;
    width: 21px;
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    transform: rotate(45deg);
    background-image: linear-gradient(140deg, #08d, #06c);
    z-index: 0;
    box-shadow: -1px 1px 0 rgba(0, 0, 0, 0.3);
}

.breadcrumbs li:first-child {
    border-radius: 4px 0 0 4px;
}

.breadcrumbs li:first-child:before {
    content: none;
}

.breadcrumbs li:last-child {
    padding-right: 20px;
}

.breadcrumbs li:last-child, .breadcrumbs li:last-child:before {
    background-image: linear-gradient(140deg, #f5f5f5, #f0f0f0);
    color: #333;
}

.breadcrumbs > li > a {
    color: white;
}
`
and usage:
`
        <div class="row">
            <div class="container">
                <nav class="breadcrumbs">
                    <li> <a [routerLink]="'/dashboard'">{{'routeprovider.sidebar.dashboard' | translate}}</a>
                    <li> {{'routeprovider.title.clients.root' | translate}}
                </nav>
            </div>
        </div>`
thanks

**Comment by chelaruc** [comment]
Hi @figueiredorj!

Thank you for using our product! To fix that you need to include the div with class `breadcrumbs` into a div with class `col-md-12`.

All the best,
Ciprian

**Comment by figueiredorj** [comment]
How I wished it to be so simple! :)
Not like that.. adding a div.col-md-12 doesn't change current behaviour....
I tried adding it before breadcrumb, before container, pairing with breadcrumb and with container... none results...

more ideas please.

**Comment by chelaruc** [comment]
@figueiredorj I've added:
````
<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page">Home</li>
        </ol>
      </nav>
````
on dashboard page without doing scss changes and it is working good to me. Can you send me an archive for testing on ciprian@creative-tim.com?

**Comment by figueiredorj** [comment]
Hi, sure!
for  a view:
`<div class="main-content">
    <div class="container-fluid">

        <div class="row">
            <div class="container">
                <nav class="breadcrumbs">
                    <li><a [routerLink]="'/dashboard'">{{'routeprovider.sidebar.dashboard' | translate}}</a>
                    <li> {{'routeprovider.title.catalog.root' | translate}}
                </nav>
            </div>
        </div>

        
            
                          
                          
                          
                          
                          

                
                
                
                
                
                

                
                            
                
                            
                
                            
                
                            
                
                            
                
                            
                
                            
            
        
        
            
                    
                            
                                
                            
                
            
        


    </div>
</div>`

and for css:
`
.breadcrumbs {
    font-size: 12px;
    margin: 0;
    padding: 0;
    border: 1px solid #c2c2c2;
    border-radius: 4px;
    background-color: #d5d5d5;
    box-shadow: 0 0 10px #bbb inset;

}

.breadcrumbs li {
    display: inline-block;
    background-image: linear-gradient(#08d, #06c);
    line-height: 30px;
    color: #fff;
    padding: 0 30px 0 20px;
    position: relative;
}
.breadcrumbs li.inactive{
    background-image: linear-gradient(#08d, #d5d5d5,#06c);
}

.breadcrumbs li:before {
    content: "";
    position: absolute;
    top: 5px;
    left: -11px;
    display: block;
    height: 21px;
    width: 21px;
    -webkit-transform: rotate(45deg);
    -moz-transform: rotate(45deg);
    transform: rotate(45deg);
    background-image: linear-gradient(140deg, #08d, #06c);
    z-index: 0;
    box-shadow: -1px 1px 0 rgba(0, 0, 0, 0.3);
}

.breadcrumbs li:first-child {
    border-radius: 4px 0 0 4px;
}

.breadcrumbs li:first-child:before {
    content: none;
}

.breadcrumbs li:last-child {
    padding-right: 20px;
}

.breadcrumbs li:last-child, .breadcrumbs li:last-child:before {
    background-image: linear-gradient(140deg, #f5f5f5, #f0f0f0);
    color: #333;
}

.breadcrumbs > li > a {
    color: white;
}
`

put view on a page (perhaps changing translate instructions to literal strings not a bad idea :)) and use breadcrumb css.

Look into media query from 992 to +-1440 and you will see either a sccroll on bottom and breadcrumb is truncated by margin...

**Comment by chelaruc** [comment]
@figueiredorj you have a div with class `container-fluid` and inside is one div with class `container`. Can you delete the second div?

**Comment by figueiredorj** [comment]
It works as you say apparently...
purpose of container was to limit width that breadcrumb could be... but
apparently container has some side-effects...
do you have any idea why? and how to emulate container?

thanks

Figueiredo, Ricardo José Andrade
Email: figueiredorj@gmail.com

**Comment by chelaruc** [comment]
@figueiredorj I think there are some defaults rules on how to use the bootstrap classes and that's why we can not use a container inside a container.

Best,
Ciprian
