### ISSUE TITLE
Bug (?) on width when sidebar not collapsed

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#178]
Hi guys,

There is an issue related to media queries I think which on my previous request about breadcrumb somehow I already trasnposed here.

but now is kind more of a not acceptable behaviour...
I mean.. I have a gridcontrol (devextreme) on a row inside container-fluid;
when sidebar is collapsed all seems to be ok.. however if sidebar expanded I may have a scroolbar for data inside gridcontrol.. but there is one sidebar also for active pane.
Also.. when expanded, if I go collapsed pane scrollbar is still there until I scroll first time.
[behavior_scrollbar.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1629700/behavior_scrollbar.zip)

let me see if I can demonstrate on a video.

**Comment by chelaruc** [comment]
I've responded to #177.
