### ISSUE TITLE
Datatables.net "table-striped table-no-bordered table-hover" classes?

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#179]
Hi,

On dattable.component example (line 17+-), I can't find the definition for classes "table-striped table-no-bordered table-hover", what are they for? are they needed?

Best regards,
continue with the great work

**Comment by alexandru-paduraru** [comment]
@niesteszeck please check the classes descriptions here: https://getbootstrap.com/docs/3.3/css/#tables

Best,
Alex

**Comment by niesteszeck** [comment]
thx
