### ISSUE TITLE
CLI version bugs

### ISSUE THREAD

**Issue by flamasweb** [creativetimofficial/material-dashboard-pro-angular#18]
When we try to generate --dist version of 'Material Dashboard Pro Angular 2' we get this error:

ERROR in Type LbdTableComponent in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd-table/lbd-table.component.ts is part of the declarations of 2 modules: LbdModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd.module.ts and DashboardModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/dashboard/dashboard.module.ts! Please consider moving LbdTableComponent in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd-table/lbd-table.component.ts to a higher module that imports LbdModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd.module.ts and DashboardModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/dashboard/dashboard.module.ts. You can also create a new NgModule that exports and includes LbdTableComponent in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd-table/lbd-table.component.ts then import that NgModule in LbdModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/lbd/lbd.module.ts and DashboardModule in /Applications/MAMP/htdocs/ddh/admin/angular-cli/src/app/dashboard/dashboard.module.ts.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Applications/MAMP/htdocs/ddh/admin/angular-cli/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Also, we noticed that side nav animation does not work properly as the "ng2" folder project.

**Comment by alexandru-paduraru** [comment]
@flamasweb thank you for pointing out. We just updated it to v1.2.0 and added the CLI 1.0.0. We also fixed the side nav animation. Please check it and let us know if everything is fine.

Best,
Alex
