### ISSUE TITLE
AngularJS 1.8

### ISSUE THREAD

**Issue by RamakrishnaPawar** [creativetimofficial/material-dashboard-pro-angular#181]
Could please let me know whether this UI will work for AngularJS 1.8? if yes then please let me know the configurations.

advance thanks

**Comment by chelaruc** [comment]
Hi, @RamakrishnaPawar! Thank you for your interest in our product. Unfortunately, we are not working with AngularJS. 

All the best,
Ciprian

**Comment by RamakrishnaPawar** [comment]
Thank you for your quick response..
