### ISSUE TITLE
Select data-live-search="true"

### ISSUE THREAD

**Issue by BobaFett58** [creativetimofficial/material-dashboard-pro-angular#182]
Hello, Tim!
How can I use your 'select' with the data-live-search?

for ex.

```
> <select class="selectpicker" data-live-search="true">
>   <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
>   <option data-tokens="mustard">Burger, Shake and a Smile</option>
>   <option data-tokens="frosting">Sugar, Spice and all things nice</option>
> </select>

```

**Comment by chelaruc** [comment]
@BobaFett58 Have you find a solution?

**Comment by BobaFett58** [comment]
@chelaruc Nope :C

**Comment by chelaruc** [comment]
@BobaFett58 You can use that selectpicker: [https://www.npmjs.com/package/angular2-multiselect-dropdown](https://www.npmjs.com/package/angular2-multiselect-dropdown)

**Comment by BobaFett58** [comment]
@cristijora Thank you! This is what I looked for.
