### ISSUE TITLE
Sidebar prefix possible to apply a icon?

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#185]
Hi,
I would like to know if in sidebar prefix is it possible to replace thsi prefix with an icon without using js...
kind of being possible to set HTML for field...

**Comment by chelaruc** [comment]
Hi @figueiredorj 

Thank you for using our product! Yes, you can change the span of the sidebar prefix with an icon, but you need to update `ROUTES` from `sidebar.component.ts` and the `ChildrenItems` interface to do that.
If you need help, tell me.

All the best,
Ciprian
