### ISSUE TITLE
Sidebar second level label height issue when minimized

### ISSUE THREAD

**Issue by PonayMort** [creativetimofficial/material-dashboard-pro-angular#187]
# There is a problem with sidebar second level label since 1.5.0 template version.
You can see a height augmentation of label when sidebar is minimized.
### Steps:
- Click on a sidebar first level label with some second level label for expand it
- Click on minimize sidebar button in navbar

Browser: Google Chrome 63
OS : Windows 7

![image](https://user-images.githubusercontent.com/1438980/35212856-d9ec5284-ff5b-11e7-9e82-7033fcc130ae.png)

**Comment by alexandru-paduraru** [comment]
@PonayMort thank you for letting us know. This seems to be an issue related to the Design of the product not to the Angular, so we will fix it as soon as we fix it in the plain HTML version. Keep in touch!

**Comment by chelaruc** [comment]
Fixed in v2.0.0
