### ISSUE TITLE
Datetimepicker

### ISSUE THREAD

**Issue by malte2408** [creativetimofficial/material-dashboard-pro-angular#189]
Hi,
thank you for the great Template :)
I'm wondering how I can use the datetimepicker / timepicker that is used in the HTML-version in the Angular2-Version. Extended forms are using mat-datepicker in the Angular2 version but I think the one from the html fits much better.

**Comment by chelaruc** [comment]
Hi, @malte2408! Thank you for using our product. We changed the datepicker from HTML because there was a lot of problems with it. 

All the best,
Ciprian

**Comment by PavelValentov** [comment]
Hello!
Continue the question. How do I pick the time in 1.5 version?

**Comment by chelaruc** [comment]
@PavelValentov You need to download it again.
