### ISSUE TITLE
Problems with components behavior

### ISSUE THREAD

**Issue by ezehurt** [creativetimofficial/material-dashboard-pro-angular#190]
Hi, I'm trying to integrate this template with jhipster @4.6.0. The styles are ok, but no component has behavior. For example, if I use a dropdown the click doesn't work. Any suggest?

**Comment by sparvov** [comment]
Hi, I have the similar behavior. 
$.material is undefined in line $.material.init();.
I tried to figure out this problem and temporary solved it with the following hack:

I've added 
`var $material = $.material `
in the end of .../node_modules/bootstrap-material-design/dist/js/material.js
and in my code changed 
`$.material.init(); `
to 
`$material.init();`

So, guys from Creative Tim can easily solve this issue just like I've done.
In this way, if someone has a problem with $.material.init(); , he will be able to use the alternative approach $material.init();

**Comment by getmowize** [comment]
@sparvov Can you share the material.js file. I tried to put in my bootstrap-material-design.js but still not able to get results. My dropdown are still not working. And even can you share the component.ts file where you have added this $material.init(); piece of code.

**Comment by rachnakhokhar** [comment]
@sparvov Can you share the material.js file. I tried to put in my bootstrap-material-design.js but still not able to get results. My dropdown are still not working. And even can you share the component.ts file where you have added this $material.init(); piece of code. 

I am using "bootstrap-material-design": "^4.1.1"

**Comment by sparvov** [comment]
Unfortunately, I played with free themes, which use  `"bootstrap-material-design": "0.5.10"`, so I cannot help you, sorry (

But if you want to run bootstrap-material-design from component.ts, you can do it like this:
```
ngAfterViewInit() {
        $('body').bootstrapMaterialDesign();
    }
```
