### ISSUE TITLE
...requires a peer of @angular/...@~5.1.1 but none is installed.

### ISSUE THREAD

**Issue by pierrebenazzibr** [creativetimofficial/material-dashboard-pro-angular#191]
Im trying to run the project and keep getting this errors, just after execute npm install.

![error_angular](https://user-images.githubusercontent.com/36460455/36178964-c5a8fd24-1101-11e8-9d40-bebacb5e1608.png)

**Comment by pierrebenazzibr** [comment]
When i change the angular version from 5.2.0 to 5.1.1 i could run the project.
Was it the right thing to do?
Why the template was released with some configurations that didnt worked in the first time? Or i was missing sth...

![error_angular](https://user-images.githubusercontent.com/36460455/36182159-653797a8-110f-11e8-9cdb-d8469b11346c.png)

**Comment by acib708** [comment]
I'm having the exact same problem. Besides, they are using deprecated libraries. This is a paid product, it should be properly maintained and tested. I bought it to save time, and this is clearly the opposite of saving time.

**Comment by alexandru-paduraru** [comment]
@pierrebenazzibr @acib708 we are working on the Angular 6 release and it will come next week. Sorry for the issues, we tested a lot on our side and the dependencies were working fine. We are doing updates every 2-3 weeks, and if there are releases from other libraries in between it's possible to have errors.

**Comment by acib708** [comment]
Thanks for the prompt response.
The solution stated above is not working for me, though. 

I still get
`npm WARN ng2-nouislider@1.6.1 requires a peer of @angular/common@^2.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-nouislider@1.6.1 requires a peer of @angular/core@^2.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/compiler-cli@5.2.0 requires a peer of @angular/compiler@5.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.0.0 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@2.0.0 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular-devkit/schematics@0.0.52 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN @schematics/angular@0.1.17 requires a peer of @angular-devkit/core@0.0.29 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

added 1436 packages in 20.48s`

**Comment by raskolnikov1041** [comment]
Hi there.  I have just downloaded my copy of the pro package, ran npm install (with a lot of warnings) and ran 'ng serve'.  

I got this message too

Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

I have not modified any other files.  Frustrating because I was able to effortlessly ran the free version and when I finally decided to get the paid version, I am faced with a lot of issues.

**Comment by raskolnikov1041** [comment]
For anyone facing a similar issue, there is another post which advises to change some things in the depedencies and dev dependencies.  You will still face some warnings in npm install but at least 'ng serve' will work. :-1:  lol

https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/184

**Comment by decision-ca** [comment]
Hello @alexandru-paduraru @chelaruc. We purchased the developer license of the product yesterday and we are experimenting issues when we use the 'npm install' (a lot of warnings). There is another version of the product working properly? Or what can we do?.

Any official solutions?

**Comment by alexandru-paduraru** [comment]
@decision-ca thank you for using our product and sorry for the issues that you have. Can you please give us more details? Isn't it working at all? Or it is installing and you just get the warnings? Also, the OS that you want to use would help.

Best,
Alex

**Comment by decision-ca** [comment]
@alexandru-paduraru Thank you for your response. The main issue are the warnings, but with the temporal solution described in #184, I was able to solve the problem.

The OS that we are using is elementary OS 0.4

**Comment by alexandru-paduraru** [comment]
@decision-ca awesome man! We will add those in the release too. 

Please let us know if we can help with anything else.

Best,
Alex

**Comment by danellis** [comment]
> we are working on the Angular 6 release and it will come next week. 

It's been over a month now, so where do I get the Angular 6 version? The version I just bought has the same problems as described here. $60 for something that fails right out of the gate.

**Comment by alexandru-paduraru** [comment]
@danellis the product was updated a couple of hours ago, please download it and let us know your status. Did you open any other request about your problem with the product not working? 

Best,
Alex

**Comment by chelaruc** [comment]
Fixed in v2.0.0
