### ISSUE TITLE
mat-select not highlighting selected item on keypress

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#193]
I am using the code from the "Forms Extended" demo for testing on a new form.

I have copied the following code only a blank component:

`            <mat-form-field>`
`                <mat-select placeholder="Single City" name="city">`
`                    <mat-option *ngFor="let item of ['One', 'Two', 'Three']" [value]="item">`
`                        {{ item }}`
`                    </mat-option>`
`                </mat-select>`
`            </mat-form-field>`

But when I run the code, the items in the popup are only highlighted when I use the mouse. If I use the up and down arrows, no highlighting is shown - although the item is still selected, because if I push Enter, the value is shown in the input.

This happens with both mat-select and mat-autocomplete.

**Comment by chelaruc** [comment]
Hi, @mcurrycl! Can you give me some images?

**Comment by chelaruc** [comment]
@mcurrycl If you want to be like when you hover it, you need to add this line in scss:
```
.mat-option.mat-active {
     -webkit-box-shadow: 0 4px 20px 0px rgba(0, 0, 0, 0.14), 0 7px 10px -5px rgba(156, 39, 176, 0.4);
    box-shadow: 0 4px 20px 0px rgba(0, 0, 0, 0.14), 0 7px 10px -5px rgba(156, 39, 176, 0.4);
    background: #9c27b0 !important;
    color: #FFFFFF !important;
}
```
