### ISSUE TITLE
Navigation Pills or Pagination on Wizard breaks Tabs

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#194]
Exactly as in this ticket:
https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/29#issuecomment-313389496

The same issue occurs if you put nav-pills or pagination on a wizard form. Unfortunately putting  a timer around the select method doesn't fix it this time.

**Comment by mcurrycl** [comment]
As an example, just add this somewhere in the WizardComponent in the demo app:

    <ul class="pagination pagination-primary">
          <li class="active">
                <a href="SetGender('M')">Male</a>
           </li>
           <li>
                  <a href="SetGender('F')">Female</a>
            </li>
            <li>
                   <a href="SetGender('U')">Unknown</a>
              </li>
       </ul>

**Comment by chelaruc** [comment]
@mcurrycl I've done some tests and this is working for us. Can you give me more informations about this error?
