### ISSUE TITLE
Alignment of <mat-form-field>

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#195]
If I use a mat-select inline with other inputs, or with a preceding icon, the alignment of the text and bottom line is off between the <mat-select> and the other inputs. The <mat-select> is higher than the other controls.
The same thing happens with checkboxes.

**Comment by chelaruc** [comment]
@mcurrycl can you give me an example for testing?

**Comment by mcurrycl** [comment]
Add this to a blank form:

    <div class="card-content">
            <div class="row">
                <div class="col-md-6">
                        <div class="form-group label-floating">
                                <label class="control-label">Email address</label>
                                <input type="email" class="form-control">
                            </div>
                </div>
                <div class="col-md-6">
                    <mat-form-field>
                        <mat-select placeholder="Single City" name="city">
                            <mat-option *ngFor="let city of ['Sydney', 'Melbourne', 'Brisbane', 'Perth']" [value]="city">
                            {{ city}}
                            </mat-option>
                        </mat-select>
                    </mat-form-field>
                </div>
            </div>
        </div>

Result is:
![image](https://user-images.githubusercontent.com/8777232/36421578-bc6a617a-1684-11e8-92e5-12ce31931425.png)

**Comment by mcurrycl** [comment]
Same thing happens with CheckBoxes:
 <div class="row">
                    <div class="col-md-6">
                        <div class="form-group label-floating">
                            <label class="control-label">Email address</label>
                            <input type="email" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="optionsCheckboxes"> Checkbox
                            </label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="checkbox checkbox-inline">
                            <label>
                                <input type="checkbox" name="optionsCheckboxes"> Inline Checkbox
                            </label>
                        </div>
                    </div>
                </div>

![image](https://user-images.githubusercontent.com/8777232/36421778-8771f9aa-1685-11e8-9149-6f3abed6c407.png)

By the way, is there any way to darken the checkbox and radio text? You can see in that image it is even lighter than the placeholder text in the Input

**Comment by chelaruc** [comment]
@mcurrycl If you want to make the checkbox and radio text more darken, you need to go in `src/assets/sass/material-dashboard/_checkboxes.scss` file and remove line 5. And to align mat-from-field with other inputs, add to .mat-form-filed top: 12px.
Tell me if you need something else.

**Comment by igoratf** [comment]
@chelaruc adding .mat-form-filed top: 12px. did not work for me. It still looks the same as @mcurrycl showed. Any other idea?
