### ISSUE TITLE
Dropdown not opening integrating with jhipster

### ISSUE THREAD

**Issue by rachnakhokhar** [creativetimofficial/material-dashboard-pro-angular#196]
When I tried integrating Bootstrap-Material-Design the dropdown component or floating label component all were working fine. And when I tried to integrate this theme which I have recently purchased assuming it will give nice look and feel to my dashboard the theme got integrated but the components like dropdown and all are not working.

I am even getting error $.material is undefined in line $.material.init();

I am including all required javascript and css/scss files required for bootstrap, bootstrap-material-design and your material-dashboard.scss but only theme files are working not the components actions.

I am using Bootstrap 4, Bootstrap Material Design 4 and Angular 5. Please help me with this issue, I purchased your theme just for this.

**Comment by chelaruc** [comment]
Hi, @rachnakhokhar! Thank you for using our product. Can you send me an email with an archive for testing at ciprian@creative-tim.com?
