### ISSUE TITLE
How to use MatProgressSpinner ?

### ISSUE THREAD

**Issue by Souffiane** [creativetimofficial/material-dashboard-pro-angular#197]
Hi,

I'm beginner in Angular and would like use Spinner.
I saw MatProgressSpinner in the app.module.ts but there is no example in the app.

Can someone provide one please?

Thanks.

**Comment by timcreative** [comment]
Hi, @Souffiane 

Thank you for using our product! Here is the documentation for Material Spinner: [https://material.angular.io/components/progress-spinner/overview](https://material.angular.io/components/progress-spinner/overview)

All the best, 
Ciprian

**Comment by chelaruc** [comment]
Hi, @Souffiane 

Thank you for using our product! Here is the documentation for Material Spinner: [https://material.angular.io/components/progress-spinner/overview](https://material.angular.io/components/progress-spinner/overview)

All the best, 
Ciprian
