### ISSUE TITLE
Install Css & Components

### ISSUE THREAD

**Issue by MJules** [creativetimofficial/material-dashboard-pro-angular#198]
Hello

I would like to know how to install the theme (css files and components)
There are not enough instructions for import, I don't want to clone the project.

I don't understand the following error / code : 
ERROR ReferenceError: $ is not defined

component.ts
declare const $: any;    
ngOnInit() {
        $.material.init();
}

![image](https://user-images.githubusercontent.com/16535677/36785414-fa84a30e-1c82-11e8-91c1-56590a0ec326.png)

ps : I really need to have a list of files with the lines to edit / add

Thank you
@alexandru-paduraru  @timshingyu  @sonoftheweb  @aluciu  @shakhrillo

**Comment by chelaruc** [comment]
Hi, @MJules! Did you follow the steps from documentation? [http://md-pro-angular.creative-tim.com/documentation/tutorial](http://md-pro-angular.creative-tim.com/documentation/tutorial)

**Comment by MJules** [comment]
Hi,
Yes but when i use component I've got this error :
ERROR ReferenceError: $ is not defined

**Comment by chelaruc** [comment]
@MJules CAn you give me more informations? LIke the file where you get this error and the steps to reproduce?

**Comment by MJules** [comment]
Hello
I tried again to install the theme and it worked ..

For information:
ng e2e fail: Upgrading ts-node to ~ 3.3.0
add "@ types / jasminewd2": "~ 2.0.2",

I don't undertsand how work in app.component.ts : 
declare var $: any; 
and     
$.material.init();

You can tell me how it works please ?

Thx

**Comment by chelaruc** [comment]
@MJules Can you send me an archive for testing to ciprian@creative-tim.com?
