### ISSUE TITLE
Scrollbar not working on Firefox/Chrome on Mac

### ISSUE THREAD

**Issue by drenda** [creativetimofficial/material-dashboard-pro-angular#200]
I'm experiencing troubles with scrollbars on Firefox/Chrome on Mac. On Windows everything works but on Mac works only the sidebard scroll but the content on the right is without scrollbar and I'm not able to scroll down.

I saw that in your application it works but not in mine. Do you know what could be wrong with that? And why it works on Windows and not on Mac? Sounds weird.

<img width="1279" alt="schermata 2018-03-03 alle 10 25 14" src="https://user-images.githubusercontent.com/3420646/36932691-3ea0e0e2-1ecd-11e8-81a3-e01becadd787.png">

**Comment by chelaruc** [comment]
@drenda have you got errors in the console?

**Comment by drenda** [comment]
@chelaruc no errors

**Comment by chelaruc** [comment]
@drenda Can you send me an archive to ciprian@creative-tim.com for testing?

**Comment by drenda** [comment]
@chelaruc Having a link to the application live could be enough?

**Comment by drenda** [comment]
@chelaruc I think I found the problem. In admin-layout.component.ts you have this code:

` if (window.matchMedia(`(min-width: 960px)`).matches && !this.isMac()){
            let ps = new PerfectScrollbar(elemMainPanel);
            ps = new PerfectScrollbar(elemSidebar);
        }`

Removing the check on isMac() the scrollbar works. You didn't initialize that on Mac. Why? Thanks

**Comment by drenda** [comment]
@chelaruc You should fix this problem because without the initialization of the perfect scrollbar I've not scrollbar at all in the application. Please change your code in order to fix this problem

**Comment by chelaruc** [comment]
@drenda I'll fix that in next update. I'll reopen this issue till then.

**Comment by drenda** [comment]
@chelaruc When do you plan to come out with the next relase? Thanks

**Comment by chelaruc** [comment]
@drenda Today or Monday.

**Comment by chelaruc** [comment]
Fixed in v2.0.0

**Comment by Divya10101305** [comment]
Am using angular template, scrollbar is not scrolling in windows ..is that i need to add css property to do scrolling up and down
