### ISSUE TITLE
Select inside Table

### ISSUE THREAD

**Issue by elvis-gbmme** [creativetimofficial/material-dashboard-pro-angular#202]
Hi, trying to put a select tag inside a table row.

mat-select is not working, gives a runtime error. Normal select tag looks very basic.

only using the form-control class makes it look elegant..but still not positioned well inside the column.

**Comment by chelaruc** [comment]
@elvis-gbmme Can you give me an archive for testing to ciprian@creative-tim.com or the steps to reproduce the error? 

Best,
Ciprian

**Comment by elvis-gbmme** [comment]
Just paste the following <td> item into any table...
```
<td>
	<select class="form-control" ngModel="{{ user.regn_status }}">
		<option value="invited">Invited</option>
		<option value="requested">Requested</option>
		<option value="registered">Registered</option>
		<option value="rejected">Rejected</option>
		<option value="cancelled">Cancelled</option>
	</select>
</td>
```

The alignment looks off, and if I remove form-control, they it looks like an ordinary html select box.

**Comment by chelaruc** [comment]
@elvis-gbmme we are not using that select anymore. We are using the mate-select:
```
<mat-select multiple placeholder="Multiple Cities" [(ngModel)]="currentCity" name="Paris" ariaLabel="cities[0]">
       <mat-option *ngFor="let city of cities" [value]="city.value">
               {{ city.viewValue }}
       </mat-option>
</mat-select>
```

**Comment by elvisgn** [comment]
It worked !! Thanks.
