### ISSUE TITLE
Wizard Validation

### ISSUE THREAD

**Issue by rintuseqato** [creativetimofficial/material-dashboard-pro-angular#205]
Hi,
I'm using the wizard for a 3-step registration process. I want to do validation on the second step of the wizard. 
Also, I don't want the navigation through the tabs before the 'Next' button is clicked in the first 2 steps.

**Comment by chelaruc** [comment]
@rintuseqato can you give me more informations? What validation do you want to do on the second tab?

**Comment by rintuseqato** [comment]
@chelaruc, I do not want the user to proceed with an empty field in the second step.

**Comment by chelaruc** [comment]
@rintuseqato, can you tell me what code do you use in the second step?

**Comment by rintuseqato** [comment]
Sorry, @chelaruc  I was a bit busy in the past days. I have mailed you the code of the component.ts and the HTML page.Please check that.

**Comment by aleximmauell** [comment]
Actually the code was designed from your end was like ,on the last tab the button will show "Finish", will show "Next" on previous tabs.based on the hide and show,
 onTabShow :   
 if ($current >= $total) {
                    $($wizard).find('.btn-next').hide();
                    $($wizard).find('.btn-finish').show();
}
my validations was on the jquery validate () funtion
const $validator = $('.wizard-card form').validate({
            rules: {            
               Name: {
                       required: true,
                       minlength: 4,
                   }
             Policy: {
                     required: true,
                      minlength: 10,        
                 }

Here , Id = Name  was on the first tab ,Id = Policy was on the last tab,
now ,from the first tab if i click next button i get error if the name was typed only " 3 " characters coz min length was set by me as " 4 " and next button will not work until i type 4 characters , similarly on the last tab i have id = Policy and the button name was " finish "the validation  for Policy is not working.  i need to validate the fields of the last tab also before submit .

**Comment by chelaruc** [comment]
@rintuseqato Check what @aleximmauell said in the previous comment. It should work.
