### ISSUE TITLE
Scrollbar doesn't work on mobile devices

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#218]
If I try to use my project on a mobile phone I can't see any scrollbar, probably because you don't initialize the scrollbar correctly.
Indeed If I comment this control in admin-layout.component.ts:
![scroll](https://user-images.githubusercontent.com/27501745/38139435-b0b653b6-342f-11e8-87cf-4ec109a505cd.PNG)

And

![scroll2](https://user-images.githubusercontent.com/27501745/38139458-ca004b10-342f-11e8-9e91-d205365507e7.PNG)

So I don't understand why you do this.
Related to:  https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/200

**Comment by chelaruc** [comment]
@lippomano you can delete these lines if you want scrollbar on mobile phones.
