### ISSUE TITLE
navbar toggle issues

### ISSUE THREAD

**Issue by Kalki5** [creativetimofficial/material-dashboard-pro-angular#219]
mat-raised-button should be removed for navbar toggle
![image](https://user-images.githubusercontent.com/20438413/38142170-01067e58-3459-11e8-93a3-e167d167163a.png)

button is not responsive at 320px
![image](https://user-images.githubusercontent.com/20438413/38142227-2ee68156-3459-11e8-98a2-631c72d58c5a.png)

**Comment by chelaruc** [comment]
Hi, @Kalki5 

You need to change the  `mat-raised-button ` with ` mat-button ` 

All the best,
Ciprian
