### ISSUE TITLE
Form labels not aligned at certain breakpoints

### ISSUE THREAD

**Issue by paninics** [creativetimofficial/material-dashboard-pro-angular#220]
Screenshot shows it all.

![labels](https://user-images.githubusercontent.com/23061690/38150700-19740f1c-3415-11e8-8060-fb832986abe7.PNG)

**Comment by alexandru-paduraru** [comment]
@paninics thank you for pointing out and sorry for the late response, we had Easter in our team. Can you please let us know which OS you are using and what is the browser version? Then we will test and my colleague Ciprian will give a quick fix.

Best,
Alex

**Comment by paninics** [comment]
OS: Windows Server 2008 R2 (You probably can reproduce on Win 7 / Win 10)
Browser: Chrome Version 65.0.3325.181 (64-bit)

**Comment by chelaruc** [comment]
fixed in v2.0.1
