### ISSUE TITLE
oauth

### ISSUE THREAD

**Issue by yasser-kfupm** [creativetimofficial/material-dashboard-pro-angular#221]
I have Spring oauth2 server, how to implement authentication on the angular code.

I didn't find any code template to do any authentication ! 

Thanks

**Comment by chelaruc** [comment]
Hi, @yasser-kfupm! We have a small tutorial for Authentication Guard here: [http://md-pro-angular.creative-tim.com/documentation/authentication](http://md-pro-angular.creative-tim.com/documentation/authentication)

Best,
Ciprian
