### ISSUE TITLE
datatables.net - incomplete data view in responsive mode

### ISSUE THREAD

**Issue by paninics** [creativetimofficial/material-dashboard-pro-angular#222]
See the below image. The table has lot more data to the right but there is no scroll bar to permit viewing. This behavior is not exhibited in the other two tables i.e. regular and extended.

![datatables](https://user-images.githubusercontent.com/23061690/38218030-4e8a7eda-3685-11e8-8967-57e3e9ba0f17.PNG)

**Comment by chelaruc** [comment]
Hi, @paninics 

You need to click on the rows because datatables is responsive.

All the best,
Ciprian

**Comment by paninics** [comment]
I see what you're saying. But the regular and extended tables show a different behavior in responsive mode i.e. they show scroll bars and not the '+' icons. Definitely there needs to be consistent behavior across all tables. So it appears to me a bug on one or the other based on different behaviors. Please let us know your thinking and the plan of action.
