### ISSUE TITLE
Error scroll admin layout

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#225]
I am migratin to v.2 and I see an error in your theme when you navigate from register to login page:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot set property 'scrollTop' of null
TypeError: Cannot set property 'scrollTop' of null
    at SafeSubscriber._next (admin-layout.component.ts:61)
```

![err](https://user-images.githubusercontent.com/27501745/38356541-4c728ef2-38c0-11e8-9be5-1c7880dd59df.PNG)

**Comment by drenda** [comment]
Any update about this issue?

**Comment by chelaruc** [comment]
@lippomano @drenda thank you for point this to me. This error appears only on live preview, I'll take a look these days and I'll fix it.

Best,
Ciprian

**Comment by drenda** [comment]
Hi, did you solve the problem? We need a fix for this. Thanks

**Comment by chelaruc** [comment]
@drenda this error appears on the local project?

**Comment by drenda** [comment]
@chelaruc Yes both in local and in production. We used a temporary workaround using  window.scrollTo(0, 0);

**Comment by chelaruc** [comment]
@drenda I don't get the error in my local project, but your workaround is a good one
