### ISSUE TITLE
make a link to edit profile pict

### ISSUE THREAD

**Issue by bfheythem** [creativetimofficial/material-dashboard-pro-angular#227]
Hi , 
I want to make a link to the Edit profile page when I click on Edit Profile 
![image](https://user-images.githubusercontent.com/22716581/38420071-85868dda-399a-11e8-97c6-6156984a4b8e.png)

=> 
![image](https://user-images.githubusercontent.com/22716581/38420100-9bdc82a6-399a-11e8-8b0a-8d2c80a6ac01.png)

I know how to integrate an entry in the sidebar , but this one is kind of different 
can you please help me 
thanks

**Comment by chelaruc** [comment]
Hi, @bfheythem 

Replace the code for edit profile with:
````
<li class="nav-item">
                <a [routerLink]="['/pages/user']" class="nav-link">
                     <span class="sidebar-mini">EP</span>
                     <span class="sidebar-normal">Edit Profile</span>
               </a>
</li>
````

All the best,
Ciprian
