### ISSUE TITLE
pie chart is not displayed correctly when taking many series 

### ISSUE THREAD

**Issue by AndreasHohnholt** [creativetimofficial/material-dashboard-pro-angular#229]
if you insert more than 4 series then each additional series is also shown in black. 

Example:

```javascript
    const dataPreferences = {
        series: [100.5, 100, 100,100,100,100,100,100,100,100,100,100,100,100,100,100]
      };    
      var sum = function(a, b) { return a + b };    
      var piw = new Chartist.Pie('#chartPreferences', dataPreferences,
        {
          labelInterpolationFnc: function(value) {
            return Math.round(value / dataPreferences.series.reduce(sum) * 100) + '%';
        }});
```
![image](https://user-images.githubusercontent.com/17142022/38453707-61efbd40-3a5a-11e8-88c9-bc33cf4ef7ca.png)

And how it looks on the chartist-js site:

![image](https://user-images.githubusercontent.com/17142022/38453730-b7f19538-3a5a-11e8-990e-70f201852dcb.png)

**Comment by chelaruc** [comment]
Hi, @AndreasHohnholt 

Thank you for using our product. All you have to do is to go in `src/assets/scss/material-dashboard.scss` and replace the line 78 ` @import "plugins/chartist";` with ` @import "~chartist/dist/scss/chartist.scss";` 
Tell me if it works.

All the best,
Ciprian

**Comment by AndreasHohnholt** [comment]
yes now everything is displayed correctly :) (except the demo diagram (colors no longer match the legend))

**Comment by chelaruc** [comment]
@AndreasHohnholt you can make your own style in `src/assets/scss/core/_type.scss` at the end of the file and match with the colors from pie chart.
