### ISSUE TITLE
page subCategories nav pills on windows resize

### ISSUE THREAD

**Issue by cerokool32** [creativetimofficial/material-dashboard-pro-angular#23]
i'm having troubles with the max title size on the page subcategories nav pills, is there a way to fix positions like col-xs or something? 
Demo module attached
![problemasubpages](https://user-images.githubusercontent.com/3944935/27157758-e50c36f2-5128-11e7-8b7a-8ec50642c8cb.png)
[level3.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1076123/level3.zip)

**Comment by alexandru-paduraru** [comment]
@cerokool32 can you please send us the link to your web app so we can check and give you a fix? Or can you send the complete archive?

Best,
Alex

**Comment by cerokool32** [comment]
this is my full module. page still offline

[level3.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1088478/level3.zip)

**Comment by chelaruc** [comment]
Hi @cerokool32,

Sorry for the late response. We added your files in our dashboard and this is what we get:
<img width="395" alt="screen shot 2017-07-31 at 16 18 22" src="https://user-images.githubusercontent.com/22840626/28779488-ff51e52c-760b-11e7-8b2d-2c1c605076e9.png">
Can you, please, send us the right files?

Best,
Ciprian
