### ISSUE TITLE
Official Bootstrap Core usage

### ISSUE THREAD

**Issue by YZahringer** [creativetimofficial/material-dashboard-pro-angular#232]
Hello,

I would like to use your Theme with the official Bootstrap Core. If I understand correctly, your Theme contains a modified version of Bootstrap. I can not importe the officiel Bootstrap version and apply your Theme?

Following the good practices by Bootstrap [https://getbootstrap.com/docs/4.0/getting-started/theming/](https://getbootstrap.com/docs/4.0/getting-started/theming/) I should use the official version and import your scss.

This is available? I did not find any documentation about this.

This is critical, I must use an official version of Bootstrap. To not have a strong dependence on your Theme, to be able to update Bootstrap without waiting for an update of the Theme, ... 

For example, Bootstrap 4.1 is out, but not yet in your Theme.

**Comment by YZahringer** [comment]
I found the import of official Bootstrap in `material-dashboard.scss`. But the JS is not official, it's provided by `bootstrap-material-design` package, I have to import this customized version `../node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.min.js`? I can't use the official version and add subset?

**Comment by chelaruc** [comment]
Hi, @YZahringer 
If you will add the official bootstrap.js file, all the components for material will stop working as expected and that's why we are using bootstrap material design which is an extension of bootstrap.js. So you basically use the official bootstrap.js.

All the best,
Ciprian
