### ISSUE TITLE
Login page broken on Firefox 59.x

### ISSUE THREAD

**Issue by drenda** [creativetimofficial/material-dashboard-pro-angular#238]
On Firefox 59 on Mac this is how the login page looks like:

<img width="1280" alt="schermata 2018-04-23 alle 23 33 41" src="https://user-images.githubusercontent.com/3420646/39154595-1c602a56-474f-11e8-84cc-43bfae25465c.png">

Please fix the problem

**Comment by chelaruc** [comment]
@drenda thank you for point this. It will be fixed in v2.0.1

**Comment by drenda** [comment]
Do you have an ETA? We are going to release our application and this problem is very annoying. Thanks

**Comment by chelaruc** [comment]
@drenda v2.0.1 was released

**Comment by lippomano** [comment]
If I remove `body.classList.add('login-page')` from the login.component.ts 
the css : `.login-page .page-header, .lock-page .page-header {
    height: 100vh;
}` is NOT set and I see the login page like the picture in the question.
So can you explain me why this keep happening in v2.0.1.

**Comment by raskolnikov1041** [comment]
what was the fix?  i originally used v2.0 and now i downloaded v2.0.2 and i can't see a difference in pages/login.

**Comment by chelaruc** [comment]
@raskolnikov1041 Did you find any errors in the product?

**Comment by ShashidharSs** [comment]
based on the page footer is not adjusting,
