### ISSUE TITLE
Dropdown issue when opening menù

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#239]
I have an issue when I try to open a dropdown, first time  I need to click twice if I want to open the dropdown, like you see:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27501745/39363045-1f95b9a2-4a29-11e8-97d5-8e4c1dbda6e1.gif)

After that, the functionality seems good.
Can you help me to understand where is the problem?
Just updated to 2.0.1, the same problem in 2.0.0

**Comment by drenda** [comment]
Do you have some advice on that? Thanks

**Comment by chelaruc** [comment]
@lippomano @drenda this is not happening to my local project. Have you changed something to the archive?

**Comment by lippomano** [comment]
Importing packages in the `angular.cli.json` file in this order solve the problem:

```
"../node_modules/jquery/dist/jquery.js",
"../node_modules/popper.js/dist/umd/popper.js",
"../node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.min.js"
```
Now I don't see any kind of opening issue.
