### ISSUE TITLE
Incorrect positioning of navbar and footer on mobile view

### ISSUE THREAD

**Issue by ytijtgat** [creativetimofficial/material-dashboard-pro-angular#241]
The navbar and footer seem to have an absolute position on top and bottom of the screen on mobile view. This behavior is different from the Bootstrap 4 version of Material Dashboard Pro. This overlaps with content on the screen and is very annoying on mobile use.

Easily observable on a mobile device when going to e.g. login page and entering some data in an input field. The onscreen keyboard will pop up and resize the viewing window. The navbar and footer will now overlap with some parts of the login card.

Also reproducible in Chrome responsive mode with e.g. width of 350px and varying window height.
Expected behavior: http://demos.creative-tim.com/material-dashboard-pro/examples/pages/login.html 
Actual behavior: http://md-pro-angular.creative-tim.com/pages/login

**Comment by chelaruc** [comment]
Hi, @ytijtgat! Thank you for using our product. All you have to do is to replace the file from this archive with your current file:
[_pagination.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1967569/_pagination.scss.zip)

This will be fixed in next version.

All the best,
Ciprian

**Comment by chelaruc** [comment]
Hi, @ytijtgat!
Thank you for using our product. Change the file from this archive with the current file from your project and tell me if this worked.
[_pages.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1967662/_pages.scss.zip)

All the best,
Ciprian

**Comment by ytijtgat** [comment]
That fixed it!

Many thanks,
Youran
