### ISSUE TITLE
Card icon action

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#248]
Hi.
I want to suggest a new type of card icon header, usefull to put actions. An example
![image](https://user-images.githubusercontent.com/3708962/39759238-8a12da76-52a8-11e8-9426-71b7f7f42de7.png)

html code for the header part:
```
          <div class="card-header card-header-icon">
            <div class="card-icon card-header-primary">
              <i class="material-icons">people</i>
            </div>
            <div class="card-icon-action">
              <i class="material-icons"
                 matTooltip="Add new Client"
                 (click)="openClientWizard()">add</i>
              <i class="material-icons"
                 matTooltip="Refresh"
                 (click)="refresh()">refresh</i>
            </div>
          </div>
```

changes in _cards.scss
from:
```
    .card-icon,
    .card-text {
      border-radius: $border-radius-base;
      background-color: $gray-color;
      padding: 15px;
      margin-top: -20px;
      margin-right: 15px;
      float: left;
    }

    .card-text {
```

to:
```
    .card-icon,
    .card-icon-action,
    .card-text {
      border-radius: $border-radius-base;
      background-color: $gray-color;
      padding: 15px;
      margin-top: -20px;
      margin-right: 15px;
      float: left;
    }

    .card-icon-action {
      float: right;
      cursor: pointer;
      height: 60px;
      margin-top: -10px;
    }

    .card-text {
```

Open to suggestions.

**Comment by chelaruc** [comment]
Hi, @niesteszeck! Thank you for your feedback and we'll try to add them, but we need to do some design tests, we can put it without background, just the icons in the top corner. Like here:
<img width="451" alt="screen shot 2018-05-11 at 10 57 41" src="https://user-images.githubusercontent.com/22840626/39913670-63e32aee-550b-11e8-9b88-bad2c52c6e28.png">

All the best,
Ciprian

**Comment by niesteszeck** [comment]
that looks better, how can I use it?

**Comment by chelaruc** [comment]
@niesteszeck this is implemented in this dashboard: [https://github.com/creativetimofficial/now-ui-dashboard-angular](https://github.com/creativetimofficial/now-ui-dashboard-angular)
