### ISSUE TITLE
How to start with mini sidebar

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#250]
How can I start the dashboard layout with a mini sidebar instead of a full one?

**Comment by niesteszeck** [comment]
why the sidebar-mini class is added to body?

**Comment by chelaruc** [comment]
@niesteszeck you can add the class `sidebar-mini` on a parent of the sidebar and it will work.

**Comment by Roman991** [comment]
a little update: u have to add `sidebar-mini` class to <body>
