### ISSUE TITLE
Modal don't close on route change

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/material-dashboard-pro-angular#254]
If you have open a modal and then navigate back (or other type of route change), the body doesn't loose the modal-open class. So you cant do anything more with the page.

How to reproduce 

- open http://md-pro-angular.creative-tim.com
- navigate using the menú to Components-Notifications
- open any modal
- navigate back using your back button on your browser
- try to click anything (menu, link, etc)

**Comment by chelaruc** [comment]
@niesteszeck in `src/app/layouts/admin/admin-layout.component.ts` you have:
```
  this._router = this.router.events.filter(event => event instanceof NavigationEnd).subscribe((event: NavigationEnd) => {
          this.navbar.sidebarClose();
        });
```
All you have to do is to replace with this:
```
  this._router = this.router.events.filter(event => event instanceof NavigationEnd).subscribe((event: NavigationEnd) => {
          this.navbar.sidebarClose();
          const body = document.getElementsByTagName('body')[0];
          const modalBackdrop = document.getElementsByClassName('modal-backdrop')[0];
          if (body.classList.contains('modal-open')) {
            body.classList.remove('modal-open');
            modalBackdrop.remove();
          }
        });
```

**Comment by niesteszeck** [comment]
thx.

one question, why in the admin-layout and not on app.component. This way any page will remove modals on routes changes, even new layouts.

Also, will this fix be included in next release?

**Comment by chelaruc** [comment]
@niesteszeck yes, it will be fixed in next release. And I'll try to add it in `app.component.ts` to close the modal in all the layouts.

**Comment by niesteszeck** [comment]
@chelaruc I can confirm that works great on app.components.ts

have a great week
