### ISSUE TITLE
How to disable default loader on page load  ??

### ISSUE THREAD

**Issue by aleximmauell** [creativetimofficial/material-dashboard-pro-angular#258]
how to disable default loader on page load  ?? need help

![loader](https://user-images.githubusercontent.com/17826757/40228922-3fd56bda-5ab0-11e8-8c55-8485c9b1b6df.JPG)

**Comment by niesteszeck** [comment]
just remove it from index.html

**Comment by chelaruc** [comment]
@aleximmauell as @niesteszeck said all you have to do is to remove the code from the index.
