### ISSUE TITLE
autoclose sidebar menu on selection

### ISSUE THREAD

**Issue by cerokool32** [creativetimofficial/material-dashboard-pro-angular#26]
sidebar keeps open on selection when i'm on mobile screen.

**Comment by chelaruc** [comment]
Hi @cerokool32 

Thanks for using our products. We fixed that thing and you need to replace the following files:
[files_to_replace.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1097435/files_to_replace.zip)

Please let us know if this is working fine for you.

Keep in touch,
Ciprian
