### ISSUE TITLE
Open Dashboard in full-screen

### ISSUE THREAD

**Issue by raviready** [creativetimofficial/material-dashboard-pro-angular#27]
Is there a way to hide the sidebar based on a flag? If the flag is false then everything works as in the demo today. If the flag is set to true, the dashboard should be shown in full-screen, with the hamburger button on the right (that can be clicked to show/hide the sidebar). Basically when the flag is set, the dashboard works as it does today on a small screen but on any screen size.

Thanks,
Ravi Mareddy

**Comment by alexandru-paduraru** [comment]
@raviready thank you for using our product. To make sure that I understood right, are you talking about the full-screen feature of the browser? Like this one: https://www.sitepoint.com/use-html5-full-screen-api/ ?

**Comment by raviready** [comment]
Thanks for your reply, Alex. No, I am not talking about the browser full-screen feature. Currently I am able to collapse the sidebar menu in my logic by using a flag but ideally I would like to hide the sidebar menu (irrespective of the screen size).

To explain more, I am trying to build a dashboard that will run in two modes, an interactive mode and an auto slideshow mode. In the interactive mode, the sidebar menu is used to allow browsing through various screens. But in slideshow mode, I would like to use the full extent of available screen and for this I would like to hide the sidebar completely. At this time I put in logic that will collapse the dashboard but it still uses precious screen space.

Thank you,
Ravi

**Comment by alexandru-paduraru** [comment]
@raviready now I got it. We will think of a way to build that. At this moment what you can do is when you start your slideshow just to add a class on the body of the page which will work like this:

```css
.hide-sidebar .sidebar{
    display:none !important;
}
.hide-sidebar .main-panel{
    width: 100% !important;
}
```
Hope this helps till we will have an official release.

Best,
Alex

**Comment by raviready** [comment]
Okay, this seems to partially work (when I add this CSS class to the div in my app.component.html file) but issue is, the sidebar disappears and cannot be displayed again, even on clicking the regular menu button. No way to go back to interactive mode without refreshing the website.

When the sidebar is hidden, the hamburger menu should also appear on the right top so that the user can then choose further menu options from there.

Really appreciate that you will consider it for your next build. It will be a useful feature. Thanks.

**Comment by ishkurko** [comment]
+1
We need this feature also. Thank you.

**Comment by alexandru-paduraru** [comment]
@raviready @ishkurko this was approved as a future for the next release. Did you try to add/remove the class "hide-sidebar" from the body when you play/stop the presentation?

**Comment by raviready** [comment]
Alex, I tried the "hide-sidebar" class suggested by you but as mentioned earlier, once hidden there is no way to bring it back on again. That is, the menu is hidden completely and there is no access to it (the hamburger menu button needs to be shown at this time but I do not know how).

At this time I will continue with the minimized (collapsed) sidebar but await eagerly for the next release.

**Comment by raviready** [comment]
Alex, I see a new version released. How would I know if this feature was implemented or not? Can you provide an example on its usage if it was implemented. Thank you.

**Comment by alexandru-paduraru** [comment]
@raviready that was implemented. Please replace the `#minimizeSidebar` with `#hideSidebar` for the button in the navbar:

<img width="943" alt="screen shot 2017-09-24 at 18 16 45" src="https://user-images.githubusercontent.com/2517758/30783952-a8df6f6a-a154-11e7-9487-a8c8c399a254.png">

Hope this helps. We will do this update in the documentation too.

Best,
Alex

**Comment by raviready** [comment]
Thanks Alex and Creative Tim team. This seems to work as expected but it also seems to have introduced a bug. Wanted to bring that to your attention. After changing #minimizeSidebar to #hideSidebar, when you reduce the window size then the Sidebar shows up permanently in the middle of the window. Clicking the button docks the Sidebar to the right but clicking the button ('X') again shows the Sidebar in the middle of the window. Seems like #hideSidebar is not being hidden properly at all window sizes.
