### ISSUE TITLE
Problems with select tag, class="selectpicker" and dynamic data

### ISSUE THREAD

**Issue by jamper91** [creativetimofficial/material-dashboard-pro-angular#29]
Hi, guys (first, i I apologize for my spelling).
I am  trying to visualize a  multi select with an array of data, but the data come from a web service.
What its my problem? the select doesn't show any option.
In the next picture you can see how the select has the options tag, but when i click doesnt show anything
![sshot-5](https://user-images.githubusercontent.com/515314/27764272-10bc122e-5e5b-11e7-88af-251773883656.png)

I thoung the problem was mine, I try to load the data in the constructor, after init view, before init view and nothig, after that i use NgZone to "refresh" the view, but nothing.

But if i dont use the property class, the page works fine 
![sshot-7](https://user-images.githubusercontent.com/515314/27764276-1912a4ec-5e5b-11e7-987a-63789072f52d.png)

This is my html code

<select  name="subcategories" title="Productos" [(ngModel)]="company.subcategories" >
                                                                    <option value="{{subcategory.id}}" *ngFor="let subcategory of categories">{{subcategory.name}}</option>
                                                        </select>

**Comment by alexandru-paduraru** [comment]
@jamper91 please make sure you call the method "$(".selectpicker").selectpicker();" inside `ngAfterViewInit` that will make sure the selectpicker is called after the view was rendered. 

Also please replace in wizard.component.ts this line 228: 
`var total_steps = $wizard.find('li').length;`
with this one
`var total_steps = $wizard.find('.wizard-navigation li').length;`

 That will make sure the total_steps variable count only in the navigation steps, not on the selectpicker "li"

**Comment by jamper91** [comment]
Hi @alexandru-paduraru ,i change the code but doesn't still working, this is my code:
`ngAfterViewInit(){`
`this.veporel.get_categories()`
           	`	.map(res => res.json())`
            `.subscribe((result)=>{`
                `if(result)`
                `{`
                        `self.categories = result;`
                        `$("#categories").selectpicker({`
                            `size: 4`
                        `});`
                `}`
            `});`
`}`

Html

`<select class="selectpicker" id="categories"  name="subcategories" title="Productos" multiple [(ngModel)]="company.subcategories" >`
		`<option value="{{category.id}}" *ngFor="let category of categories">{{category.name}}</option>`
`</select>`

**Comment by alexandru-paduraru** [comment]
@jamper91 let's try to add the select picker inside a timeout like this:
```js
setTimeout(function(){
    $("#categories").selectpicker({
        size: 4
    });
},10);
```

**Comment by jamper91** [comment]
Hi @alexandru-paduraru , that is the solution, and the same problem with datatable.net and ajax data, i just need add a timer

**Comment by iSanjayAchar** [comment]
What if I need to dynamically change the data? I tried using the change function, but it is not working

**Comment by alexandru-paduraru** [comment]
@iSanjayAchar we just release the v1.4.0 version and that is having a Native Selectpicker, that means you will be able to sync it with your model and data. Please check it and let us know if you have any further feedback.

Best,
Alex

**Comment by abhisanand** [comment]
hey, how do i update the package

**Comment by alexandru-paduraru** [comment]
@abhisanand we can give you access to our private repo to see exactly which files we changed and you choose only the changes for the plugins that are used inside your project. If you have better ideas on how we can do this please let us know. Best, Alex!

**Comment by iSanjayAchar** [comment]
@alexandru-paduraru It will be better if you could share the repo's with us instead of ZIP file.

**Comment by bikramchoudhury** [comment]
@alexandru-paduraru  I am trying to select the options based on the model data. But it's not working.
