### ISSUE TITLE
How to implement an editable table?

### ISSUE THREAD

**Issue by softbrillianceperu** [creativetimofficial/material-dashboard-pro-angular#30]
Hi, 
Do you have a sample how to develop a table that can be able to edit data?
I see some samples but all present data only

Thanks in advance
Carlos V

**Comment by alexandru-paduraru** [comment]
@softbrillianceperu please check the original documentation of datatatbles.net for the Inline Edit: https://editor.datatables.net/examples/inline-editing/simple

Hope that helps.

Best,
Alex
