### ISSUE TITLE
The style doesn't load with a custom URL

### ISSUE THREAD

**Issue by jamper91** [creativetimofficial/material-dashboard-pro-angular#32]
Hi guys, If I try to load this url http://localhost:4200/tables/extended the app doesn´t load the styles 
![sshot-8](https://user-images.githubusercontent.com/515314/27979993-d8ccbb7c-633f-11e7-8d02-05c17ddc9641.png)
I tried to load the styles on the app.components with stylesUrl:[..] but doesn´t work

**Comment by alexandru-paduraru** [comment]
@jamper91 did you change anything in the original archive? This is what we get on the same link:

<img width="1440" alt="screen shot 2017-07-10 at 02 05 28" src="https://user-images.githubusercontent.com/2517758/27998275-5069870c-6514-11e7-94b7-fb93c14820a8.png">

Best,
Alex

**Comment by jamper91** [comment]
Not, i dont change anything, but if you put this rul in your browser http://localhost:4200/tables/extended without go to http://localhost:4200/. If i  type ng serve, the command open a new tab in http://localhost:4200 and all its ok if after that i go to http://localhost:4200/tables/extended everything its ok, but if a open a new tab or i reload this http://localhost:4200/tables/extended the problem happen
