### ISSUE TITLE
issue when compiling for production

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#34]
Hi,

when building downloaded source for production there is an issue related with wizard component seems... 

It is a fresh downloaded copy wich was served as 'ng serve --prod' and resulted on "src/$$_gendir/app/forms/wizard/wizard.component.ngfactory.ts (45,9): Supplied parameters do not match any signature of call target."

Can you help with this?
Thanks

**Comment by chelaruc** [comment]
Hi @figueiredorj 

Thank you for using our product and sorry for the late response. To fix this you need to go in _src/app/forms/wizard/wizard.component.ts_ and import SimpleChanges from `@angular/core` and change `ngOnChanges` with `ngOnChanges(changes: SimpleChanges)`. 
Tell us if this worked!

Keep in touch,
Ciprian
