### ISSUE TITLE
Having a more productive aproach under repetitive elements

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#35]
Hi,
I am starting development under this theme and have to say I do like how it looks.

However work start has something to say has it has some repetitives codes (at least about notifications) where it is defined in lots of places instead of having a component that could represent it....

**Comment by alexandru-paduraru** [comment]
@figueiredorj thank you for using our product and for the feedback. We are constantly updating the product based on the customers' feedback. We will optimize this on the next release. If you have any further feedback please let us know.

Best,
Alex
