### ISSUE TITLE
Project initialization on IE 

### ISSUE THREAD

**Issue by chelaruc** [creativetimofficial/material-dashboard-pro-angular#38]
To fix that please go to src/polyfills.ts on line 21 and uncomment these lines:

// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import ‘core-js/es6/set';

**Comment by norujlu** [comment]
Thanks you the issue has been fixed.
