### ISSUE TITLE
Login page render on iPad

### ISSUE THREAD

**Issue by eliesermorais** [creativetimofficial/material-dashboard-pro-angular#42]
Hello,

The login/register page render wrong on iPad. It looks ok on smartphone and desktop. See the image, menu cannot be close, still open all the time.

![erro](https://user-images.githubusercontent.com/913703/28746147-b86e932c-745c-11e7-9bb6-fe4487d3f123.jpg)

**Comment by alexandru-paduraru** [comment]
@eliesermorais thank you for pointing this out. We are working on it now and we will have an update tomorrow or Monday. Please stay tuned.

Best,
Alex
