### ISSUE TITLE
select with "selectpicker" class not show unless on post action of browser

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#43]
Hi,
I am trying to use some dropdowns styled on a component...
what I noticed is that if I navigate to view (angular) select's are not shown...
I do know it is something caused by style of selectpicker but still haven't figured what.. perhaps with your help it can go faster...

my component code:
`
<select data-style="btn btn-rose btn-square" style="display: block" title="Familias" data-size="7">
    <option value="">Todas Familias</option>
    <option value="1">Foobar</option>
    <option value="2">Is great</option>
</select>

<div class="card" style="width: 250px;">
    <div class="card-header" data-background-color="blue">
        <h4 class="card-title" style="text-align: center">Filtros</h4>
    </div>

    <div class="card-content">
        
        
        
        

        <select class="selectpicker bootstrap-select"  data-style="btn btn-rose btn-square" style="display: block" title="Familias"
                data-size="7">
            <option value="">Todas Familias</option>
            <option value="1">Foobar</option>
            <option value="2">Is great</option>
        </select>

        

        <div class="form-group">
            <div class="card">
                <div class="card-header" data-background-color="orange">
                    <h4 class="card-title">Preço</h4>
                    <div class="category">
                        <div class="checkbox"><label><input type="checkbox" name="optionsCheckboxes"> Filtrar</label>
                        </div>
                    </div>
                </div>
                <div class="card-content">
                    <div class="wrapper-inline row">
                        <div class="col-xs-6">
                            <input type="text" class="form-control" style="text-align: center;">
                        </div>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" style="text-align: center;">
                        </div>
                    </div>

                    

                </div>
            </div>
        </div>

    </div>
</div>`

[no_select.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1190148/no_select.zip)

Cheers

**Comment by figueiredorj** [comment]
As far as I understand it must be something related to javascript initialization....

**Comment by figueiredorj** [comment]
Got it...
As 'selectpicker' is a js native component it has to be dealt with some constrainsts...

First of all... if it is injected on view, you can't expect that "onload" handles initialization of it...
use:

```
export class SomeComponent implements OnInit, AfterViewInit {
    ngAfterViewInit(): void {
        $('.selectpicker').selectpicker();
    }
```

If you need to update data during window scope then you must subscrive an update event and on it run
```
            setTimeout(() => {
                $('.selectpicker').selectpicker('refresh');
            }, 500);
```
This is related to Angular +2

**Comment by chelaruc** [comment]
Hi @figueiredorj,

Thank you for using our product! We're sorry for the late response, but we're glad you found the solution! 

All the best,
Ciprian

**Comment by figueiredorj** [comment]
Hi,
althought I wsa able to initialize the control, I am kind of having some trouble on binding values to the control on my view...

Some help please?
How do I use this control on angular noticing that this something initialized from jquery..... :S

**Comment by figueiredorj** [comment]
ok, Now this was an issue relatred to 'newbie' on angular... 

Just declare FormsModule and bind select with [(ngModel)]...

thanks anyway
Cheers

**Comment by alexandru-paduraru** [comment]
Did you refreshed the selectpicker after you set the value in TS?
