### ISSUE TITLE
How to align controls in a row?

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#45]
Sorry, this is more of a support question.
I have a text edit, a datepicker and a checkbox which I need to show on a single row. Currently the vertical alignment of each control is different so that the appear messy on screen. I can't get any of the normal alignment tags to work.

Sorry if this is just my ignorance, how can I vertically align all of these controls so the text appears at the same alignment.

**Comment by alexandru-paduraru** [comment]
@mcurrycl thank you for using our product. Do you have an example so we can see what is the problem?

Best,
Alex

**Comment by mcurrycl** [comment]
![image](https://user-images.githubusercontent.com/8777232/28961241-f5563316-7944-11e7-901d-807b659c0af6.png)

In this example, I want to vertically align the checkbox and text "SMS" with the text on the text controls. Thanks!

**Comment by alexandru-paduraru** [comment]
Add the class `checkbox checkbox-inline` and that should work fine. 

Best,
Alex

**Comment by mcurrycl** [comment]
Thanks Alex,

I tried this but the alignment still doesn't work.

**Comment by alexandru-paduraru** [comment]
@mcurrycl do you have a link that we can check?
