### ISSUE TITLE
How to deploy this project in tomcat?

### ISSUE THREAD

**Issue by iedwin** [creativetimofficial/material-dashboard-pro-angular#47]
I have tried several methods such as using "ng build --base-herf" or move the dist forder to tomcat webapps/ROOT/. All failed and 404 always occurred. 
Could you please give a guild for deploy to tomcat? Thanks a lot in advance!
<img width="571" alt="screen shot 2017-08-13 at 10 54 06 pm" src="https://user-images.githubusercontent.com/17739715/29250749-9f06ce10-800d-11e7-9003-d1fccba95d81.png">

**Comment by aVolpe** [comment]
To work with a `context path` I add this to my `index.html` file:

    <script type="text/javascript">
    if (document.location.href.indexOf('/context/') > 0)
        document.write("<base href='/context/' />");
    </script>

In the head part of the html, it's not pretty, but it works.

**Comment by iedwin** [comment]
@aVolpe 
Thanks a lot! But really strange, it doesn't work for me...
I added that code in the head of index.html and ran "ng build --prod". Then I moved the whole dist folder to tomcat webapps folder. The second time I moved the dist folder to webapps/ROOT/. At last I deleted the origin "<base href / >" before I changed the code in index.html. 404 error still occurred..
Could you please share your procedure more in detail? I believe I must have something wrongly configured. : (

**Comment by aVolpe** [comment]
You can access the assets by URL? I recommend you to build a simple war file to check the correct location of everything

In this  [gist](https://gist.github.com/aVolpe/8c91a43750fcacca426699d8582b84da) I put the base configuration to build a war for this project, you can run `mvn generate-sources package` and mvn will generate a war file that you can use to deploy to your tomca. All the files of that gist must be in the root folder.

This works with the `<script>` tag that I put before.

**Comment by ogarvey** [comment]
@iedwin Are you moving the dist folder itself, or the contents of the folder?

**Comment by alexandru-paduraru** [comment]
@iedwin this is the first time when we see somebody trying to deploy our product to Tomcat. Unfortunately, we don't have much experience with that, we always used Heroku as the deploy server service. We also included a tutorial in the documentation on how to work with that. In the meantime maybe this answer will help: https://stackoverflow.com/questions/40461171/integrate-angular2-project-into-tomcat-server

Best,
Alex

**Comment by iedwin** [comment]
@alexandru-paduraru @aVolpe @ogarvey @timshingyu 
Thanks all of you! This is absolutely the answer: https://stackoverflow.com/questions/40461171/integrate-angular2-project-into-tomcat-server
My procedures in detail:
1. Change base in index.html to "."
```
<base href='.'>
```
2. ng build --prod --aot 
3. Copy index.html, all the js files and assert/ in "/your-project-path/dist/" to "tomcat-path/webapps/ROOT/"

Then run tomcat and you can now see the page via http://localhost:8080
