### ISSUE TITLE
Chartist plugin is not working 

### ISSUE THREAD

**Issue by norujlu** [creativetimofficial/material-dashboard-pro-angular#49]
We are having dificulties with chartist plugins. For example we are trying to show legend on the chart. this.widgetchart.update( this.MultiBarChartData ,{ seriesBarDistance: 10, axisX: {showGrid: false}, height: '400px', plugins: [Chartist.plugins.legend()] } // , this.ResponsiveOptionsMultipleBarsChart ); // update the chart with the new data We got an error: Cannot read property 'legend' of undefined.

Please find attach project files:
[AngularDemoQuipsound.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1227721/AngularDemoQuipsound.zip)

**Comment by alexandru-paduraru** [comment]
@norujlu thank you for using our product. We will have a look on this next week when we will be in the office and come back with a solution.

Best,
Alex

**Comment by norujlu** [comment]
Dear Alex,

Do you have any update regarding this issue?

Thanks

Nigar.

Nigar Orujlu
Senior Developer

DDI: +44 (0) 1959 560291
Tel: +44 (0) 1959 561717
Fax: +44 (0) 1959 564740

Quipsound Ltd
The Crown Building
London Road
Westerham
Kent
TN16 1UT

Web: www.quipsound.com<http://www.quipsound.com>

**Comment by chelaruc** [comment]
Hi Nigar,

We looked in your project and saw that you have `id='#testChart'`, please change it with `testChart`, and in `test-charts.component.ts` you will do as in the picture below:

<img width="1075" alt="screen shot 2017-08-24 at 15 27 23" src="https://user-images.githubusercontent.com/22840626/29666416-de16ff4a-88e0-11e7-8f48-5d5dd8bd8524.png">

 Tell me if it works for you!

Best, 
Ciprian

**Comment by norujlu** [comment]
Hi Ciprian

Could you please ignore test-charts component.

Please refer to to charts.component.ts.

When we add plugins the chart is not working:

var optionsMultipleBarsChart = {
            seriesBarDistance: 10,
            axisX: {
                showGrid: false
            },
            height: '300px'
            ,plugins: [Chartist.plugins.legend()]
        };

 See screenshot below:
![image](https://user-images.githubusercontent.com/31059539/29666955-685e1468-88d2-11e7-98ca-03b145ed9ed2.png)

Thanks you for your help.

Regards,

Nigar.

**Comment by chelaruc** [comment]
Hi Nigar

Add this code after your imports:
```
declare var require: any;
require('chartist-plugin-legend');
```

Best,
Ciprian

**Comment by norujlu** [comment]
Thank you, it works now!

Nigar Orujlu
Senior Developer

DDI: +44 (0) 1959 560291
Tel: +44 (0) 1959 561717
Fax: +44 (0) 1959 564740

Quipsound Ltd
The Crown Building
London Road
Westerham
Kent
TN16 1UT

Web: www.quipsound.com<http://www.quipsound.com>

**Comment by norujlu** [comment]
Hi @chelaruc 
Legend  now appears, but there are no colours against each label in the legend.
![image](https://user-images.githubusercontent.com/31059539/29708395-66ee5b48-8980-11e7-9a91-158774ff9300.png)


I have uploaded test project for you to check.
Thanks

Nigar.
[AngularLegendIssue.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1251448/AngularLegendIssue.zip)

**Comment by norujlu** [comment]
Hi @alexandru-paduraru , @chelaruc 

Do you have any update regading this issue?

Thanks

Nigar.

**Comment by chelaruc** [comment]
Hi Nigar,

I've made some changes in your app. I've moved your css code in `assets/sass/material-dashboard/plugins/chartist.scss'` and in `angular.cli.json` I've changed the default `styleExt` from `.css ` to `.scss` and `"styles": ["assets/sass/material-dashboard.scss"],`. Check the below archive.

Best,
Ciprian
[Archive.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1259700/Archive.zip)

**Comment by norujlu** [comment]
Hi @chelaruc 
Thank you, I can see colours agains each label, but unfortunately colours don't match to colours of graph.
![image](https://user-images.githubusercontent.com/31059539/29814268-ac4b454e-8ca4-11e7-9f52-b707f2095601.png)


Do you know How this can be fixed?

Thanks

Nigar.

**Comment by chelaruc** [comment]
You have to make the css so that each line has its own color.
```
.ct-chart
{
    background-color:white;
}

.ct-legend{
    color: red;
}
.ct-legend li {
    position: relative;
    padding-left: 20px;
    margin-right: 10px;
    margin-bottom: 3px;
    cursor: pointer;
    display: inline-block;
    line-height: 16px;
}

.ct-legend li:before {
    width: 16px;
    height: 16px;
    position: absolute;
    left: 0;
    content: '';
    border: 3px solid transparent;
    border-radius: 2px;
}

.ct-legend li.inactive:before {
    background: transparent;
}

.ct-legend li.ct-legend-inside {
    position: absolute;
    top: 0;
    right: 0;
}

.ct-legend li.ct-series-0:before {
    background-color: blue;
    border-color: blue;
}

.ct-legend li.ct-series-1:before {
    background-color: red;
    border-color:  red;
}

.ct-legend li.ct-series-2:before {
    background-color: orange;
    border-color: orange;
}

.ct-legend li.ct-series-3:before {
    background-color: green;
    border-color: green;
}

.ct-legend li.ct-series-4:before {
    background-color: pink;
    border-color: pink;
}

```

Best,
Ciprian

**Comment by norujlu** [comment]
Thanks @chelaruc , it works now.
