### ISSUE TITLE
Material Component

### ISSUE THREAD

**Issue by karthinuk107** [creativetimofficial/material-dashboard-pro-angular#5]
Hi,

I want to include material checkbox with selectall function

please find the below script

JS

angular.module('MyApp',['ngMaterial', 'ngMessages', 'material.svgAssetsCache'])

.controller('AppCtrl', function($scope) {
  $scope.items = [1,2,3,4,5];
  $scope.selected = [1];
  $scope.toggle = function (item, list) {
    var idx = list.indexOf(item);
    if (idx > -1) {
      list.splice(idx, 1);
    }
    else {
      list.push(item);
    }
  };

  $scope.exists = function (item, list) {
    return list.indexOf(item) > -1;
  };

  $scope.isIndeterminate = function() {
    return ($scope.selected.length !== 0 &&
        $scope.selected.length !== $scope.items.length);
  };

  $scope.isChecked = function() {
    return $scope.selected.length === $scope.items.length;
  };

  $scope.toggleAll = function() {
    if ($scope.selected.length === $scope.items.length) {
      $scope.selected = [];
    } else if ($scope.selected.length === 0 || $scope.selected.length > 0) {
      $scope.selected = $scope.items.slice(0);
    }
  };
});

html
<div ng-controller="AppCtrl" class="md-padding demo checkboxdemoSelectAll" ng-app="MyApp">
  <div layout="row" layout-wrap="">
    <div flex="100" layout="column">
      <div>
          <div layout="row" layout-wrap="" flex="">
          <div flex-xs="" flex="50">
            <md-checkbox aria-label="Select All" ng-checked="isChecked()" md-indeterminate="isIndeterminate()" ng-click="toggleAll()">
              <span ng-if="isChecked()">Un-</span>Select All
            </md-checkbox>
          </div>
            <div class="demo-select-all-checkboxes" flex="100" ng-repeat="item in items">
              <md-checkbox ng-checked="exists(item, selected)" ng-click="toggle(item, selected)">
               {{ item }}
              </md-checkbox>
            </div>
          </div>
        </fieldset>
      </div>
    </div>

css
.checkboxdemoSelectAll .demo-legend {
  color: #3F51B5; }

.checkboxdemoSelectAll .demo-fieldset {
  border-style: solid;
  border-width: 1px;
  height: 100%; }

.checkboxdemoSelectAll .demo-select-all-checkboxes {
  padding-left: 30px; }

**Comment by chelaruc** [comment]
@karthinuk107 Thank you for using our product. Can you give us a link to your repo or some screenshots? We did not understand what you mean and we want some details.

Keep in touch,
Ciprian

**Comment by karthigv** [comment]
Hi All,

Thanks for Creating beautiful web app.Here is the scenario I am facing, I want to Visualize Relationship charts with D3 and my data source was Google Big Query.

So I want to Connect to Big query and get the data based on Users filter conditions and visualize into D3.

I have a lot of Solution available for Angular 1 but not for 2

Could you please guide me on this

Please have this solution on as soon as possible

and also please give some link or tutorial for Angular2 with Big query and D3

**Comment by alexandru-paduraru** [comment]
@karthigv thank you for the detailed explanation. Can you please let us know how the D3 and Google Big Query is linked to the first request with checkboxes? 

Also please let us know what is D3 and BigQueryData, this is the first time when we hear about them. Do you have any repo where we can check your code and see if we can give you a solution?

Best,
Alex
