### ISSUE TITLE
Wizard: invoke angular service on tab change

### ISSUE THREAD

**Issue by figueiredorj** [creativetimofficial/material-dashboard-pro-angular#50]
Hi,
Althought I do like pretty much of this theme, I have to say that having jquery plugins onto an angular development is becoming a time reducer for what sould be some simple tasks.

Currently I have an issue related to wizard: I have to update a source of a grid on tab change with option from last wizard page.

That being said... how should I handle this issue? I mean.. how do  I invoke an angular service from wizard event? any clue?

thanks

**Comment by alexandru-paduraru** [comment]
@figueiredorj thank you for using our product. We are in the process of migrating all the jQuery components to Angular Native components. We started the dev of Angular products a couple of months ago and we are learning a lot from the feedback that we get from our customers. 

Till we will do an official releas with a Native Wizard you have 2 options:

1. Replace the current wizard with a native one: https://www.npmjs.com/package/angular2-wizard
2. Try to call the angular service like how they explain here: https://stackoverflow.com/questions/18758997/call-angular-function-with-jquery

Hope this helps. Please let us know your status and any further feedback. 

Best,
Alex

**Comment by figueiredorj** [comment]
@alexandru-paduraru 

When I realized that I woulodn't be able to finish my development based on current wizard I ended going with archwizard [()](https://github.com/madoar/ng2-archwizard)

**Comment by alexandru-paduraru** [comment]
@figueiredorj thank you for letting us know about it. Can you please give us more details about your case with it? Is it easy to be used and helped you in the process? If you confirm that it is a good plugin, we would be happy to change the current wizard with the one suggested. 

Best,
Alex

**Comment by figueiredorj** [comment]
Hi @alexandru-paduraru ,
been out of business for sometime :)

archwizard only thing I see better without looking too much on your suggestion was having icons.. don't know if angular2-wizard does so thought... also the ability to jump steps (as I saught wizard suggestion allows to hide them)

Actually going to give a try on wizard for a fidderent use case where ability to hide seems more intuitive

I will let you know after using it my opinion
