### ISSUE TITLE
sidebar navigation's active class not working while using ngIf

### ISSUE THREAD

**Issue by shreenil** [creativetimofficial/material-dashboard-pro-angular#51]
I'm using `ngIf ` to hide and show the sidebar navigation list.
When i load the web page first time it shows the active link on dashboard as dashboard is my initial component. But issue occurs when i click on any other link. The active class disappears after navigating to another page.

**Code** :
```
<ul class="nav">
                    <li routerLinkActive="active">
                        <a  routerLink="/dashboard">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li *ngIf="(role=='patient')?true:false" routerLinkActive="active">
                        <a routerLink="/patient-appointment">
                            <i class="material-icons">event</i>
                            <p>Book Appointment</p>
                        </a>
                    </li>
                    <li *ngIf="(role=='doctor')?true:false" routerLinkActive="active">
                        <a routerLink="/doctor-appointment">
                            <i class="material-icons">event</i>
                            <p>Book Appointment</p>
                        </a>
                    </li>

 </ul>
```
I have tried to apply `ngIf` on `ul` tag, But the issue remains same.

**Comment by alexandru-paduraru** [comment]
@shreenil thank you for using our product and sorry for the late response. Can you please let us know what exactly you want to achieve? The active class is added automatically, as you can see in our original product: http://md-pro-angular.creative-tim.com/ so you don't have to add any conditions. What is the case where you want to add `ngIf` so we can see how we can help.

Best,
Alex

**Comment by shreenil** [comment]
I'm not trying add active class. My app has two roles 'doctor' and 'patient'. What i want to do is when the logged in user is 'patient' he should not see the some of the links. So if the role is 'patient' than the link having `'/doctor-appointment'` should not be displayed. and if the role is 'doctor' `'/patient-appointment` should not be displayed. The conditions are working good, The links are hidden perfectly. But the active class of the `li` is not working. If i remove `*ngIf` than it is working completely fine.

**Comment by chelaruc** [comment]
Hi, @shreenil! Do you have the latest version of MDP?

Best, 
Ciprian

**Comment by shreenil** [comment]
@chelaruc Yes, it is the latest one(1.4.1)

**Comment by chelaruc** [comment]
@shreenil Are you sure the role is returning correct information?

Best,
Ciprian

**Comment by shreenil** [comment]
@chelaruc Yes, In fact my links are hidden also.

**Comment by chelaruc** [comment]
@shreenil What version you have? The latest is 1.4.1

**Comment by chelaruc** [comment]
@shreenil Can you give me your files for testing? My email address is `ciprian@creative-tim.com`.

**Comment by chelaruc** [comment]
@shreenil Did you found a solution for this?

**Comment by shreenil** [comment]
@chelaruc No but i used another way to achieve it!
