### ISSUE TITLE
Error to run

### ISSUE THREAD

**Issue by wagnerperin** [creativetimofficial/material-dashboard-pro-angular#52]
I tried to run the project but received the following error messages:

`ERROR in multi script-loader!./node_modules/jquery/dist/jquery.js script-loader!./node_modules/bootstrap/dist/js/bootstrap.js script-loader!./node_modules/bootstrap-material-design/dist/js/material.min.js script-loader!./src/assets/js/core/material.min.js script-loader!./node_modules/arrive/src/arrive.js script-loader!./node_modules/moment/moment.js script-loader!./node_modules/chartist/dist/chartist.js script-loader!./node_modules/chartist-plugin-zoom/dist/chartist-plugin-zoom.js script-loader!./node_modules/twitter-bootstrap-wizard/jquery.bootstrap.wizard.js script-loader!./node_modules/bootstrap-notify/bootstrap-notify.js script-loader!./node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js script-loader!./node_modules/nouislider/distribute/nouislider.min.js script-loader!./node_modules/bootstrap-select/dist/js/bootstrap-select.js script-loader!./node_modules/datatables.net/js/jquery.dataTables.js script-loader!./node_modules/datatables.net-bs/js/dataTables.bootstrap.js script-loader!./node_modules/datatables.net-responsive/js/dataTables.responsive.js script-loader!./node_modules/fullcalendar/dist/fullcalendar.js script-loader!./node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.js script-loader!./node_modules/jasny-bootstrap/dist/js/jasny-bootstrap.min.js script-loader!./src/assets/js/core/jquery.perfect-scrollbar.min.js script-loader!./src/assets/js/plugins/jquery-jvectormap.js script-loader!./src/assets/js/plugins/sweetalert2.min.js script-loader!./src/assets/js/core/jquery.validate.min.js
Module not found: Error: Can't resolve '/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js' in '/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/@angular/cli/models/webpack-configs'
resolve '/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js' in '/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/@angular/cli/models/webpack-configs'
  using description file: /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/@angular/cli/package.json (relative path: ./models/webpack-configs)
    using description file: /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/package.json (relative path: ./node_modules/datatables.net/js/jquery.dataTables.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js.js doesn't exist
      as directory
        /Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js doesn't exist
[/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js]
[/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js.ts]
[/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js.js]
[/Users/wagnerperin/Desktop/md-pro-angular-v1.4.0-html/node_modules/datatables.net/js/jquery.dataTables.js]
 @ multi script-loader!./node_modules/jquery/dist/jquery.js script-loader!./node_modules/bootstrap/dist/js/bootstrap.js script-loader!./node_modules/bootstrap-material-design/dist/js/material.min.js script-loader!./src/assets/js/core/material.min.js script-loader!./node_modules/arrive/src/arrive.js script-loader!./node_modules/moment/moment.js script-loader!./node_modules/chartist/dist/chartist.js script-loader!./node_modules/chartist-plugin-zoom/dist/chartist-plugin-zoom.js script-loader!./node_modules/twitter-bootstrap-wizard/jquery.bootstrap.wizard.js script-loader!./node_modules/bootstrap-notify/bootstrap-notify.js script-loader!./node_modules/eonasdan-bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js script-loader!./node_modules/nouislider/distribute/nouislider.min.js script-loader!./node_modules/bootstrap-select/dist/js/bootstrap-select.js script-loader!./node_modules/datatables.net/js/jquery.dataTables.js script-loader!./node_modules/datatables.net-bs/js/dataTables.bootstrap.js script-loader!./node_modules/datatables.net-responsive/js/dataTables.responsive.js script-loader!./node_modules/fullcalendar/dist/fullcalendar.js script-loader!./node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.js script-loader!./node_modules/jasny-bootstrap/dist/js/jasny-bootstrap.min.js script-loader!./src/assets/js/core/jquery.perfect-scrollbar.min.js script-loader!./src/assets/js/plugins/jquery-jvectormap.js script-loader!./src/assets/js/plugins/sweetalert2.min.js script-loader!./src/assets/js/core/jquery.validate.min.js

webpack: Failed to compile.`

What's happened here?

**Comment by chelaruc** [comment]
Hi @wagnerperin,

Thank you for using our product! Did you follow exact steps like in documentation?

Best,
Ciprian

**Comment by wagnerperin** [comment]
Yes ... but the problem is that I was using version 8.4.0 of node.js. I downgraded to 6.11.2 and it worked.

Thx,

**Comment by KarmicJohn** [comment]
I have the same error. I could try to downgrade to 6.11.2 but would prefer not to do so. The instructions, [here](http://md-pro-angular.creative-tim.com/documentation/tutorial), just say to download from the homepage. Is this not compatible with the latest?

**Comment by chelaruc** [comment]
Hi, @KarmicJohn! Thank you for using our product! For fixing this issue, you need to follow this steps:
1. Delete `package-lock.json` from your project
2. Run `npm install`
3. Run `npm rebuild node-sass --force`
4. `ng serve`

Tell me if this worked for you!

Best, 
Ciprian

**Comment by clintmasden** [comment]
I resolved this by running : npm install -g angular-cli / since the project is on 1.4.1 and my local version was 1.3.0.
