### ISSUE TITLE
Modal Scroll Error

### ISSUE THREAD

**Issue by ehdwns980416** [creativetimofficial/material-dashboard-pro-angular#53]
I opened Modal and I can't scroll it.
The examples are the same.
http://md-pro-angular.creative-tim.com/components/notifications

I think this is scrollbar problem. What should I do?

**Comment by norujlu** [comment]
I got the same problem but only in IE

**Comment by norujlu** [comment]
It works in Chrome and Firefox, follwoing should be added to css

  .modal-body{
            max-height: calc(100vh - 200px);
            overflow-y: auto;
        }

**Comment by ehdwns980416** [comment]
I tried but I have the same problem.

**Comment by ehdwns980416** [comment]
Here it is.
OS: Windows 10 pro
Browser: chrome browser v.60.0.3112.101

**Comment by chelaruc** [comment]
@ehdwns980416 @norujlu add the following lines in `src/app/layouts/admin/admin-layout.component.ts` on 35 line:
````
$('.modal').on('shown.bs.modal', function (e: any) {
                console.log('shown');
                $main_panel.perfectScrollbar('destroy');
            }).on('hidden.bs.modal', function (e: any){
                console.log('hidden');
                $main_panel.perfectScrollbar();
            });
````
Tell me if it workes for you!

Best,
Ciprian

**Comment by ehdwns980416** [comment]
Awesome!!!!

**Comment by norujlu** [comment]
Thanks, worked for me too.
