### ISSUE TITLE
npm install error (new angualr cli version)

### ISSUE THREAD

**Issue by pawmel** [creativetimofficial/material-dashboard-pro-angular#54]
![obraz](https://user-images.githubusercontent.com/20113449/29562909-9f26598a-873b-11e7-90f4-19b19c4f4099.png)

**Comment by chelaruc** [comment]
Hi @pawmel,

Thank you for using our product! Did you follow exact steps like in documentation?

Best,
Ciprian

**Comment by pawmel** [comment]
I did:
1. install node 6.11.2
2. npm install -g @angular/cli
3. copy project folder and go there
4. change package.json 
5. npm install

**Comment by chelaruc** [comment]
Why you changed package.json?

**Comment by pawmel** [comment]
from tutorial: "Replace package.json with this code."

**Comment by chelaruc** [comment]
![screen shot 2017-08-23 at 11 39 20](https://user-images.githubusercontent.com/22840626/29606706-bee408b4-87f7-11e7-984d-dd836e043131.png)

**Comment by pawmel** [comment]
ok, I copied project folder, ran 3 command and I've got:

**Comment by pawmel** [comment]
![obraz](https://user-images.githubusercontent.com/20113449/29608924-e63c61b0-87f5-11e7-9bbc-afad595a0d5b.png)

**Comment by chelaruc** [comment]
Can you send me your package.json?

**Comment by pawmel** [comment]
https://drive.google.com/file/d/0Byl-nOAJfly3LVRNd2RXWHMwT3M/view?usp=sharing

**Comment by chelaruc** [comment]
Do you have Material Dashboard Pro Angular or Light Bootstrap Dashboard Free Angular? This repo is for Material Dashboard Pro Angular and it seems you have the package for Light Bootstrap Dashboard Free Angular.

**Comment by pawmel** [comment]
I bought Web Angular 4.0 Dashboard 
and  asked Mrs. if there will be update for Light Blue - Web & Angular 4.0 Dashboard to 
CLI version, and if there will be some AoT implemented coz it takes 9 seconds to load. 

I got mail from yesterday: 

> Hey Pawel,
> 
> The update has just been released. The new version is built with Angular 4 CLI and has native support for selectpicker, tags, datepicker. There are a few plgins still on jQuery, because there is no alternative on Angular for now. 
> 
> If you want to see the documentation, here it is: http://md-pro-angular.creative-tim.com/documentation/tutorial
> 
> Hope this clears things up :)
> 
> All the best,
> Cristina

and I'm little cofused now. Does the admin panel I bought got upgraded?

**Comment by chelaruc** [comment]
We are a little bit confused, too. Can you say us what product do you bought and what email address do you have?
