### ISSUE TITLE
Project doesn't render in IE

### ISSUE THREAD

**Issue by norujlu** [creativetimofficial/material-dashboard-pro-angular#55]
Hello,

We are using template for dahsboard, but it doesn't render in IE, it works fine in all other browers, what would you suggest to fix this issue?

Thanks

Nigar.

**Comment by chelaruc** [comment]
Hi @norujlu!

Thank you for using our product! We fixed it in #38.

Best, 
Ciprian

**Comment by norujlu** [comment]
Thanks, it works now.
