### ISSUE TITLE
Sidebar Space Bug

### ISSUE THREAD

**Issue by WaleedZ90** [creativetimofficial/material-dashboard-pro-angular#56]
In the Sidebar 
ROUTES (Menu Items)
1] Create an object of type sub
2] add any value in title with a space eg. "User Authentication".

Output:
the node doesn't dropdown when you click it

**Comment by alexandru-paduraru** [comment]
@WaleedZ90 thank you for using our product. We will have a look and come back with a solution.

I've added my colleague Ciprian and he will assist you.

Best,
Alex

**Comment by chelaruc** [comment]
Hi @WaleedZ90 

We fixed that bug. You need to replace the `sidebar.component.html` and `sidebar.component.ts` with the files attached here. Tell us if it worked for you!

[sidebar_bug.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1259742/sidebar_bug.zip)

Best,
Ciprian

**Comment by chelaruc** [comment]
fixed in v1.4.5
