### ISSUE TITLE
created a new component with route, getting 404 NotFoundHttpException

### ISSUE THREAD

**Issue by h2i** [creativetimofficial/material-dashboard-pro-angular#57]
i just created a user profile page with the path 'user'  and added the module and path in app.routing.ts file

import { Routes } from '@angular/router';

import { AdminLayoutComponent } from './layouts/admin/admin-layout.component';
import { AuthLayoutComponent } from './layouts/auth/auth-layout.component';

export const AppRoutes: Routes = [
    {
      path: '',
      redirectTo: 'dashboard',
      pathMatch: 'full',
    },
    {
      path: '',
      component: AdminLayoutComponent,
      children: [
          {
        path: '',
        loadChildren: './dashboard/dashboard.module#DashboardModule'
       },
       {
        path: 'user',
        loadChildren: './user/user.module#UserModule'
       }
  ]
    }
];

With this if i try the root url its working fine, http://localhost:8011/ redirects to http://localhost:8011/dashboard properly

if i try http://localhost:8011/dashboard and http://localhost:8011/user path im getting 404.

Can you please help me with this issue.

I using angular4 with laravel project
https://github.com/jaesung2061/anvel

**Comment by chelaruc** [comment]
Hi @h2i,

Can you give me your user.module.ts and user.routing.ts ?

**Comment by h2i** [comment]
hi,
thanks for getting back. This issue is fixed when i added useHash to the router module in the app.module.ts

RouterModule.forRoot(AppRoutes, {useHash: true})
