### ISSUE TITLE
Fixing datatables.net trouble on 1.4.1

### ISSUE THREAD

**Issue by netinhoteixeira** [creativetimofficial/material-dashboard-pro-angular#58]
Hello,

I had a trouble when tried to build and serve, it was missing the datatables.net and I solved with this command: `npm install datatables.net --save`

I'm sending my diff screenshot too.
<img width="500" alt="screen shot 2017-08-25 at 9 30 11 pm" src="https://user-images.githubusercontent.com/1563399/29737004-850e1b74-89dd-11e7-8f87-42ff37af78b5.png">

Cya

**Comment by netinhoteixeira** [comment]
I know that needs to put the right version, but I was lost and tried many things. See u later.

**Comment by alexandru-paduraru** [comment]
@netinhoteixeira thank you for the information and the solution!
