### ISSUE TITLE
Button has no animation

### ISSUE THREAD

**Issue by nrebequi** [creativetimofficial/material-dashboard-pro-angular#59]
Clicking the buttons does not execute the animation.
Inspecting the code I see that it is not including the element
`<div class = "ripple-container"> </ div>`
Inside the button element.

I guess I have a problem setting up my project.
Can you help me?
Thanks!

**Comment by alexandru-paduraru** [comment]
@nrebequi thank you for using our product. Please make sure you initialize the `$.material.init();` as we do in `app.component.ts`, line 14.

Hope this helps.

Best,
Alex
