### ISSUE TITLE
If toggle switch is used to represent True/False(1/0) in datatables.net, the sorter doesnt work

### ISSUE THREAD

**Issue by sumitdhameja** [creativetimofficial/material-dashboard-pro-angular#6]
If I'm using datatables and using toggle to show True/False state, the sort doesn't seem to be working on that specific column. Seems to be working fine if Im representing it simply by 1/0 values for true/false expression.
Example Column:
```
  <td>
        <div class="togglebutton">
            <label class="togglebutton">
                  <input type="checkbox" [(ngModel)]="person.Enabled" disabled>
            </label>
          </div>
   </td>
```

**Comment by alexandru-paduraru** [comment]
@sumitdhameja thank you for using our product and sorry for the late response. Can you please share with us the code portion from your typescript and let us know where you initialise the datatables?

In this way, we will test your case and give you a quick fix.

Best,
Alex

**Comment by sumitdhameja** [comment]
@alexandru-paduraru in my component I am calling the script as 
```$.getScript('../../../assets/js/init/initDataTable.js');```
I invoke initDataTable() function in ngOnInit for that component.
In my initTable.js, I invoke thefunction as shown below. I am using Angular-Cli with this project

```
(function initDataTable() {


  $('#datatables').DataTable({
    "pagingType": "full_numbers",
    "bSort": true,
    "lengthMenu": [
      [10, 25, 50, -1],
      [10, 25, 50, "All"]
    ],
    responsive: true,
    language: {
      search: "_INPUT_",
      searchPlaceholder: "Search records",
    }

  });
```
