### ISSUE TITLE
Issues with dashboard in IE

### ISSUE THREAD

**Issue by norujlu** [creativetimofficial/material-dashboard-pro-angular#60]
Hello

Dashboard with charts are working fine in Chrome, but we got issues when the same dahsboard working in IE. For example when the IE browser is not maximized, and then we maxime it, we got follwoing error ( see screenshot below)

![image](https://user-images.githubusercontent.com/31059539/29913303-b1c68e64-8e2c-11e7-85b6-5ea28753c3d4.png)

Coul you please let me know how this can be fixed?

Code of Polyfiis.ts 
------------------------------------------------
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/** Evergreen browsers require these. **/
import 'core-js/es6';
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';

/** ALL Firefox browsers require the following to support `@angular/animation`. **/
import 'web-animations-js';  // Run `npm install --save web-animations-jsnpm install --save web-animations-js`.

/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
 import 'intl';  // Run `npm install --save intl`.

 import 'intl/locale-data/jsonp/en.js';

--------------------------------------------------

Thanks

Nigar.
cc: @alexandru-paduraru , @chelaruc , @timcreative

**Comment by chelaruc** [comment]
Hi Nigar,

I followed your steps, but I don't get any errors. Can you give us more informations?

Best,
Ciprian

**Comment by norujlu** [comment]
Hi @chelaruc 
 Please find attached project. 
Open IE, but not maximize it, navigate to charts , then maximaze IE.

[Archive.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1266699/Archive.zip)
Thanks
Nigar.

**Comment by chelaruc** [comment]
Hi Nigar,

Please get the last version of MDP and try again. Tell me if you still get errors! 😄 

Best,
Ciprian

**Comment by norujlu** [comment]
I installed mdp

npm install mdp

But I still got the same  error..

cc: @chelaruc

**Comment by norujlu** [comment]
@alexandru-paduraru , @chelaruc 

Do you have any update regading this issue? Many thanks.

**Comment by chelaruc** [comment]
@norujlu 

Can you give me your archive?

Best,
Ciprian

**Comment by norujlu** [comment]
@chelaruc 

Yes, Archive.zip attached to the prevoius comment..

Uploading it again. See below.

[Archive(1).zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1274080/Archive.1.zip)

**Comment by chelaruc** [comment]
@norujlu 
1. I tested it with your archive, but I don't get any errors. 
2. Still don't have the latest version of MDP. Update to latest version [MDP](https://www.creative-tim.com/product/material-dashboard-pro-angular2)

Best,
Ciprian

**Comment by norujlu** [comment]
Hi @chelaruc 
When you say get latest version of MDP, do you mean npm install mdp?
Thanks

Nigar.

**Comment by chelaruc** [comment]
@norujlu 
No, you need to download the last version from [our site](https://www.creative-tim.com/product/material-dashboard-pro-angular2).

Best, 
Ciprian

**Comment by norujlu** [comment]
Hi @chelaruc , @alexandru-paduraru 
Can you please let me know which files have you updated in the new version of dashboard project, as we are working on the old version and  I need to know which files to replace to fix this issue.

Thanks

**Comment by chelaruc** [comment]
@norujlu, You need to download full project. We made major modifications on the product.

Best,
Ciprian

**Comment by alexandru-paduraru** [comment]
@norujlu the best option would be for us to share the BitBucket project and you will see in commits the changes for the files. You will see if a specific file that you used was modified and you manually add that changes. 

Otherwise, it is almost impossible to tell you which lines to change in files because we made a lot of modifications. Or if you have any suggestions on how we could do this more "automatic" please let us know and we will see what we can do in future updates.

Will this help?

Best,
Alex

**Comment by norujlu** [comment]
@alexandru-paduraru 

Yes, please could you please share the BitBucket project, so I can see which files have been updated.

Many thanks

Nigar.

**Comment by alexandru-paduraru** [comment]
@norujlu just sent an email to this email n.o*******und.com. Please check it.

Best,
Alex

**Comment by norujlu** [comment]
@alexandru-paduraru , @chelaruc , @timcreative 
We got the same issue in latest template as well. Can you please let me know how this can be fixed. Please see below attached file with latest MDP.

[DemoDashboard1_4.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1313898/DemoDashboard1_4.zip)
I noticed, when we comment out legends in chartist charts, IE works, hope it would help to identify what is the problem...

**Comment by norujlu** [comment]
@alexandru-paduraru , @chelaruc  do you have any update regading this issue?

**Comment by chelaruc** [comment]
@norujlu I can't run `npm install` for this archive. It gives me this error:
<img width="717" alt="screen shot 2017-09-21 at 10 15 42" src="https://user-images.githubusercontent.com/22840626/30683365-dd097700-9eb5-11e7-8a7b-c798965fa805.png">
Can you give me a good one?

**Comment by norujlu** [comment]
Hi @chelaruc , @alexandru-paduraru 

I have downloaded the same project and did npm install, then npm start, and I don't get any errors.
Could you pleasae create a demo project using your dashboard template and add legend and tooltip to one of the charts - this is what this demo project does at the moment which I provided. It works in Chrome, but not in IE.
![image](https://user-images.githubusercontent.com/31059539/31812149-fa6bb332-b579-11e7-9815-79fda93445af.png)


Many thanks

Nigar.

**Comment by norujlu** [comment]
@chelaruc , @alexandru-paduraru 

Do you have any update regarding this issue?

Thanks.

**Comment by alexandru-paduraru** [comment]
@norujlu we will have a look today and see how we can help :D

**Comment by chelaruc** [comment]
@norujlu We tested in our project and saw that we were getting the same error and thought it was our fault, but we tested in a new project and getting the same error. So I opened an issue to `chartist-plugin-legend Github repo` and you can see here if they will answer: [https://github.com/CodeYellowBV/chartist-plugin-legend/issues/47](https://github.com/CodeYellowBV/chartist-plugin-legend/issues/47)

All the best,
Ciprian
