### ISSUE TITLE
Adding a Route Parameter destroys layout

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#61]
I have a page which loads accounts via a route parameter:

`{
            path: 'clientaccount/:id',
            component: AccountViewClientComponent
    }`

If I leave off the /:id parameter, the page loads correctly; but if the parameter is there, the sidebar and the navigation bar are completely messed up. I can achieve the same issue in the dashboard project by adding the parameter to a route.

**Comment by chelaruc** [comment]
Hi, @mcurrycl! Thank you for using our product! Have you tried [this](https://angular.io/guide/router) tutorial?

Best, 
Ciprian

**Comment by mcurrycl** [comment]
That is exactly the tutorial I was using:
` { path: 'crisis-center', component: CrisisListComponent },
  { path: 'hero/:id',      component: HeroDetailComponent },`

In these two routes, the first renders correctly, the second breaks the layout of your AdminLayoutComponent if you add it as a route for, say, the FormsComponent.

**Comment by chelaruc** [comment]
@mcurrycl, can you give me your archive?

**Comment by mcurrycl** [comment]
Just use the latest Angular Admin Dashboard project.
Change forms.routing.ts to read:
`import { Routes } from '@angular/router';

import { ExtendedFormsComponent } from './extendedforms/extendedforms.component';
import { RegularFormsComponent } from './regularforms/regularforms.component';
import { ValidationFormsComponent } from './validationforms/validationforms.component';
import { WizardComponent } from './wizard/wizard.component';

export const FormsRoutes: Routes = [
    **{
        path: 'regular/:id',
        component: RegularFormsComponent
},** {
    path: '',
    children: [ {
      path: 'extended',
      component: ExtendedFormsComponent
    }]
    }, {
    path: '',
    children: [ {
      path: 'validation',
      component: ValidationFormsComponent
    }]
    }, {
        path: '',
        children: [ {
            path: 'wizard',
            component: WizardComponent
        }]
    }
];`

and then navigate to 

http://localhost:4200/forms/regular/22

**Comment by mcurrycl** [comment]
I can't make the "Routes" import above read correctly, but it is unchanged. Just the regular forms route is changed.

**Comment by chelaruc** [comment]
@mcurrycl In the tutorial, you have `hero.service.ts` which gives you the id for routes. Did you do that?

**Comment by mcurrycl** [comment]
I can get the value of the id fine. It is just that the layout of the generated HTML looks like this as soon as I add the /:id bit:
![image](https://user-images.githubusercontent.com/8777232/30025943-29bd2718-91be-11e7-8cf4-b77b21f155ff.png)

**Comment by chelaruc** [comment]
What errors did you get in browser console?

**Comment by mcurrycl** [comment]
This is from IE:
![image](https://user-images.githubusercontent.com/8777232/30026197-2f909af2-91bf-11e7-96b3-a7f097c92662.png)

**Comment by chelaruc** [comment]
@mcurrycl Can you try replace
```
{
path: 'regular/:id',
component: RegularFormsComponent
}
```
with 
```
 {
path: '',
children: [ {
path: 'regular/:id',
component: RegularFormsComponent
}
```
Tell me if it worked for you!

Best,
Ciprian
