### ISSUE TITLE
Incorrect path in sidebar routes

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#62]
I am having an issue with routing like described in the forum,If I have a composed path with a '/' It might be escaped. I have this error: Error: Cannot match any routes. URL Segment: 'ticketBlocks%2fmovements'
If I have a path like this in your **sidebar.ts**
{
    path: '/',
    title: werehouse,
    type: 'sub',
    icontype: 'assignment_turned_in',
    children: [
      {path: 'ticketBlocks/movements', title: ticketBlocksmovements, ab: 'SP'}
    ]
  }

In **sidebar-routes.config**
export const ROUTES: RouteInfo[] = [
 {path: '/ticketBlocks/movements', title: 'Spostamenti', icon: 'material-icons'}

In my **app.routing**
{
        path: 'ticketBlocks/movements',
        loadChildren: './ticket-blocks/ticket-block-movement-list/ticket-block-movement-list.module#TicketBlockMovementListModule'
      }

**Comment by alexandru-paduraru** [comment]
@lippomano thank you for using our product. We will have a look into this and come back with a solution.

Best,
Alex

**Comment by chelaruc** [comment]
Hi, @lippomano! Can you replace `path:'/'` with `path:''` in `sidebar.ts`? Tell me if it worked.

Best,
Ciprian

**Comment by lippomano** [comment]
No, same error

**Comment by chelaruc** [comment]
@lippomano Need to see all your routing files to fix the problem. Can you send me an email with the routing files at `ciprian@creative-tim.com`?

**Comment by lippomano** [comment]
Do you have some news about it?

**Comment by chelaruc** [comment]
@lippomano Sorry for the late response! Have you tried to include the ticketBlocks/movements like a child of ticketBlocks with path /movements?

**Comment by chelaruc** [comment]
@lippomano Can you tell me if you found a solution for this? So I can close it.

**Comment by lippomano** [comment]
Sorry @chelaruc can you give me an example?
At the moment I have this 2 routings:

```
{
  path: '/',
  title: 'sidebar.titles.werehouse',
  type: 'sub',
  icontype: 'assignment_turned_in',
  collapse: 'werehouse',
  children: [
    {
      path: 'ticketBlocks', title: 'sidebar.titles.ticketblocks', ab: 'G'
    },
    {
      path: 'ticketBlocksmovements', title: 'sidebar.titles.ticketblockmovements', ab: 'SP'
    }
  ]
}
```
And of course I want a path like: 'ticketBlocks/movements' in th sidebar

**Comment by lippomano** [comment]
But in my case ticketBlocks and ticketBlocksmovements are 2 different page:

**App.routing:**
```
      {
        path: 'ticketBlocks',
        loadChildren: './ticket-blocks/ticket-block-list/ticket-block-list.module#TicketBlockListModule',
        data: { roles: ['role.admin', 'role.backoffice', 'role.user'] }
      },
      {
        path: 'ticketBlocksmovements',
        loadChildren: './ticket-blocks/ticket-block-movement-list/ticket-block-movement-list.module#TicketBlockMovementListModule',
        data: { roles: ['role.admin', 'role.backoffice'] }
      },
```

**Comment by chelaruc** [comment]
You are right, but you can make the second page to be child for the first one and it will be different pages.
