### ISSUE TITLE
Date picker issue on last version "1.4.1"

### ISSUE THREAD

**Issue by gassuncaocosta** [creativetimofficial/material-dashboard-pro-angular#63]
I'm having an issue on datepicker, when trying to access any form page, on "vanilla" project.

- Downloaded new version from my account
- Ran npm install
- Ran ng serve or npm start
- Click on form page (Regular Forms or Extended Forms or Validation Forms)

![image](https://user-images.githubusercontent.com/24612762/30038751-6bf92cdc-919e-11e7-922a-920e33989326.png)

Any suggestion?

**Comment by sveg-pl** [comment]
The mdDatepicker needs no `<button>` tag. Please see in the pull request section, I provided a solution:

Remove the line 9 (<button...) and insert:
`<md-datepicker-toggle mdSuffix [for]="resultPicker"></md-datepicker-toggle>`

Remove the line 23 (<button...) and insert:
`<md-datepicker-toggle mdSuffix [for]="datepickerYear"></md-datepicker-toggle>`

Hope it helps!

**Comment by chelaruc** [comment]
@gassuncaocosta please follow instructions provided by @sveg-pl. @sveg-pl  thank you for helping us to improve this product!

Best,
Ciprian

**Comment by gassuncaocosta** [comment]
Thanks! Problem solved.
