### ISSUE TITLE
Error in sidebar when go back location

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#64]
Hi, In my project when I use location.back() or just click back with browser sometimes I have this error: this.setParentCollapse is not a function at sidebar.component.ts:57

**Comment by chelaruc** [comment]
@lippomano Thank you for using our product! Please update this project to the latest version 1.4.1!

Best,
Ciprian

**Comment by lippomano** [comment]
What is the best practice to update the theme?

**Comment by chelaruc** [comment]
@lippomano, you need to download it again with the latest version.

Best,
Ciprian
