### ISSUE TITLE
Is this kit for angularJS or angular2+?

### ISSUE THREAD

**Issue by halukkaramete** [creativetimofficial/material-dashboard-pro-angular#65]
I'm sorry for this uneducated question but is this kit for AngularJS or angular 2+? 
The version number 1.4.x sounds like, it is for the old angular.

**Comment by alexandru-paduraru** [comment]
@halukkaramete thank you for your interest in our product. It is for Angular 2+ CLI, the v1.4.x is our internal versioning system for our product, it doesn't have anything in common with the versioning system from Angular. Hope this makes sense :D

Best,
Alex
