### ISSUE TITLE
Error mdDatepickerToggle when using Forms Example

### ISSUE THREAD

**Issue by gerhardStone** [creativetimofficial/material-dashboard-pro-angular#67]
![image](https://user-images.githubusercontent.com/8873412/30240238-b0196496-956c-11e7-83b0-26489cf36d3b.png)

I had to change extendedforms.component.html into

![image](https://user-images.githubusercontent.com/8873412/30240258-fb7bbc04-956c-11e7-9011-f084a043efd5.png)

I bought the dashboard pro angular and downloaded it today. Do i have an old version?

**Comment by sveg-pl** [comment]
Can be fixed, see:
https://github.com/creativetimofficial/material-dashboard-pro-angular/pull/66

**Comment by alexandru-paduraru** [comment]
@gerhardStone did you got it working?

**Comment by gerhardStone** [comment]
it's now working

**Comment by alexandru-paduraru** [comment]
@gerhardStone please let the issue open till we do the official release. Thank you!

**Comment by alexandru-paduraru** [comment]
Fixed in v1.4.2
