### ISSUE TITLE
Components are appended to the top of the page

### ISSUE THREAD

**Issue by ao1000** [creativetimofficial/material-dashboard-pro-angular#68]
Specific to Firefox . I've removed child modules and instead i'm routing directly to components. so in app.routing -> AppRoutes -> AdminLayoutComponent -> children: [{ path: "users", component: UsersComponent }] .

For every route that i'm navigating to, the component is being appended to the top of the page while the desired behaviour is that components should be swapped.

**Comment by chelaruc** [comment]
@ao1000 thank you for using our products. I'm not sure what you want to do. Can you send me some print screens?

Best,
Ciprian

**Comment by ao1000** [comment]
![3](https://user-images.githubusercontent.com/6130611/30395810-1e7cfce8-98d0-11e7-8c97-a949bce99cfd.png)
![2](https://user-images.githubusercontent.com/6130611/30395811-1e7eea26-98d0-11e7-90db-be86fbb3659b.png)
![1](https://user-images.githubusercontent.com/6130611/30395812-1e804696-98d0-11e7-9b98-672138ef35d0.png)

Here's the routing.. as you can see i'm only using dashboard as a module, the rest i'm routing directly to components

`const appRoutes: Routes = [
  {
    path: '',
    redirectTo: 'dashboard',
    pathMatch: 'full',
  },
  {
    path: '', component: AdminLayoutComponent, canActivate: [AuthGuard],
    children: [
      { path: '', loadChildren: './dashboard/dashboard.module#DashboardModule' },
      { path: "customers", loadChildren: "", component: AllCustomersComponent },
      { path: "pos/all", loadChildren: "", component: AllPosComponent },
   ]
}`

**Comment by chelaruc** [comment]
@ao1000 Delete loadChildren: "" and all should work fine.

Best,
Ciprian

**Comment by ao1000** [comment]
@chelaruc tired that, still having the same problem .. again this is only on Firefox, Chrome is fine

**Comment by chelaruc** [comment]
Have you imported and declared all components from app.routes.ts in app.module.ts?

**Comment by ao1000** [comment]
Yes. otherwise it wont compile. Here's the app.module

[app.module.ts.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1302395/app.module.ts.zip)

**Comment by chelaruc** [comment]
I tested in our project and went well on Firefox. Can you give me your project to test? You can send me an email at `ciprian@creative-tim.com`.

**Comment by ao1000** [comment]
It's really hard for me to decouple it from the backend at the moment, I'll try digging more deeply and get back to you

**Comment by ao1000** [comment]
Looks the problem was from my side. I was implementing ngOnDestroy{} wrong, it's fine now. Thanks

**Comment by bfheythem** [comment]
@ao1000 how did u solve it ? 
can you please share with me the ngOnDestroy implementaion 
I ve been stuck for like 3 pbm having the same problem after consuming a REST api , using subscribe
