### ISSUE TITLE
Cannot find module magic-string

### ISSUE THREAD

**Issue by teacii** [creativetimofficial/material-dashboard-pro-angular#69]
Hi,
I just bought this app.
did 
```
npm install
npm update
ng serve

```
and it says:
Cannot find module 'magic-string'

I would have expected it to work out of the box at least. 

Any help?

**Comment by chelaruc** [comment]
@teacii thank you for using our product. Have you followed the instructions from documentation?
![screen shot 2017-09-11 at 17 57 44](https://user-images.githubusercontent.com/22840626/30281335-c9241a44-971a-11e7-92a4-8ee65d0d1e65.png)

Best, 
Ciprian

**Comment by teacii** [comment]
Hi,

As I said, I follow the exact steps and all I get is a whole bunch of errors.
I recorded it in a video. See here http://snap.ashampoo.com/nRPkGGGy

Thanks for the help.

**Comment by chelaruc** [comment]
@teacii Replace line 38:
 ````      
"../node_modules/datatables.net/js/jquery.dataTables.js"
```` 
from `angular-cli.json` with 
```
"../node_modules/datatables/media/js/jquery.dataTables.js"
```
Tell me if it worked.

Best,
Ciprian

**Comment by shanewoodruff** [comment]
I had the same problem and the above fixed it for me.

**Comment by Jackeysharath** [comment]
thank you this fixed my issue.
Can someone tell me what is the cause for that?

**Comment by chelaruc** [comment]
@Jackeysharath they made some changes to the plugin and changed the paths to .js files.
