### ISSUE TITLE
In the demo login/register/login page the hamburger does not work

### ISSUE THREAD

**Issue by DuckyChocobo** [creativetimofficial/material-dashboard-pro-angular#7]
Any instructions on how to fix it? I like the template and want to use it as our login page but this really breaks it.

**Comment by dragosct10** [comment]
Hi @DuckyChocobo! For fixing this issue you must go in the html page and add in the bottom of the page the following code: `<script src="./assets/js/init/initMenu.js"></script>`. Please tell us if everything is working fine!

Regards,
Dragos

**Comment by DuckyChocobo** [comment]
It works now, ty

**Comment by alexandru-paduraru** [comment]
fixed in v1.0.1
