### ISSUE TITLE
styles.bundle.css not found

### ISSUE THREAD

**Issue by netinhoteixeira** [creativetimofficial/material-dashboard-pro-angular#70]
When using a container like Apache HTTPD, it has a problem with routes and relative urls.

On file index.html, exists a code `<base href="/">` but after code `<body class="bootstrap-collapse">`.

To fix this problem, it need to be moved to top of file, after tag `<head>`, so it is solved.

**Comment by chelaruc** [comment]
@netinhoteixeira Thank you for using our product and for this information.

Best,
Ciprian
