### ISSUE TITLE
Validation Forms - Password match issue (v1.4.1)

### ISSUE THREAD

**Issue by gassuncaocosta** [creativetimofficial/material-dashboard-pro-angular#74]
Hi. I'm having an issue with password match and, when checking live preview at website, the problem is occuring there too.

![image](https://user-images.githubusercontent.com/24612762/30296618-2b2ebb86-971b-11e7-9171-f6891b0b4ead.png)

Validations are not working correctly. 

Any "official" suggestion?

**Comment by chelaruc** [comment]
@gassuncaocosta thank you for using our product. We'll check this and we'll come with a solution.

Best, Ciprian

**Comment by chelaruc** [comment]
fixed in v1.4.5
