### ISSUE TITLE
$.material.init() in app.component not working for content pages

### ISSUE THREAD

**Issue by donnytian** [creativetimofficial/material-dashboard-pro-angular#77]
I do have `$.material.init();` in app.component.ts, but still have issue with animations for buttons and input labels in my right content pages. I tried to move the init call into each feature component, then they are ok. 

So the initialization in app.component.ts seem not working for content pages. They have to call it again evertime in ngOnInit? Any better solution for this?

**Comment by chelaruc** [comment]
@donnytian thank you for using our product. In our project, it works perfectly. Can you give us more details?

Best,
Ciprian

**Comment by chelaruc** [comment]
@donnytian Have you found a solution?
