### ISSUE TITLE
checkbox is not displaying 1.4.1

### ISSUE THREAD

**Issue by donnytian** [creativetimofficial/material-dashboard-pro-angular#78]
I am following sample of checkbox but cannot see it as the first column in the table:
```
<div class="checkbox">
    <label>
        <input type="checkbox" [(ngModel)]="row.completed" name="optionsCheckboxes">
    </label>
</div>
```
I've also called init both in AppComponent and in the feature component:
```
    ngAfterViewInit() {
        $.material.init();
    }
```

below is the screenshot:
![snipaste_20170914_112047](https://user-images.githubusercontent.com/5674023/30410647-01bba40a-993f-11e7-879c-fe5a95567485.png)

**Comment by chelaruc** [comment]
@donnytian thank you for using our product! What is `row.completed`?

Best, 
Ciprian

**Comment by donnytian** [comment]
Hi,
It's a boolean value in the model:
```
export class TodoModel {
    id: string;
    content: string;
    dueDate?: Date;
    completed: boolean;
    message: string;
}
```

**Comment by donnytian** [comment]
Hi, if I set static html for checkboxes like what in document, it works fine. But my use case is that I have to retrieve data from server and bind rows in component's `onInit`, so each row is dynamic, the `<span>` in the checkbox `div `has not been populated then. 
My workaround is adding these spans manually after the `input`:
```
<div class="checkbox">
    <label>
        <input type="checkbox" [(ngModel)]="row.completed" name="optionsCheckboxes">
        <span class="checkbox-material"><span class="check"></span></span>
    </label>
</div>
```
This is something tedious for each checkbox, can you please consider to fix this?

**Comment by chelaruc** [comment]
We'll check it and come back with an answer.

**Comment by chelaruc** [comment]
@donnytian Sorry for the late response! I tested that and it worked for me. Can you give me more details like your data from server? Or give me your project for testing.

**Comment by chelaruc** [comment]
@donnytian Have you found a solution?
