### ISSUE TITLE
problem with tooltips

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#79]
My tooltip content (title) is the result of a remote Get call and I see a standard tooptip instead of yours
![cattura](https://user-images.githubusercontent.com/27501745/30421840-53fb4884-993e-11e7-9656-19f8cadb06d5.PNG)
As you see the static part is loaded into your tooltip but it seems when retrieve the remote call part (date in this case) is loading a standard tooltip.

 Is it possible that the problem is when tooltip is initialized? 
```
  ngAfterViewInit() {
    $('[rel="tooltip"]').tooltip(); }
```

**Comment by chelaruc** [comment]
Hi, @lippomano! Have you added `rel="tooltip" title="Tooltip name"` on your tag?

**Comment by lippomano** [comment]
yes of course but inside the title I have a variable that is populated with the resultof a remote Get call, so maybe the tooltip is already initialized when the variable is populated

**Comment by chelaruc** [comment]
Can you activate tooltips AfterViewInit? Like:
````
ngAfterViewInit(){
 //  Activate the tooltips
       $('[rel="tooltip"]').tooltip();
}
````

Best, 
Ciprian

**Comment by lippomano** [comment]
yes, like in the theme
If you try to populate the title property with a remote get call you see the standard tooltip...

**Comment by chelaruc** [comment]
@lippomano Can you give me an example to test it?

**Comment by lippomano** [comment]
I see also in a page where I have to load the data from a Get call, I usually put all the html content inside a:
`<div class="card" *ngIf="selected">` So when selected is populated it show all the content, and if the tooltip is inside this ngIf I see the standard tooltip instead of yours.

So probably the problem is when to initialize the tooltip.

**Comment by chelaruc** [comment]
@lippomano Sorry for the late response :( You can use material tooltips from here: https://material.angular.io/components/tooltip/overview

Best,
Ciprian

**Comment by lippomano** [comment]
Yes with mat tooltips problem is solved
