### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by Mohendran** [creativetimofficial/material-dashboard-pro-angular#8]
Why have you guys added jquery and its supported plugins? 
Angular manipulates the shadow DOM to make faster renders whereas Jquery touches the DOM each time for a small operation... making the UI slower... It would be nice If you could remove jquery and make everything in pure Angular

**Comment by karocksjoelee** [comment]
Agreed , and this doesn't count as an Angular Theme . Code is based on jQuery under the component . 
I want a refund for real .

**Comment by alexandru-paduraru** [comment]
@Mohendran @karocksjoelee thank you for using our product and sorry to hear that it is now as you expected. How I described in the other comments (https://www.creative-tim.com/product/material-dashboard-pro-angular2), we've built MDPro Angular 2 as we had too many requests from our customers who wanted to migrate MD Pro HTML to Angular 2, and we just wanted to help them in the development process. 

It seems that the Angular 2 that we've built, is not in the best format and it is requesting more adjustments and changes. We noted all the feedback that we get and based on that we started to work for a new structure with different layouts, less jQuery, and components that are coming from typescript, not from HTML. 

The new structure can be checked here: https://github.com/creativetimofficial/lbdp-test-login. We will use this structure to work on MD Pro Angular CLI. Please check it and let us know if this is the right direction. And if you have any other feedback for this new structure please write it here and we will include it in the next release. 

We will release the new product in 2-3 weeks. Hope you understand this case and we are very sorry for the inconvenience. 

Best,
Alex!
