### ISSUE TITLE
How to use datatables.net-buttons-dt

### ISSUE THREAD

**Issue by dushiying** [creativetimofficial/material-dashboard-pro-angular#80]
It's my great pleasure to use this product
but, I find this cli not include datatables.net-buttons-dt
when I use NPM intall datatables.net-buttons-dt and follow datatables.net example
stll doesn't work
plz tell me how to use
thanks！！!

**Comment by dushiying** [comment]
Is anyone here？

**Comment by chelaruc** [comment]
@dushiying thank you for using our product! Have you installed [this](https://www.npmjs.com/package/datatables.net-buttons-dt) and import the `.js` file from node_modules in `angular-cli.json`?

Best,
Ciprian
