### ISSUE TITLE
Labels bad positioned

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/material-dashboard-pro-angular#81]
In my fields with input type="number" if I write something wrong like symbols '+' or '-' (or letters in Mozilla Firefox) I correctly see the field invalid but the label is over the text inserted:
![numb](https://user-images.githubusercontent.com/27501745/30496792-d5829a48-9a50-11e7-9cef-0bd657e41fc3.PNG)

And in my forms I see the labels sometimes are not in the correct position, when I submit a new form if I don't insert any value in some fields the server initialize it to 0 so after the Post request I read the response from the server to update my fields but I see these fields with label over the value:
![label](https://user-images.githubusercontent.com/27501745/30496525-f4303ea6-9a4f-11e7-90df-0322276f97a2.PNG)

**Comment by paramthind** [comment]
Getting same issue. Made a address input template but started getting this: 
<img width="409" alt="screen shot 2017-09-18 at 7 21 06 pm" src="https://user-images.githubusercontent.com/6757640/30573086-aa1d5584-9ca6-11e7-8e4d-a8149aff38fc.png">

**Comment by chelaruc** [comment]
@lippomano @paramthind  please add this code:
```
$.material.options.autofill = true;
$.material.init();
```
instead of
```
$.material.init();
```
inside file `src/app/app.component.ts` 

We will do this change in v1.4.2.

Best,
Ciprian

**Comment by lippomano** [comment]
I don't this works properly, now I see the field red when I focus it, before entering any value

**Comment by paramthind** [comment]
Same for me too.

**Comment by chelaruc** [comment]
Sorry for the late response. Can you give me an example? We tested it and it worked. Please check this video: https://vimeo.com/235537653.

**Comment by allowski** [comment]
I was having the same issue, I moved the model update into the ngOnInit and it's OK now
