### ISSUE TITLE
DataTable row selection

### ISSUE THREAD

**Issue by rbasniak** [creativetimofficial/material-dashboard-pro-angular#85]
Hi, I bought the theme and it's really wonderful and well done, but I'm having a hard time setting the datatable so I can select an item and emit a selected event when this happens.

None of the tables on the examples are selectable. I tried to find the answer on the original jquery component (datatables.net), but all examples are for valilla js and jquery. Can someone point me to the right direction here?

**Comment by chelaruc** [comment]
@rbasniak thank you for using our product! You can add a new function in `src/app/tables/datatable.net/datatable.component.ts` like that one:
``` 
table.on( 'click', 'td', function () {
            const $tr = $(this).closest('tr');

            const data = table.row($tr).data();
            alert( 'You press on Row: ' + data[0] + ' ' + data[1] + ' ' + data[2] + '\'s row.' );
        } );
```
and work with const `data`.
Tell me if it helped you.

Best,
Ciprian

**Comment by rbasniak** [comment]
@chelaruc Very strange i wasn't notified of the answer, but was notified of you closing the issue, so I didn't see it, sorry.

But this solves the problem. Thank you...
