### ISSUE TITLE
Page scroll position remain while navigating to different page

### ISSUE THREAD

**Issue by jariwbh** [creativetimofficial/material-dashboard-pro-angular#86]
Hi,

I don't know if this is intended behaviour but its seems wrong. If you are on page and scroll it to bottom, click any other page and scroll position remain there on open page.

this is happening on demo site also.

How to reproduce on demo site

1. Open http://md-pro-angular.creative-tim.com/tables/extended

2. Click dashboard.. page scroll position keep as it is.

How to keep page position on new loaded page on top ?

**Comment by chelaruc** [comment]
@jariwbh thank you for using our product! To keep page position on top you need to add this code in your layout component: 
````
    private _router: Subscription;
    constructor( private router: Router ) {    }
    ngOnInit() {
        this._router = this.router.events.filter(event => event instanceof NavigationEnd).subscribe((event: NavigationEnd) => {
          document.querySelector('.main-panel').scrollTop = 0;
        });
}
````
For our project, you need add only: 
```
document.querySelector('.main-panel').scrollTop = 0;
```
  on line 29 in `src/app/layouts/admin/admin.component.ts`.
Tell me if it worked for you.

Best, 
Ciprian

**Comment by jariwbh** [comment]
You mean this location ?

src/app/theme/layouts/admin/admin-layout.component.ts 

I made this change, did not work though.

**Comment by chelaruc** [comment]
I test it and it worked on our project. You sure you did the good changes? Can you give me your project or some images so I can help you?

Best,
Ciprian

**Comment by jariwbh** [comment]
git repo = https://github.com/jariwbh/timesvacanza

userid - admin
pwd - 12345

**Comment by jariwbh** [comment]
Did you able to pull code ?

**Comment by chelaruc** [comment]
I can't login with this userid and pwd. :(

**Comment by jariwbh** [comment]
its public repo. use this user id while running and login to app.

**Comment by chelaruc** [comment]
Hi @jariwbh. Sorry for the late response. I can't log in with username: admin and pwd: 12345.
![screen shot 2017-09-27 at 10 30 46](https://user-images.githubusercontent.com/22840626/30901144-504b9604-a36f-11e7-9953-7f0de859db73.png)
![screen shot 2017-09-27 at 10 30 42](https://user-images.githubusercontent.com/22840626/30901143-5047c164-a36f-11e7-8984-7bda63a6d2fe.png)

Can you tell me what to do?

**Comment by jariwbh** [comment]
please try again. 

could you update release with this fix ? We can get latest and update our code.

**Comment by chelaruc** [comment]
Hi, @jariwbh! Sorry for the late response. We update the product today and this issue was resolved. Check it out!

Best, 
Ciprian.

**Comment by jariwbh** [comment]
Thank you, it fixed.
