### ISSUE TITLE
Login page mobile layout issue - version 1.4.1

### ISSUE THREAD

**Issue by gassuncaocosta** [creativetimofficial/material-dashboard-pro-angular#91]
Hi. 

When accessing "http://md-pro-angular2.creative-tim.com/pages/login" on mobile, login page is not filling browser on 100%. The same is happening when simulating mobile at Chrome Inspector.

- iPhone 7 with Safari:

![image](https://user-images.githubusercontent.com/24612762/30825790-a948f1d6-a20a-11e7-9799-4ce6fdf9a414.png)

- Chrome Inspector:

![image](https://user-images.githubusercontent.com/24612762/30825863-f22c10c2-a20a-11e7-880b-ab49e8f921ed.png)

Any suggestion to fix it?

**Comment by dragosct10** [comment]
Hi @gassuncaocosta! For fixing this issue I will upload for you the scss partial `_responsive.scss` and what you have to do is to go in your project and replace this in `src/assets/sass/material-dashboard/_responsive.scss`. After you do that everything will work fine for you!

[_responsive.scss.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1333084/_responsive.scss.zip)

Regards,
Dragos

**Comment by gassuncaocosta** [comment]
Hi, @dragosct10!

It works. But I'm having another issue:

This code in "assets/css/material-dashboard.css" is overriding the fix:

```
@media (max-width: 991px)
material-dashboard.css:11301
.bootstrap-collapse .container {
    padding-right: 0;
    padding-left: 0;
}
```

The material-dashboard.css should be rewritten in "npm start", right?
Can you help me on this?

**Comment by dragosct10** [comment]
Hi @gassuncaocosta! Please go in `src/index.html` on the line `16` and delete the `<link href="../assets/css/material-dashboard.css" rel="stylesheet" />` because the scss is auto-compiling in `angular-cli.json`.

Regards,
Dragos.

**Comment by gassuncaocosta** [comment]
@dragosct10 it's done!

Thanks for help!
