### ISSUE TITLE
Button ripple effect missing in 1.4.2? 

### ISSUE THREAD

**Issue by MattHoneycutt** [creativetimofficial/material-dashboard-pro-angular#92]
It looks like the button ripple effect isn't working in 1.4.2.  I don't see it in the demos or the documentation.  Is there some extra step that is necessary in order to enable it now?

**Comment by chelaruc** [comment]
@MattHoneycutt thank you for using our product!To fix that, you need to add this line:
```        
"../node_modules/bootstrap-material-design/dist/js/ripples.min.js",
```
in `angular-cli.json` file, in scripts and restart the project.
Tell me if it worked for you.

Best,
Ciprian

**Comment by MattHoneycutt** [comment]
That got it, thanks!!  

Is there a performance reason (or something) that this was removed from the project template and demos?

**Comment by chelaruc** [comment]
No, it is not :)
