### ISSUE TITLE
Nested component is hidden due to css

### ISSUE THREAD

**Issue by mcurrycl** [creativetimofficial/material-dashboard-pro-angular#93]
I have a number of nested components that make up a larger page. I noticed that when I get to a certain level, one component is not rendered. Tracing through the generated DOM and css, I found that there is a CSS class for:
```
[_nghost-c6] {
  display: none;
}
```

Is this piece of CSS there for a purpose? How can I get my hidden component to be visible?

**Comment by chelaruc** [comment]
You don't need these lines of css. You can delete them. Tell me if you need something else 😄 

Best,
Ciprian

**Comment by chelaruc** [comment]
Fixed in v1.4.3
