### ISSUE TITLE
Material dashboard css or bootstrap stopped working properly

### ISSUE THREAD

**Issue by MSkraburski** [creativetimofficial/material-dashboard-pro-angular#95]
Hi, I am using your Dashboard for a while and faced new issue concerning Design features.

The main issue is that underlining the activated input stopped working properly. When I click on it nothing happens even though it should be underlined in a default 'primary' color. 

Secondly, it is all located in a wizard form and all the inputs are set as 'required'. Suddenly when none of the inputs are filled with value and I click 'Next' to go through to the second tab of the wizard the underlining works and the empty inputs are underlined in red.

Later on when I fill all the inputs with the proper values the color does not change and still displays an error red color even though I can proceed to the next tab of the wizard.

The whole issue is pretty confusing since it looks as if something got 'mixed' in bootstrap or material.css. Since the matter is urgent I would be hugely grateful if you can help me as soon as possible.

Regards

**Comment by chelaruc** [comment]
@MSkraburski Thank you for using our product! Can you tell me your version?

Best,
Ciprian

**Comment by MSkraburski** [comment]
If you ask for a MD version it is: Material Dashboard Pro Angular 2

**Comment by MSkraburski** [comment]
Apart from that features like: help-block, radio buttons, etc. stopped working completely...

**Comment by chelaruc** [comment]
Hi @MSkraburski 

Sorry for the late response. We tried multiple times to reproduce the errors but without success. Here is a video with our product: https://vimeo.com/236934284. For the version, we are looking for what you have in package.json.

Best,
Ciprian

**Comment by MSkraburski** [comment]
I found you face the same problem at your tutorial website. You'll find it
there: http://demos.creative-tim.com/material-dashboard/
documentation/tutorial-components.html . Check the input section and you
will get what I'm talking about. When I click the input it is not being
underlined in any color and furthermore the floating label does not work at
all.

Best regards,
Mikołaj

2017-10-05 16:56 GMT+02:00 Chelaru Ciprian <notifications@github.com>:

**Comment by MSkraburski** [comment]
And that is mine package.json that you asked for.

2017-10-06 10:36 GMT+02:00 Mikołaj Skraburski <skrabur96@gmail.com>:

**Comment by alexandru-paduraru** [comment]
@MSkraburski here is the second test https://vimeo.com/238049924 . We also sent that on email. Are you available for a Skype call where you can give us access to your website so we can check?

Best,
Alex
