### ISSUE TITLE
Fixed Top Menu and different side menu for each Top menu item choosen

### ISSUE THREAD

**Issue by touqeerm** [creativetimofficial/material-dashboard-pro-angular#96]
Hi Creative Team,
I'm using material dashboard pro and have created a fixed top menu. I need a separate side menu for each Top menu item choosen. Ex: The Top Menu has Operations, Revenue,etc.. When I choose Operations I need a different Sidebar with components listed sample as in the dashboard. I have seen that we specify the list and the items are loaded from the list for sidebar. How can we accomplish in having separate sidebar items. Please assist.

**Comment by alexandru-paduraru** [comment]
@touqeerm we just responded to the first request here: https://github.com/creativetimofficial/material-dashboard-pro/issues/74. Please let's keep the conversations in only 1 place so we don't miss anything.

Best,
Alex
