### ISSUE TITLE
Doubled Scrollbar

### ISSUE THREAD

**Issue by leeniu** [creativetimofficial/material-dashboard-pro-angular#99]
Hey peepz,

on routes that have a bit of content and are therefore scrollable, it happens that I get the standard windows scrollbar and the "perfect" scrollbar next to each other :)

![scrollbar-bug-2](https://user-images.githubusercontent.com/15927396/31239142-66a5cae4-a9fc-11e7-8de5-e8dcb22beb03.png)

![scrollbar-bug](https://user-images.githubusercontent.com/15927396/31239148-6ab8ea9e-a9fc-11e7-8569-07947dae5c8f.png)

As you can see in this images, the standard scrollbar only slides so far and disappears and I am left with the perfect scrollbar when scrolling further

**Comment by chelaruc** [comment]
fixed in v1.4.4

**Comment by leeniu** [comment]
Sry mate, but this issue actually is not resolved with the update. I am still facing the same problem. Would you mind reopening the ticket?

**Comment by chelaruc** [comment]
Can you tell me the browser and version?

**Comment by leeniu** [comment]
Of course, it is Chrome 61 on Windows 10
